(() => {
const T=window.THREE;if(!T||typeof player==='undefined')return;
const S={entities:new WeakMap(),time:0};
function state(e){let s=S.entities.get(e);if(!s){s={last:e.mesh.position.clone(),speed:0,hit:0,dead:0,phase:(e.mesh.id||0)*.73};S.entities.set(e,s)}return s}
function people(){const a=[player];if(typeof civilians!=='undefined')a.push(...civilians);if(typeof followers!=='undefined')a.push(...followers);if(typeof enemies!=='undefined')a.push(...enemies);return [...new Set(a)].filter(e=>e?.mesh&&e.actor)}
function animals(){return typeof livestock!=='undefined'?livestock.filter(a=>a?.mesh):[]}
function humanoid(e,dt,t){const s=state(e);const moved=e.mesh.position.distanceTo(s.last),spd=moved/Math.max(dt,.001);s.speed=s.speed*.72+spd*.28;s.last.copy(e.mesh.position);if(!e.alive){s.dead=Math.min(1,s.dead+dt*2.8);e.mesh.rotation.z+=(Math.PI/2-e.mesh.rotation.z)*Math.min(1,dt*7);e.actor.position.y=-.12*s.dead;return}if(e.__hitPulse>0||e.__hit16>0){s.hit=Math.min(.18,(s.hit||0)+dt);e.actor.rotation.z=Math.sin(t*45+s.phase)*.10}else if(!e.__swing15&&!e.__bow15)e.actor.rotation.z*=Math.max(0,1-dt*8);const moving=s.speed>.35;const run=s.speed>5.8;const amp=run?.105:.065,freq=run?14:9;if(moving&&!e.__swing15&&!e.__bow15){e.actor.position.y=Math.sin(t*freq+s.phase)*amp;const lean=Math.min(.12,s.speed*.012);e.actor.rotation.x+=(lean-e.actor.rotation.x)*Math.min(1,dt*8)}else if(!e.__swing15&&!e.__bow15){e.actor.position.y*=Math.max(0,1-dt*8);e.actor.rotation.x*=Math.max(0,1-dt*7)}if(e.__arms15&&!e.__swing15&&!e.__bow15&&moving){const swing=Math.sin(t*freq+s.phase)*(run?.42:.27);e.__arms15.left.rotation.x+=(swing-e.__arms15.left.rotation.x)*Math.min(1,dt*12);e.__arms15.right.rotation.x+=(-swing-e.__arms15.right.rotation.x)*Math.min(1,dt*12)}}
function animateAnimal(a,dt,t){if(!a.alive)return;const s=state(a);const moved=a.mesh.position.distanceTo(s.last),spd=moved/Math.max(dt,.001);s.speed=s.speed*.7+spd*.3;s.last.copy(a.mesh.position);if(s.speed<.3)return;const freq=s.speed>5?13:8,amp=a.type==='horse'||a.type==='camel'?.08:.045;a.mesh.rotation.z=Math.sin(t*freq+s.phase)*.025;a.mesh.position.y+=Math.abs(Math.sin(t*freq+s.phase))*amp}
function mountedMotion(dt,t){if(typeof mounted==='undefined'||!mounted||!mount)return;const speed=state(mount).speed;if(speed>.4){const f=speed>6?14:9;player.actor.position.y=1.25+Math.abs(Math.sin(t*f))*.12;player.actor.rotation.x=Math.sin(t*f)*.035}}
if(typeof damage==='function'){const old=damage;damage=function(e,a){if(e)e.__hit16=.16;const alive=e?.alive;const r=old(e,a);if(alive&&e&&!e.alive)e.__death16=1;return r}}
let last=performance.now();function loop(now){const dt=Math.min(.045,(now-last)/1000||0);last=now;const t=now/1000;S.time=t;for(const e of people()){if(e.__hit16)e.__hit16=Math.max(0,e.__hit16-dt);humanoid(e,dt,t)}for(const a of animals())animateAnimal(a,dt,t);mountedMotion(dt,t);requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessAnimations16=S;
})();