(()=>{
const T=window.THREE;if(!T||typeof player==='undefined')return;
const metal=new T.MeshLambertMaterial({color:0xc8c3ad,flatShading:true}),darkMetal=new T.MeshLambertMaterial({color:0x615e58,flatShading:true}),hair=new T.MeshLambertMaterial({color:0x342217,flatShading:true}),eye=new T.MeshBasicMaterial({color:0x17110d}),leather=new T.MeshLambertMaterial({color:0x70472d,flatShading:true}),wood=new T.MeshLambertMaterial({color:0x5a3922,flatShading:true}),stringMat=new T.MeshBasicMaterial({color:0xd9c9a5});
const enhanced=new WeakSet(),palette=[0xc6a36a,0xb88a58,0xd0bd91,0x8f6548,0xa77955,0x7d5034,0xc1a17a];
function clothFor(e,salt=0){const id=(e?.mesh?.id||0)+salt;return new T.MeshLambertMaterial({color:palette[Math.abs(id)%palette.length],flatShading:true})}
function box(p,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);p.add(q);return q}
function hideLegacyWeapon(e){if(e.equipment)e.equipment.visible=false}
function enhance(e){if(!e?.actor||enhanced.has(e)||e.type==='lion')return;enhanced.add(e);const a=e.actor,c1=clothFor(e,0),c2=clothFor(e,3);
const face=new T.Group();box(face,.13,.09,.055,eye,-.17,2.97,.408);box(face,.13,.09,.055,eye,.17,2.97,.408);box(face,.18,.055,.05,hair,-.17,3.08,.41);box(face,.18,.055,.05,hair,.17,3.08,.41);box(face,.13,.16,.08,mats.skin,0,2.84,.44);box(face,.42,.16,.07,hair,0,2.67,.405);box(face,.30,.28,.09,hair,0,2.56,.36);a.add(face);e.__face15=face;
// Wrapped cloth stays around the head; nothing projects vertically above it.
const wrap=new T.Group();box(wrap,.92,.20,.92,c1,0,3.16,0);box(wrap,.84,.15,.94,c2,0,3.28,0);box(wrap,.16,.58,.18,c1,-.38,2.95,-.08);box(wrap,.14,.44,.17,c2,.37,2.92,-.10);a.add(wrap);e.__headwrap15=wrap;
const robe=new T.Group();box(robe,1.15,1.08,.78,c2,0,1.25,0);box(robe,1.02,.28,.78,leather,0,1.80,0);box(robe,.88,.38,.72,c1,0,2.04,0);a.add(robe);e.__robe15=robe;
const arms=new T.Group(),lm=e.enemy?mats.enemy:mats.skin,leftPivot=new T.Group(),rightPivot=new T.Group();leftPivot.position.set(-.62,2.2,0);rightPivot.position.set(.62,2.2,0);box(leftPivot,.24,1.18,.25,lm,0,-.48,0);box(rightPivot,.24,1.18,.25,lm,0,-.48,0);arms.add(leftPivot,rightPivot);a.add(arms);e.__arms15={left:leftPivot,right:rightPivot};
for(const ch of a.children){if(ch===arms||ch===face||ch===wrap||ch===robe)continue;if(ch.isMesh&&ch.material===mats.black)ch.visible=false}
const legs=new T.Group(),lp=new T.Group(),rp=new T.Group();lp.position.set(-.26,1.02,0);rp.position.set(.26,1.02,0);box(lp,.28,1.02,.30,mats.black,0,-.50,0);box(rp,.28,1.02,.30,mats.black,0,-.50,0);legs.add(lp,rp);a.add(legs);e.__legs15={left:lp,right:rp};
if(e===player){hideLegacyWeapon(e);const hand=new T.Group();rightPivot.add(hand);const staff=box(hand,.13,2.55,.13,wood,.18,-1.35,.12);staff.rotation.x=.42;staff.rotation.z=-.20;const swordGroup=new T.Group();hand.add(swordGroup);const blade=box(swordGroup,.16,1.42,.08,metal,.14,-1.18,.10);blade.rotation.x=.42;blade.rotation.z=-.22;box(swordGroup,.48,.10,.14,darkMetal,.14,-.55,.10);box(swordGroup,.14,.50,.14,leather,.14,-.33,.10);e.__weapons15={staff,sword:swordGroup,mode:'staff'};swordGroup.visible=false;e.__weapon15='staff'}else{hideLegacyWeapon(e);const weapon=new T.Group();rightPivot.add(weapon);if(e.role==='archer'){const upper=box(weapon,.09,.9,.09,mats.bow,.18,-.85,.10);upper.rotation.z=.48;const lower=box(weapon,.09,.9,.09,mats.bow,.18,-1.45,.10);lower.rotation.z=-.48;box(weapon,.025,1.55,.025,stringMat,.39,-1.13,.10);e.__weapon15='bow'}else{const spear=box(weapon,.12,2.35,.12,wood,.12,-1.30,.08);spear.rotation.x=.38;spear.rotation.z=-.18;e.__weapon15='staff'}}
}
function setPlayerWeapon(mode){enhance(player);const w=player.__weapons15;if(!w)return;w.mode=mode==='sword'?'sword':'staff';w.staff.visible=w.mode==='staff';w.sword.visible=w.mode==='sword';player.__weapon15=w.mode;if(typeof flash==='function')flash(w.mode==='sword'?'⚔️ Espada desenvainada':'Bastón en mano',900);updateWeaponButton()}
function togglePlayerWeapon(){setPlayerWeapon(player.__weapons15?.mode==='sword'?'staff':'sword')}
function ensureSword(){if(player.__weapons15?.mode!=='sword')setPlayerWeapon('sword')}
function markMelee(e){if(e===player)ensureSword();if(e)e.__swing15=.34}function markBow(e){if(e)e.__bow15=.42}
if(typeof playerAttack==='function'){const old=playerAttack;playerAttack=function(){markMelee(player);return old()}}
if(typeof fireArrow==='function'){const old=fireArrow;fireArrow=function(shooter,target,friendly){markBow(shooter);return old(shooter,target,friendly)}}
function all(){const arr=[player];if(typeof civilians!=='undefined')arr.push(...civilians);if(typeof followers!=='undefined')arr.push(...followers);if(typeof enemies!=='undefined')arr.push(...enemies);return[...new Set(arr)]}
function animateUpper(e,dt){enhance(e);const ar=e.__arms15;if(!ar)return;let lx=0,rx=0,rz=0;if(e.__swing15>0){e.__swing15=Math.max(0,e.__swing15-dt);const p=1-e.__swing15/.34,arc=Math.sin(p*Math.PI);rx=-1.15+arc*2.05;rz=-.25+arc*.58;lx=.18}else if(e.__bow15>0){e.__bow15=Math.max(0,e.__bow15-dt);rx=-1.05;lx=-.95;rz=-.25}ar.left.rotation.x+=(lx-ar.left.rotation.x)*Math.min(1,dt*16);ar.right.rotation.x+=(rx-ar.right.rotation.x)*Math.min(1,dt*18);ar.right.rotation.z+=(rz-ar.right.rotation.z)*Math.min(1,dt*18)}
const btn=document.createElement('button');btn.id='weapon-toggle15';btn.style.cssText='position:fixed;z-index:76;right:calc(12px + env(safe-area-inset-right,0px));top:calc(52px + env(safe-area-inset-top,0px));border:1px solid #d8b97a99;border-radius:8px;background:#25180dcc;color:#fff0cf;padding:7px 9px;font:800 9px ui-monospace,monospace;pointer-events:auto';btn.onclick=togglePlayerWeapon;document.body.appendChild(btn);function updateWeaponButton(){btn.textContent=player.__weapons15?.mode==='sword'?'GUARDAR ESPADA':'SACAR ESPADA'}
addEventListener('keydown',e=>{if(e.code==='KeyK'&&!e.repeat)togglePlayerWeapon()});
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;for(const e of all())if(e?.alive)animateUpper(e,dt);updateWeaponButton();requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessCharacters15={enhance,setPlayerWeapon,togglePlayerWeapon};
})();