(()=>{
const T=window.THREE;if(!T||typeof player==='undefined')return;
const metal=new T.MeshLambertMaterial({color:0xd8d3bc,flatShading:true}),darkMetal=new T.MeshLambertMaterial({color:0x5a5650,flatShading:true}),hair=new T.MeshLambertMaterial({color:0x342217,flatShading:true}),eye=new T.MeshBasicMaterial({color:0x17110d}),leather=new T.MeshLambertMaterial({color:0x70472d,flatShading:true}),cloth=new T.MeshLambertMaterial({color:0xc6a36a,flatShading:true}),cloth2=new T.MeshLambertMaterial({color:0x7d5034,flatShading:true}),wood=new T.MeshLambertMaterial({color:0x5a3922,flatShading:true}),stringMat=new T.MeshBasicMaterial({color:0xd9c9a5});
const enhanced=new WeakSet();
function box(p,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);p.add(q);return q}
function hideLegacyWeapon(e){if(e.equipment)e.equipment.visible=false}
function clothFor(e){const r=((e.mesh?.id||1)*37)%5;return [cloth,cloth2,new T.MeshLambertMaterial({color:0x8e7654,flatShading:true}),new T.MeshLambertMaterial({color:0xb6976f,flatShading:true}),new T.MeshLambertMaterial({color:0x69533d,flatShading:true})][r]}
function enhance(e){if(!e?.actor||enhanced.has(e)||e.type==='lion')return;enhanced.add(e);const a=e.actor,c1=clothFor(e);
const face=new T.Group();box(face,.13,.09,.055,eye,-.17,2.97,.408);box(face,.13,.09,.055,eye,.17,2.97,.408);box(face,.18,.055,.05,hair,-.17,3.08,.41);box(face,.18,.055,.05,hair,.17,3.08,.41);box(face,.13,.16,.08,mats.skin,0,2.84,.44);box(face,.42,.16,.07,hair,0,2.67,.405);box(face,.30,.28,.09,hair,0,2.56,.36);a.add(face);e.__face15=face;
const wrap=new T.Group();box(wrap,.95,.16,.92,c1,0,3.24,0);box(wrap,.90,.15,.96,cloth2,0,3.36,0);box(wrap,.14,.54,.18,c1,-.40,3.02,-.10);box(wrap,.12,.38,.17,c1,.39,3.05,-.12);a.add(wrap);e.__headwrap15=wrap;
const robe=new T.Group();box(robe,1.18,1.10,.80,c1,0,1.28,0);box(robe,1.06,.34,.78,leather,0,1.82,0);box(robe,1.02,.55,.76,c1,0,.78,0);a.add(robe);e.__robe15=robe;
const arms=new T.Group(),lm=e.enemy?mats.enemy:mats.skin,leftPivot=new T.Group(),rightPivot=new T.Group();leftPivot.position.set(-.62,2.2,0);rightPivot.position.set(.62,2.2,0);box(leftPivot,.24,1.18,.25,lm,0,-.48,0);box(rightPivot,.24,1.18,.25,lm,0,-.48,0);arms.add(leftPivot,rightPivot);a.add(arms);e.__arms15={left:leftPivot,right:rightPivot};
for(const ch of a.children){if(ch===arms||ch===face||ch===wrap||ch===robe)continue;if(ch.isMesh&&ch.material===mats.black)ch.visible=false}
const legs=new T.Group(),lp=new T.Group(),rp=new T.Group();lp.position.set(-.26,1.02,0);rp.position.set(.26,1.02,0);box(lp,.28,1.02,.30,mats.black,0,-.50,0);box(rp,.28,1.02,.30,mats.black,0,-.50,0);legs.add(lp,rp);a.add(legs);e.__legs15={left:lp,right:rp};
if(e===player){hideLegacyWeapon(e);const hand=new T.Group();rightPivot.add(hand);const staffGroup=new T.Group();hand.add(staffGroup);const staff=box(staffGroup,.13,2.60,.13,wood,.12,-1.20,.18);staff.rotation.x=.32;staff.rotation.z=-.12;const swordGroup=new T.Group();hand.add(swordGroup);swordGroup.position.set(.10,-.58,.15);swordGroup.rotation.x=-1.30;swordGroup.rotation.z=-.10;const blade=box(swordGroup,.18,1.68,.09,metal,0,.74,0);box(swordGroup,.54,.11,.16,darkMetal,0,-.10,0);box(swordGroup,.15,.52,.15,leather,0,-.38,0);e.__weapons15={staff:staffGroup,sword:swordGroup,mode:'staff'};swordGroup.visible=false;e.__weapon15='staff'}else{hideLegacyWeapon(e);const weapon=new T.Group();rightPivot.add(weapon);if(e.role==='archer'){const upper=box(weapon,.09,.9,.09,mats.bow,.18,-.85,.10);upper.rotation.z=.48;const lower=box(weapon,.09,.9,.09,mats.bow,.18,-1.45,.10);lower.rotation.z=-.48;box(weapon,.025,1.55,.025,stringMat,.39,-1.13,.10);e.__weapon15='bow'}else{const spear=box(weapon,.12,2.35,.12,wood,.12,-1.20,.15);spear.rotation.x=.42;spear.rotation.z=-.14;e.__weapon15='staff'}}
}
function setPlayerWeapon(mode){enhance(player);const w=player.__weapons15;if(!w)return;w.mode=mode==='sword'?'sword':'staff';w.staff.visible=w.mode==='staff';w.sword.visible=w.mode==='sword';player.__weapon15=w.mode;if(typeof flash==='function')flash(w.mode==='sword'?'⚔️ Espada desenvainada':'Bastón en mano',900);updateWeaponButton()}
function togglePlayerWeapon(){setPlayerWeapon(player.__weapons15?.mode==='sword'?'staff':'sword')}
function ensureSword(){if(player.__weapons15?.mode!=='sword')setPlayerWeapon('sword')}
function markMelee(e){if(e===player)ensureSword();if(e)e.__swing15=.34}function markBow(e){if(e)e.__bow15=.42}
if(typeof playerAttack==='function'){const old=playerAttack;playerAttack=function(){markMelee(player);return old()}}
if(typeof fireArrow==='function'){const old=fireArrow;fireArrow=function(shooter,target,friendly){markBow(shooter);return old(shooter,target,friendly)}}
function all(){const arr=[player];if(typeof civilians!=='undefined')arr.push(...civilians);if(typeof followers!=='undefined')arr.push(...followers);if(typeof enemies!=='undefined')arr.push(...enemies);return[...new Set(arr)]}
function animateUpper(e,dt){enhance(e);const ar=e.__arms15;if(!ar)return;let lx=0,rx=0,rz=0;if(e.__swing15>0){e.__swing15=Math.max(0,e.__swing15-dt);const p=1-e.__swing15/.34,arc=Math.sin(p*Math.PI);rx=-1.05+arc*1.95;rz=-.20+arc*.52;lx=.18}else if(e.__bow15>0){e.__bow15=Math.max(0,e.__bow15-dt);rx=-1.05;lx=-.95;rz=-.25}else if(e===player&&e.__weapons15?.mode==='sword'){rx=-.62;rz=-.12}ar.left.rotation.x+=(lx-ar.left.rotation.x)*Math.min(1,dt*16);ar.right.rotation.x+=(rx-ar.right.rotation.x)*Math.min(1,dt*18);ar.right.rotation.z+=(rz-ar.right.rotation.z)*Math.min(1,dt*18)}
const btn=document.createElement('button');btn.id='weapon-toggle15';btn.style.cssText='position:fixed;z-index:76;right:calc(12px + env(safe-area-inset-right,0px));top:calc(52px + env(safe-area-inset-top,0px));border:1px solid #d8b97a99;border-radius:8px;background:#25180dcc;color:#fff0cf;padding:7px 9px;font:800 9px ui-monospace,monospace;pointer-events:auto';btn.onclick=togglePlayerWeapon;document.body.appendChild(btn);function updateWeaponButton(){btn.textContent=player.__weapons15?.mode==='sword'?'GUARDAR ESPADA':'SACAR ESPADA'}
addEventListener('keydown',e=>{if(e.code==='KeyK'&&!e.repeat)togglePlayerWeapon()});
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;for(const e of all())if(e?.alive)animateUpper(e,dt);updateWeaponButton();requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessCharacters15={enhance,setPlayerWeapon,togglePlayerWeapon};
})();