(()=>{const T=window.THREE,W=window.WildernessWorld;if(!T||!W||typeof player==='undefined'||typeof civilians==='undefined')return;const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;const state={agents:new Map(),decorated:new Set(),clock:0};
function rnd(e,s=0){const p=e.mesh.position;return W.randAt(Math.round(p.x),Math.round(p.z),8100+s)}function homeCenter(e){const h=e.home;return h?new T.Vector3(h.x,W.groundY(h.x,h.z),h.z):e.mesh.position.clone()}
function job(e){if(e.__life18)return e.__life18;const r=rnd(e,1);const kind=r<.28?'farmer':r<.48?'merchant':r<.67?'shepherd':r<.86?'artisan':'walker';e.__life18={job:kind,target:null,wait:rnd(e,2)*3,phase:rnd(e,3)*6.28};return e.__life18}
function chooseTarget(e,a){const h=e.home,c=homeCenter(e),rad=h?.type==='city'?(h.radius||24)*.72:18;let ang=rnd(e,20+Math.floor(performance.now()/9000))*Math.PI*2,rr=4+rnd(e,30+Math.floor(performance.now()/7000))*rad;if(a.job==='merchant'){rr=Math.min(rad,7+rnd(e,42)*5);ang=Math.floor(rnd(e,43)*4)*Math.PI/2}if(a.job==='shepherd')rr=rad*.8;if(a.job==='farmer')rr=rad*.7;a.target=new T.Vector3(c.x+Math.cos(ang)*rr,0,c.z+Math.sin(ang)*rr);a.target.y=W.groundY(a.target.x,a.target.z)}
function move(e,a,dt){if(!e.alive||e.recruited)return;if(!a.target||e.mesh.position.distanceTo(a.target)<1.1){a.wait-=dt;if(a.wait<=0){chooseTarget(e,a);a.wait=1.2+rnd(e,50)*3}return}const d=a.target.clone().sub(e.mesh.position);d.y=0;if(d.length()>0){d.normalize();const sp=a.job==='shepherd'?1.05:a.job==='merchant'?1.25:1.45;e.mesh.position.addScaledVector(d,sp*dt);e.mesh.position.y=W.groundY(e.mesh.position.x,e.mesh.position.z);e.mesh.rotation.y=Math.atan2(d.x,d.z)}}
function box(g,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);g.add(q);return q}const cloth=[0x9a4937,0x315d69,0xb28742,0x6e6840].map(c=>new T.MeshLambertMaterial({color:c,flatShading:true}));
function decorate(h){if(!h||state.decorated.has(h.id))return;state.decorated.add(h.id);const g=new T.Group();g.name='life18-'+h.id;const r=h.type==='city'?(h.radius||23):15;const stalls=h.type==='city'?(mobile?3:5):2;for(let i=0;i<stalls;i++){const a=(i/stalls)*Math.PI*2,x=h.x+Math.cos(a)*Math.min(9,r*.45),z=h.z+Math.sin(a)*Math.min(9,r*.45),y=W.groundY(x,z);box(g,2.8,.18,2.1,cloth[i%cloth.length],x,y+2.1,z);for(const dx of[-1.15,1.15])box(g,.12,2,.12,mats.wood,x+dx,y+1,z);box(g,2.3,.55,1.4,mats.wood,x,y+.32,z)}if(h.type==='city'){for(let i=0;i<4;i++){const a=i*Math.PI/2,x=h.x+Math.cos(a)*r*.78,z=h.z+Math.sin(a)*r*.78,y=W.groundY(x,z);box(g,.18,3.4,.18,mats.wood,x,y+1.7,z);box(g,1.2,.75,.12,cloth[(i+1)%cloth.length],x+.5,y+2.7,z)}}scene.add(g)}
function guardPatrol(dt){if(typeof cities==='undefined')return;for(const c of cities){decorate(c);if(c.captured)continue;const guards=c.defendersRuntime?.filter(x=>x.alive&&x.role==='infantry').slice(0,mobile?2:4)||[];guards.forEach((e,i)=>{if(e.mesh.position.distanceTo(player.mesh.position)<14)return;const a=(performance.now()/9000+i/guards.length*Math.PI*2),r=(c.radius||22)*.78,tx=c.x+Math.cos(a)*r,tz=c.z+Math.sin(a)*r,d=new T.Vector3(tx-e.mesh.position.x,0,tz-e.mesh.position.z);if(d.length()>1){d.normalize();e.mesh.position.addScaledVector(d,1.25*dt);e.mesh.position.y=W.groundY(e.mesh.position.x,e.mesh.position.z);e.mesh.rotation.y=Math.atan2(d.x,d.z)}})}}
function nearbyHomes(){if(typeof generatedSettlements==='undefined')return;for(const h of generatedSettlements.values())if(Math.hypot(player.mesh.position.x-h.x,player.mesh.position.z-h.z)<120)decorate(h)}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;state.clock+=dt;const max=mobile?24:45;let n=0;for(const e of civilians){if(n>=max)break;if(!e.alive||e.recruited||!e.home)continue;if(e.mesh.position.distanceTo(player.mesh.position)>110)continue;move(e,job(e),dt);n++}guardPatrol(dt);if(state.clock>2){state.clock=0;nearbyHomes()}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessCityLife=state})();