// Wilderness 5.12.15 - solid structures, soft friendly-NPC collision, automatic step support for player and moving groups
(()=>{
const T=window.THREE,W=window.WildernessWorld,N=window.WildernessNations50;if(!T||!W||typeof scene==='undefined'||typeof player==='undefined'||typeof updatePlayer!=='function')return;
const STEP_HEIGHT=1.7;
const C={boxes:[],lastScan:0,lastCenter:new T.Vector3(1e9,0,1e9),safe:new WeakMap(),stepHeight:STEP_HEIGHT},wp=new T.Vector3(),size=new T.Vector3(),box=new T.Box3();
function visibleChain(o){for(let p=o;p&&p!==scene;p=p.parent)if(p.visible===false)return false;return true}
function noCollision(o){for(let p=o;p&&p!==scene;p=p.parent)if(p.userData?.noCollision)return true;return false}
function dynamicRoots(){const s=new Set([player.mesh]);if(typeof civilians!=='undefined')for(const e of civilians)if(e?.mesh)s.add(e.mesh);if(typeof followers!=='undefined')for(const e of followers)if(e?.mesh)s.add(e.mesh);if(typeof enemies!=='undefined')for(const e of enemies)if(e?.mesh)s.add(e.mesh);if(typeof livestock!=='undefined')for(const e of livestock)if(e?.mesh)s.add(e.mesh);if(typeof L06!=='undefined')for(const c of L06.caravans||[])if(c?.g)s.add(c.g);return s}
function underRoot(o,roots){for(let p=o;p&&p!==scene;p=p.parent)if(roots.has(p))return true;return false}
function terrainLike(o){for(let p=o;p&&p!==scene;p=p.parent)if((p.name||'').startsWith('terrain41-'))return true;return false}
function rebuild(force=false){const p=player.mesh.position;if(!force&&performance.now()-C.lastScan<800&&p.distanceToSquared(C.lastCenter)<324)return;C.lastScan=performance.now();C.lastCenter.copy(p);C.boxes.length=0;const roots=dynamicRoots();scene.updateMatrixWorld(true);scene.traverse(o=>{if(!o?.isMesh||o.isInstancedMesh||!visibleChain(o)||noCollision(o)||underRoot(o,roots)||terrainLike(o))return;if(o.material?.transparent&&o.material?.opacity<.9)return;o.getWorldPosition(wp);if(Math.hypot(wp.x-p.x,wp.z-p.z)>105)return;box.setFromObject(o);if(box.isEmpty())return;box.getSize(size);if(size.x>36||size.z>36||size.y<.16)return;if(size.y<.30&&Math.max(size.x,size.z)>1.5)return;if(size.x<.30&&size.z<.30&&size.y<1.45)return;const cx=(box.min.x+box.max.x)/2,cz=(box.min.z+box.max.z)/2;if(box.min.y>W.groundY(cx,cz)+1.05)return;const b=box.clone();b.min.x-=.16;b.max.x+=.16;b.min.z-=.16;b.max.z+=.16;C.boxes.push(b)})}
function overlapsXZ(b,pos,r){return pos.x+r>b.min.x&&pos.x-r<b.max.x&&pos.z+r>b.min.z&&pos.z-r<b.max.z}
function staticBlocked(pos,r=.48){for(const b of C.boxes)if(overlapsXZ(b,pos,r))return true;return false}
function supportTop(pos,r=.42,maxStep=STEP_HEIGHT){const ground=W.groundY(pos.x,pos.z);let top=ground;for(const b of C.boxes){if(!overlapsXZ(b,pos,r))continue;const rise=b.max.y-ground;if(rise<=.05||rise>maxStep+.05)continue;if(b.min.y>ground+.65)continue;top=Math.max(top,b.max.y+.025)}return top}
function stepHeightFor(e){if(e===player)return STEP_HEIGHT;switch(e?.type){case'horse':case'camel':return .82;case'cow':case'donkey':return .68;case'lion':return .72;case'sheep':case'goat':return .48;default:return 1.08}}
function entityStaticBlocked(e,pos,r=.48){const ground=W.groundY(pos.x,pos.z),maxStep=stepHeightFor(e);for(const b of C.boxes){if(!overlapsXZ(b,pos,r))continue;const rise=b.max.y-ground;if(rise>.05&&rise<=maxStep+.05&&b.min.y<=ground+.65)continue;return true}return false}
function playerStaticBlocked(pos,r=.48){const ground=W.groundY(pos.x,pos.z),canStep=!(typeof mounted!=='undefined'&&mounted);for(const b of C.boxes){if(!overlapsXZ(b,pos,r))continue;if(canStep){const rise=b.max.y-ground;if(rise>.05&&rise<=STEP_HEIGHT+.05&&b.min.y<=ground+.65)continue}return true}return false}
function radiusOf(e){if(e===player)return(typeof mounted!=='undefined'&&mounted&&typeof mount!=='undefined'&&mount)?1.02:.48;switch(e?.type){case'horse':return 1.05;case'camel':return 1.12;case'lion':return .76;case'sheep':case'goat':return .56;case'cow':return .82;case'donkey':return .78;default:return .48}}
function livingEntities(){const a=[];if(typeof civilians!=='undefined')a.push(...civilians);if(typeof followers!=='undefined')a.push(...followers);if(typeof enemies!=='undefined')a.push(...enemies);if(typeof livestock!=='undefined')a.push(...livestock);return[...new Set(a)].filter(e=>e&&e!==player&&e.alive!==false&&e.mesh&&e!==(typeof mount!=='undefined'?mount:null))}
function relationOf(e){const f=e?.faction||e?.nation||e?.home?.faction||e?.home?.nation;if(!f||!N?.relationTo)return null;try{return N.relationTo(f)}catch(_){return null}}
function blocksPlayer(e){if(!e||e.alive===false)return false;if(typeof followers!=='undefined'&&followers.includes(e))return false;if(typeof civilians!=='undefined'&&civilians.includes(e)&&!(typeof enemies!=='undefined'&&enemies.includes(e)))return false;if(typeof enemies!=='undefined'&&enemies.includes(e)){const r=relationOf(e);return !r||r==='hostile'||r==='war'}if(typeof livestock!=='undefined'&&livestock.includes(e))return['horse','camel','cow','donkey','lion'].includes(e.type);return false}
function dynamicBlocked(pos,r){for(const e of livingEntities()){if(!blocksPlayer(e)||e.mesh.visible===false)continue;const q=e.mesh.position,rr=r+radiusOf(e);if((pos.x-q.x)**2+(pos.z-q.z)**2<rr*rr)return true}if(typeof L06!=='undefined')for(const c of L06.caravans||[]){if(!c?.g?.visible)continue;const q=c.g.position,rr=r+2.35;if((pos.x-q.x)**2+(pos.z-q.z)**2<rr*rr)return true}return false}
const baseUpdate45=updatePlayer;updatePlayer=function(dt){rebuild();const before=player.mesh.position.clone(),r0=radiusOf(player),wasStatic=playerStaticBlocked(before,r0),wasDynamic=dynamicBlocked(before,r0);baseUpdate45(dt);const r=radiusOf(player),nowStatic=playerStaticBlocked(player.mesh.position,r),nowDynamic=dynamicBlocked(player.mesh.position,r);if((!wasStatic&&nowStatic)||(!wasDynamic&&nowDynamic)){player.mesh.position.x=before.x;player.mesh.position.z=before.z;if(typeof mounted!=='undefined'&&mounted&&typeof mount!=='undefined'&&mount){mount.mesh.position.x=before.x;mount.mesh.position.z=before.z}}};
function enforceStatic(e){if(!e?.mesh||e===(typeof mount!=='undefined'?mount:null))return;const p=e.mesh.position,r=radiusOf(e),prev=C.safe.get(e);if(entityStaticBlocked(e,p,r)){if(prev){p.x=prev.x;p.z=prev.z;p.y=supportTop(prev,r,stepHeightFor(e))}}else{p.y=supportTop(p,r,stepHeightFor(e));C.safe.set(e,p.clone())}}
function separate(){const es=[player,...livingEntities()];for(let i=0;i<es.length;i++)for(let j=i+1;j<es.length;j++){const a=es[i],b=es[j];if((a===player&&b===(typeof mount!=='undefined'?mount:null))||(b===player&&a===(typeof mount!=='undefined'?mount:null)))continue;const ap=a.mesh.position,bp=b.mesh.position,dx=bp.x-ap.x,dz=bp.z-ap.z,min=radiusOf(a)+radiusOf(b),d2=dx*dx+dz*dz;if(d2<=.0001||d2>=min*min)continue;const d=Math.sqrt(d2),nx=dx/d,nz=dz/d,push=(min-d)*((a===player||b===player)?.78:.52);if(a!==player&&a!==(typeof mount!=='undefined'?mount:null)){const x=ap.x-nx*push,z=ap.z-nz*push,tmp=new T.Vector3(x,ap.y,z);if(!entityStaticBlocked(a,tmp,radiusOf(a))){ap.x=x;ap.z=z}}if(b!==player&&b!==(typeof mount!=='undefined'?mount:null)){const x=bp.x+nx*push,z=bp.z+nz*push,tmp=new T.Vector3(x,bp.y,z);if(!entityStaticBlocked(b,tmp,radiusOf(b))){bp.x=x;bp.z=z}}}}
let last=0;function loop(t){rebuild();if(t-last>45){last=t;for(const e of livingEntities())enforceStatic(e);separate()}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessCollision45={version:'5.12.15',state:C,rebuild,staticBlocked,entityStaticBlocked,playerStaticBlocked,supportTop,stepHeightFor,dynamicBlocked,blocksPlayer,STEP_HEIGHT};
})();