// Wilderness 5.10 - Kingdoms & Conquest: political control, governors, garrisons, tribute and rebellions
(()=>{
const T=window.THREE,W=window.WildernessWorld,N=window.WildernessNations50,H=window.WildernessHistorical52,D55=window.WildernessDiplomacy55,S57=window.WildernessSiege57;
if(!T||!W||!N||!H||!D55||!S57||typeof scene==='undefined'||typeof player==='undefined')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820,KEY=`wilderness510:${W.seedToken}`;
const K={holdings:new Map(),flags:new Map(),news:[],taxClock:0,rebelClock:0,lastSave:0};
const prevNearBounds=W.settlementsNearBounds,prevSettlementDef=W.settlementDef;
function flash510(t,m=2800){if(typeof flash==='function')flash(t,m)}
function faction(id){return N.faction?.(id)||null}
function runtime(id){return typeof generatedSettlements!=='undefined'?generatedSettlements.get(id):null}
function defOf(rt){return rt?.def||rt?.definition||rt?.source||rt}
function addNews(text){K.news.unshift({text,at:Date.now()});if(K.news.length>8)K.news.length=8}
function roleLabel(r){return({infantry:'Infantería',archer:'Arquero',cavalry:'Caballería'})[r]||'Soldado'}
function serialize(){const out={};for(const[id,h]of K.holdings)out[id]={...h};return out}
function save(){try{localStorage.setItem(KEY,JSON.stringify({holdings:serialize(),news:K.news.slice(0,8)}));K.lastSave=Date.now()}catch(e){console.warn('conquest510 save',e)}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d?.holdings)for(const[id,h]of Object.entries(d.holdings))K.holdings.set(id,h);if(Array.isArray(d?.news))K.news=d.news.slice(0,8)}catch(e){console.warn('conquest510 load',e)}}
load();addEventListener('pagehide',save);addEventListener('visibilitychange',()=>{if(document.hidden)save()});
function settlementById(id,h=null){const hc=H.byId?.get?.(id);if(hc)return hc;const rt=runtime(id),d=defOf(rt);if(d?.id===id)return d;if(h&&prevNearBounds){try{const list=prevNearBounds(h.x-8,h.x+8,h.z-8,h.z+8,12)||[];return list.find(s=>s.id===id)||null}catch(_){ }}return null}
function holdingFor(id){return K.holdings.get(id)||null}
function decorateSettlement(s){if(!s?.id)return s;const h=holdingFor(s.id);if(!h)return s;s.originalFaction=h.originalFaction||s.originalFaction||s.faction||s.nation;s.cultureFaction=h.originalFaction||s.cultureFaction||s.originalFaction;s.controllerFaction=h.owner;s.occupiedBy=h.owner;s.faction=h.owner;s.nation=h.owner;s.factionName=faction(h.owner)?.display||h.owner;s.factionKing=faction(h.owner)?.king||s.factionKing;s.captured=h.status==='occupied';s.conquered=h.status==='occupied';return s}
if(prevNearBounds)W.settlementsNearBounds=function(...args){const list=prevNearBounds.apply(W,args)||[];return list.map(decorateSettlement)};
if(prevSettlementDef)W.settlementDef=function(...args){const s=prevSettlementDef.apply(W,args);return s?decorateSettlement(s):s};
function gateList(id){return[...(D55.state?.gates?.values?.()||[])].filter(g=>g.settlementId===id)}
function applyControl(h,s=settlementById(h.id,h)){
 if(!s)return false;decorateSettlement(s);const rt=runtime(h.id);if(rt){rt.originalFaction=h.originalFaction;rt.cultureFaction=h.originalFaction;rt.controllerFaction=h.owner;rt.occupiedBy=h.owner;rt.faction=h.owner;rt.nation=h.owner;rt.factionName=faction(h.owner)?.display||h.owner;rt.factionKing=faction(h.owner)?.king||rt.factionKing;rt.captured=h.status==='occupied';rt.conquered=h.status==='occupied';if(rt.def)decorateSettlement(rt.def)}
 for(const g of gateList(h.id)){g.faction=h.owner;g.controllerFaction=h.owner;if(h.status==='occupied'&&!g.breached)g.targetOpen=1}
 const realm=window.WildernessKingdoms?.realms?.get?.(h.id);if(realm){realm.owner='player';realm.controllerFaction=h.owner;realm.faction=h.owner;realm.king=faction(h.owner)?.king||realm.king;realm.strength=Math.max(realm.strength||0,h.garrison+4)}
 ensureFlag(h,s);return true
}
function clearControl(h,s=settlementById(h.id,h)){
 if(!s)return false;const orig=h.originalFaction;s.faction=orig;s.nation=orig;s.factionName=faction(orig)?.display||orig;s.factionKing=faction(orig)?.king||s.factionKing;s.controllerFaction=orig;s.occupiedBy=null;s.captured=false;s.conquered=false;const rt=runtime(h.id);if(rt){rt.faction=orig;rt.nation=orig;rt.factionName=faction(orig)?.display||orig;rt.factionKing=faction(orig)?.king||rt.factionKing;rt.controllerFaction=orig;rt.occupiedBy=null;rt.captured=false;rt.conquered=false;if(rt.def){rt.def.faction=orig;rt.def.nation=orig;rt.def.factionName=faction(orig)?.display||orig;rt.def.factionKing=faction(orig)?.king||rt.def.factionKing;rt.def.captured=false}}
 for(const g of gateList(h.id)){g.faction=orig;g.controllerFaction=orig}
 const realm=window.WildernessKingdoms?.realms?.get?.(h.id);if(realm){realm.owner='npc';realm.controllerFaction=orig;realm.faction=orig;realm.king=faction(orig)?.king||realm.king}
 removeFlag(h.id);return true
}
function makeFlag(h,s){const f=faction(h.owner),g=new T.Group();g.name=`conquest510-flag-${h.id}`;const y=W.groundY(s.x,s.z);g.position.set(s.x+4,y,s.z-4);const wood=new T.MeshLambertMaterial({color:0x4f3522,flatShading:true}),cloth=new T.MeshLambertMaterial({color:f?.color||0xb28b52,flatShading:true});const pole=new T.Mesh(new T.BoxGeometry(.13,6.2,.13),wood);pole.position.y=3.1;g.add(pole);const flag=new T.Mesh(new T.BoxGeometry(3.1,1.45,.12),cloth);flag.position.set(1.45,5.1,0);g.add(flag);for(const o of g.children){o.castShadow=!mobile;o.userData.conquest510=true}scene.add(g);K.flags.set(h.id,g);return g}
function ensureFlag(h,s=settlementById(h.id,h)){if(!s||h.status!=='occupied')return null;let g=K.flags.get(h.id);if(!g)g=makeFlag(h,s);const f=faction(h.owner),flag=g.children?.[1];if(flag?.material?.color&&f)flag.material.color.setHex(f.color);return g}
function removeFlag(id){const g=K.flags.get(id);if(g){scene.remove(g);K.flags.delete(id)}}
function defaultHolding(s,originalFaction){return{id:s.id,name:s.name||'Ciudad',x:s.x,z:s.z,type:s.type||'city',tier:s.tier||1,population:s.population||60,capital:!!s.capital,originalFaction,owner:N.state.nation,status:'occupied',capturedAt:Date.now(),loyalty:s.capital?54:61,garrison:0,roles:{infantry:0,archer:0,cavalry:0},governor:null,tax:'normal',treasury:0,rebellions:0,lastIncome:Date.now(),lastReaction:0}}
function downgradeRelation(r){return({ally:'friendly',friendly:'neutral',neutral:'hostile',hostile:'war',war:'war',own:'own'})[r]||r}
function diplomaticReaction(original,h){if(!original||original===N.state.nation)return;N.setRelation?.(original,'war');const ties=N.relationsFor?.(original)||{};for(const other of Object.keys(N.factions||{})){if(other===N.state.nation||other===original)continue;const tie=ties[other],cur=N.relationTo?.(other);if(tie==='ally'&&cur&&cur!=='war'&&cur!=='hostile'){const next=downgradeRelation(cur);if(next!==cur){N.setRelation?.(other,next);addNews(`${faction(other)?.display||other} protesta por la conquista de ${h.name}.`)}}else if(tie==='friendly'&&cur==='friendly'){N.setRelation?.(other,'neutral')}}N.setReputation?.((Number(N.state.reputation)||0)+(h.capital?10:4));const ownKing=faction(N.state.nation)?.king,enemyKing=faction(original)?.king;if(ownKing)addNews(`Rey ${ownKing} reconoce la incorporación de ${h.name}.`);if(h.capital&&enemyKing)addNews(`El rey ${enemyKing} ha perdido su capital, ${h.name}.`)}
function capture(s,source='siege'){
 if(!s||!N.state.selected||!N.state.nation)return null;let h=holdingFor(s.id);const original=h?.originalFaction||s.originalFaction||s.cultureFaction||s.faction||s.nation;if(!original||original===N.state.nation&&h?.status==='occupied')return h;
 if(!h)h=defaultHolding(s,original);else{h.owner=N.state.nation;h.status='occupied';h.capturedAt=Date.now();h.loyalty=Math.max(48,h.loyalty||0);h.name=s.name||h.name;h.x=s.x;h.z=s.z;h.population=s.population||h.population;h.capital=!!s.capital;}
 K.holdings.set(s.id,h);applyControl(h,s);if(!N.state.capturedCities.includes(s.id))N.state.capturedCities.push(s.id);diplomaticReaction(original,h);N.save?.();save();flash510(`¡${String(h.name).toUpperCase()} QUEDA BAJO EL DOMINIO DE ${String(faction(h.owner)?.label||h.owner).toUpperCase()}!`,4600);addNews(`${h.name} fue conquistada mediante ${source==='divine'?'intervención divina':'asedio'}.`);return h
}
function aliveFollowers(){return typeof followers==='undefined'?[]:followers.filter(f=>f?.alive&&f.mesh&&!f.__siege57Controlled)}
function takeFollower(){const arr=aliveFollowers().filter(f=>!f.__governor510);arr.sort((a,b)=>(a.role==='infantry'?0:a.role==='archer'?1:2)-(b.role==='infantry'?0:b.role==='archer'?1:2));return arr[0]||null}
function consumeFollower(f,tag){if(!f)return false;f[tag]=true;f.alive=false;scene.remove(f.mesh);return true}
function nearestHolding(max=70){let best=null,bd=max;for(const h of K.holdings.values()){if(h.status!=='occupied')continue;const d=Math.hypot(player.mesh.position.x-h.x,player.mesh.position.z-h.z);if(d<bd){bd=d;best=h}}return best?{h:best,d:bd}:null}
function deposit(n=1){const near=nearestHolding();if(!near)return flash510('Acércate a una ciudad conquistada.');const h=near.h;let count=0;for(let i=0;i<n;i++){const f=takeFollower();if(!f)break;const role=f.role||'infantry';if(!consumeFollower(f,'__garrison510'))break;h.garrison++;h.roles[role]=(h.roles[role]||0)+1;count++}if(!count)return flash510('No tienes soldados disponibles para dejar como guarnición.');h.loyalty=Math.min(100,h.loyalty+count*2.2);applyControl(h);save();flash510(`${count} soldado${count>1?'s':''} queda${count>1?'n':''} en la guarnición de ${h.name}.`)}
function spawnFollower(role,h){if(typeof makeHumanoid!=='function'||typeof followers==='undefined')return false;const a=makeHumanoid({x:player.mesh.position.x+1.8+Math.random()*1.8,z:player.mesh.position.z+1.8+Math.random()*1.8,role});if(!a)return false;a.alive=true;a.recruited=true;a.civilian=false;a.order='follow';a.home=settlementById(h.id,h)||a.home;if(typeof equipRole==='function')try{equipRole(a,role)}catch(_){a.role=role}else a.role=role;if(!followers.includes(a))followers.push(a);if(typeof civilians!=='undefined'){const i=civilians.indexOf(a);if(i>=0)civilians.splice(i,1)}return true}
function withdraw(n=1){const near=nearestHolding();if(!near)return flash510('Acércate a una ciudad conquistada.');const h=near.h;if(h.garrison<=0)return flash510('La ciudad no tiene soldados para retirar.');let count=0;for(let i=0;i<n&&h.garrison>0;i++){let role=['infantry','archer','cavalry'].find(r=>(h.roles[r]||0)>0);if(!role)role='infantry';if(!spawnFollower(role,h)){flash510('No se pudo reincorporar la unidad al ejército activo.');break}h.garrison--;h.roles[role]=Math.max(0,(h.roles[role]||0)-1);count++}if(count){h.loyalty=Math.max(0,h.loyalty-count*1.2);save();flash510(`${count} soldado${count>1?'s':''} vuelve${count>1?'n':''} a tu ejército.`)}}
function appointGovernor(){const near=nearestHolding();if(!near)return flash510('Acércate a una ciudad conquistada.');const h=near.h;if(h.governor)return flash510(`${h.name} ya tiene gobernador.`);const f=takeFollower();if(!f)return flash510('Necesitas un soldado o seguidor disponible para nombrarlo gobernador.');const role=f.role||'infantry',name=f.name||f.rulerName||`Gobernador ${roleLabel(role)}`;consumeFollower(f,'__governor510');h.governor={name,role,appointedAt:Date.now()};h.loyalty=Math.min(100,h.loyalty+8);save();flash510(`${name} ha sido nombrado gobernador de ${h.name}.`,3200);addNews(`${h.name}: ${name} asume el gobierno.`)}
function cycleTax(){const near=nearestHolding();if(!near)return;const h=near.h,list=['low','normal','high'];h.tax=list[(list.indexOf(h.tax)+1)%list.length];save();flash510(`Tributo de ${h.name}: ${h.tax==='low'?'BAJO':h.tax==='high'?'ALTO':'NORMAL'}.`)}
function riskOf(h){const low=Math.max(0,48-h.loyalty)*1.25,guard=h.garrison<4?(4-h.garrison)*8:0,tax=h.tax==='high'?12:h.tax==='low'?-5:0,gov=h.governor?-8:5,capital=h.capital?5:0;return Math.max(0,Math.min(92,Math.round(low+guard+tax+gov+capital)))}
function incomeTick(){let total=0;for(const h of K.holdings.values()){if(h.status!=='occupied')continue;const base=Math.max(1,Math.round((h.population||60)/32))+(h.capital?2:0),mult=h.tax==='low'?.62:h.tax==='high'?1.55:1,gov=h.governor?1.08:1,inc=Math.max(1,Math.round(base*mult*gov));h.treasury+=inc;h.lastIncome=Date.now();total+=inc;let dl=h.tax==='low'?2.0:h.tax==='high'?-2.8:.35;dl+=h.garrison>=5?.8:h.garrison===0?-1.5:0;dl+=h.governor?.8:-.25;h.loyalty=Math.max(0,Math.min(100,h.loyalty+dl));const realm=window.WildernessKingdoms?.realms?.get?.(h.id);if(realm){realm.owner='player';realm.controllerFaction=h.owner;realm.strength=Math.max(4,h.garrison+4);realm.wealth=(realm.wealth||0)+inc*.3}}
 if(total&&typeof L06!=='undefined'&&L06.eco){L06.eco.shekels+=total;flash510(`Tributos de tus dominios · +${total} séqueles.`,2200)}save()}
function spawnRebelDefenders(h,count){const s=settlementById(h.id,h),rt=runtime(h.id);if(!s||typeof makeHumanoid!=='function'||typeof enemies==='undefined')return;for(let i=0;i<count;i++){const role=i%4===3?'archer':'infantry',a=Math.PI*2*i/count,r=7+(i%3)*2,x=s.x+Math.cos(a)*r,z=s.z+Math.sin(a)*r;let e=null;try{e=makeHumanoid({x,z,role})}catch(_){ }if(!e)continue;e.alive=true;e.recruited=false;e.civilian=false;e.home=s;e.role=role;e.hp=e.maxHp||6;if(typeof equipRole==='function')try{equipRole(e,role)}catch(_){ }if(!enemies.includes(e))enemies.push(e);if(rt?.defendersRuntime&&!rt.defendersRuntime.includes(e))rt.defendersRuntime.push(e);if(typeof civilians!=='undefined'){const j=civilians.indexOf(e);if(j>=0)civilians.splice(j,1)}}}
function rebel(h){const s=settlementById(h.id,h);h.status='rebelled';h.owner=h.originalFaction;h.rebellions=(h.rebellions||0)+1;h.loyalty=34;h.garrison=0;h.roles={infantry:0,archer:0,cavalry:0};h.governor=null;clearControl(h,s);N.state.capturedCities=N.state.capturedCities.filter(id=>id!==h.id);N.setRelation?.(h.originalFaction,'war');N.save?.();const st=S57.state?.states?.get?.(h.id);if(st){st.won=false;st.assault=false;st.stage='approach';st.rt=runtime(h.id)||st.rt}spawnRebelDefenders(h,Math.max(5,4+(h.tier||1)*2));save();flash510(`⚠ ${String(h.name).toUpperCase()} SE HA REBELADO y vuelve a reconocer a ${faction(h.originalFaction)?.display||h.originalFaction}.`,4800);addNews(`${h.name} se rebeló por falta de control y guarnición.`)}
function rebellionTick(){for(const h of K.holdings.values()){if(h.status!=='occupied')continue;const risk=riskOf(h)/100;if(risk<.08||Math.random()>risk*.22)continue;const defense=h.garrison*1.85+h.loyalty*.075+(h.governor?2.5:0),attack=5+Math.random()*10+(h.tier||1)*1.6;if(defense>=attack){const loss=h.garrison>0&&Math.random()<.55?1:0;if(loss){h.garrison--;const role=['infantry','archer','cavalry'].find(r=>(h.roles[r]||0)>0);if(role)h.roles[role]--}h.loyalty=Math.min(100,h.loyalty+7);h.rebellions=(h.rebellions||0)+1;flash510(`${h.name} sofoca una revuelta${loss?' con bajas en la guarnición':''}.`,3100);addNews(`${h.name} sofocó una revuelta.`);save()}else rebel(h);break}}
function scanVictories(){if(!N.state.selected)return;for(const st of S57.state?.states?.values?.()||[]){if(st?.won){const s=st.s||settlementById(st.id);if(s&&!holdingFor(st.id))capture(s,'siege')}}for(const id of N.state.capturedCities||[]){if(holdingFor(id))continue;const s=settlementById(id);if(s)capture(s,'siege')}}
function restoreHoldings(){for(const h of K.holdings.values()){if(h.status==='occupied'){h.owner=N.state.nation||h.owner;applyControl(h)}else if(h.status==='rebelled')clearControl(h)}}
const panel=document.createElement('div');panel.id='conquest510';panel.innerHTML='<div id="c510info"></div><div id="c510actions"><button data-g>+1 GUARDIA</button><button data-w>-1 GUARDIA</button><button data-v>GOBERNADOR</button><button data-t>TRIBUTO</button></div>';document.body.appendChild(panel);
const css=document.createElement('style');css.textContent=`#kingdom24,#campaign25{display:none!important}#kingdom-panel{opacity:.28;pointer-events:none}#conquest510{display:none;position:fixed;z-index:93;right:calc(10px + env(safe-area-inset-right,0px));top:calc(82px + env(safe-area-inset-top,0px));width:250px;padding:9px;border:1px solid #d7b46f;border-radius:9px;background:#1b120be8;color:#f7e8c6;font:8px/1.4 ui-monospace,monospace;text-shadow:0 1px 2px #000;pointer-events:auto}#conquest510 b{color:#fff0b6}#c510actions{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin-top:7px}#c510actions button{border:1px solid #bb9560;border-radius:6px;background:#4b311d;color:#fff0cf;padding:6px 4px;font:900 7px ui-monospace,monospace;touch-action:manipulation}#c510actions button:disabled{opacity:.4}@media(pointer:coarse),(max-width:820px){#conquest510{right:calc(7px + env(safe-area-inset-right,0px));top:calc(82px + env(safe-area-inset-top,0px));width:44vw;max-width:190px;padding:6px;font-size:6.3px}#c510actions button{font-size:5.8px;padding:5px 2px}}`;document.head.appendChild(css);
const info=panel.querySelector('#c510info'),btnG=panel.querySelector('[data-g]'),btnW=panel.querySelector('[data-w]'),btnV=panel.querySelector('[data-v]'),btnT=panel.querySelector('[data-t]');
btnG.onpointerdown=e=>{e.preventDefault();deposit(1)};btnW.onpointerdown=e=>{e.preventDefault();withdraw(1)};btnV.onpointerdown=e=>{e.preventDefault();appointGovernor()};btnT.onpointerdown=e=>{e.preventDefault();cycleTax()};
function render(){const n=nearestHolding(68);if(!n){panel.style.display='none';return}const h=n.h,orig=faction(h.originalFaction),own=faction(h.owner),risk=riskOf(h);info.innerHTML=`<b>${String(h.name).toUpperCase()} · TU DOMINIO</b><br>Control: <b>${own?.display||h.owner}</b><br>Origen: ${orig?.display||h.originalFaction}<br>Gobernador: <b>${h.governor?.name||'SIN NOMBRAR'}</b><br>Guarnición: <b>${h.garrison}</b> · Inf ${h.roles.infantry||0} · Arq ${h.roles.archer||0} · Cab ${h.roles.cavalry||0}<br>Lealtad: <b>${Math.round(h.loyalty)}%</b> · Rebelión: <b>${risk}%</b><br>Tributo: <b>${h.tax==='low'?'BAJO':h.tax==='high'?'ALTO':'NORMAL'}</b> · Tesoro: ${h.treasury||0}₪`;btnV.disabled=!!h.governor;btnV.textContent=h.governor?'GOBERNADOR ✓':'GOBERNADOR';btnW.disabled=h.garrison<=0;panel.style.display='block'}
let last=performance.now(),scan=0;function loop(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;K.taxClock+=dt;K.rebelClock+=dt;scan+=dt;try{if(scan>.55){scan=0;scanVictories();restoreHoldings();render()}if(K.taxClock>75){K.taxClock=0;incomeTick()}if(K.rebelClock>42){K.rebelClock=0;rebellionTick()}if(Date.now()-K.lastSave>15000)save()}catch(e){console.warn('Wilderness 5.10 conquest',e)}requestAnimationFrame(loop)}
requestAnimationFrame(loop);
window.WildernessConquest510={state:K,capture,applyControl,rebel,deposit,withdraw,appointGovernor,cycleTax,riskOf,nearestHolding,save};
})();
