// Wilderness 5.6 - CAMPAMENTO / ASEDIO / RITUAL construction system
(()=>{
const T=window.THREE,W=window.WildernessWorld,S8=window.WildernessSettlement,D55=window.WildernessDiplomacy55;if(!T||!W||typeof scene==='undefined'||typeof player==='undefined')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820,KEY=`wilderness56build:${W.seedToken}`;
const B={tab:'camp',placed:[],meshes:new Map(),nextId:1};
const defs={
 tent:{tab:'camp',label:'TIENDA DE CAMPAÑA',cost:{shekels:6,food:1},foot:3.5,desc:'Refugio ligero para el grupo.'},
 fire:{tab:'camp',label:'FOGATA',cost:{shekels:4,food:0},foot:1.4,desc:'Centro sencillo de un campamento.'},
 ladder:{tab:'siege',label:'ESCALERA DE ASALTO',cost:{shekels:12,food:2},foot:2.3,desc:'Preparada para apoyarse contra una muralla en 5.7.'},
 ram:{tab:'siege',label:'ARIETE',cost:{shekels:28,food:4},foot:4.0,desc:'Arma de madera para atacar puertas.'},
 coveredRam:{tab:'siege',label:'ARIETE CUBIERTO',cost:{shekels:42,food:5},foot:4.7,desc:'Ariete protegido contra proyectiles.'},
 siegeTower:{tab:'siege',label:'TORRE DE ASEDIO',cost:{shekels:65,food:8},foot:5.8,desc:'Estructura alta para alcanzar la muralla.'},
 ramp:{tab:'siege',label:'RAMPA DE ASEDIO',cost:{shekels:35,food:6},foot:6.2,desc:'Obra de tierra para aproximarse a la muralla.'},
 altar:{tab:'ritual',label:'ALTAR DE HOLOCAUSTO',cost:{shekels:16,food:0},foot:2.4,desc:'Altar de piedra. Los sacrificios se activarán con FAVOR DE ELOHIM.'}
};
const mat=c=>new T.MeshLambertMaterial({color:c,flatShading:true}),M={wood:mat(0x5a3c27),wood2:mat(0x3c2b20),cloth:mat(0x8b5e45),stone:mat(0x887967),stone2:mat(0x655b50),earth:mat(0x9a7450),dark:mat(0x28211c),ember:new T.MeshBasicMaterial({color:0xd77d32}),rope:mat(0x9b7a53)};
function box(g,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=!mobile;q.receiveShadow=true;q.userData.construction56=true;g.add(q);return q}
function cylinder(g,r,h,m,x,y,z,rotZ=0){const q=new T.Mesh(new T.CylinderGeometry(r,r,h,6),m);q.position.set(x,y,z);q.rotation.z=rotZ;q.castShadow=!mobile;q.receiveShadow=true;q.userData.construction56=true;g.add(q);return q}
function model(kind,rec){const g=new T.Group();g.name=`build56-${kind}-${rec.id}`;g.position.set(rec.x,W.groundY(rec.x,rec.z),rec.z);g.rotation.y=rec.rot||0;g.userData={construction56:true,kind,id:rec.id,siegeId:rec.siegeId||null};
 if(kind==='tent'){const a=box(g,3.6,.18,4.8,M.cloth,-1.0,2.15,0);a.rotation.z=.55;const b=box(g,3.6,.18,4.8,M.cloth,1.0,2.15,0);b.rotation.z=-.55;box(g,.14,3.6,.14,M.wood,0,1.8,0)}
 else if(kind==='fire'){for(let i=0;i<7;i++){const a=i*Math.PI*2/7;box(g,.72,.32,.45,M.stone,Math.cos(a)*1.05,.16,Math.sin(a)*1.05)}const l1=box(g,2.0,.25,.25,M.wood,0,.34,0);l1.rotation.y=.65;const l2=box(g,2.0,.25,.25,M.wood,0,.34,0);l2.rotation.y=-.65;box(g,.55,.55,.55,M.ember,0,.55,0)}
 else if(kind==='ladder'){for(const x of[-.72,.72])box(g,.18,5.8,.18,M.wood,x,2.9,0);for(let y=.45;y<5.6;y+=.62)box(g,1.55,.13,.16,M.wood,0,y,0);g.rotation.x=-.13}
 else if(kind==='ram'||kind==='coveredRam'){for(const x of[-1.65,1.65])for(const z of[-1.55,1.55])cylinder(g,.38,.42,M.wood2,x,.42,z,Math.PI/2);for(const x of[-1.9,1.9])box(g,.26,2.7,3.7,M.wood,x,1.75,0);box(g,4.0,.25,3.9,M.wood,0,3.05,0);const beam=cylinder(g,.38,5.8,M.wood2,0,1.55,0,Math.PI/2);beam.rotation.y=Math.PI/2;box(g,.8,.85,.75,M.dark,0,1.55,-3.05);if(kind==='coveredRam'){const roof=box(g,4.8,.22,5.0,M.cloth,0,3.55,0);roof.rotation.z=.03;for(const x of[-2.1,2.1])box(g,.16,3.0,.16,M.rope,x,2.0,0)}}
 else if(kind==='siegeTower'){box(g,5.0,7.8,5.0,M.wood,0,3.9,0);for(const x of[-2.25,2.25])for(const z of[-2.25,2.25])cylinder(g,.48,.45,M.wood2,x,.48,z,Math.PI/2);for(let y=2;y<7.5;y+=2)box(g,5.3,.20,5.3,M.wood2,0,y,0);box(g,4.3,.20,3.2,M.wood2,0,7.95,-3.5).rotation.x=-.35}
 else if(kind==='ramp'){for(let i=0;i<7;i++){const h=.55+i*.62,z=2.7-i*.9;box(g,6.5,h,1.1,M.earth,0,h/2,z)}}
 else if(kind==='altar'){box(g,3.0,.65,3.0,M.stone2,0,.325,0);box(g,2.45,1.15,2.45,M.stone,0,1.225,0);box(g,2.8,.28,2.8,M.dark,0,1.94,0);for(const x of[-1.15,1.15])for(const z of[-1.15,1.15])box(g,.32,.42,.32,M.stone2,x,2.03,z)}
 scene.add(g);B.meshes.set(rec.id,g);return g}
function save(){try{localStorage.setItem(KEY,JSON.stringify({placed:B.placed,nextId:B.nextId}))}catch(_){}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d?.placed){B.placed=d.placed;B.nextId=Math.max(d.nextId||1,...B.placed.map(x=>Number(x.id)||0).map(x=>x+1));for(const r of B.placed)model(r.kind,r)}}catch(e){console.warn('construction56 load',e)}}
function eco(){return typeof L06!=='undefined'?L06.eco:null}
function canPay(c){const e=eco();return !!e&&e.shekels>=c.shekels&&e.food>=c.food}
function pay(c){const e=eco();e.shekels-=c.shekels;e.food-=c.food}
function activeSiege(){const near=D55?.state?.near,sets=D55?.state?.sieges;if(near?.s&&near.d<170&&sets?.has?.(near.s.id))return near.s;if(window.WildernessSiegeIntent55?.settlement){const s=window.WildernessSiegeIntent55.settlement,d=Math.hypot(player.mesh.position.x-s.x,player.mesh.position.z-s.z);if(d<190)return s}return null}
function placement(kind){const d=defs[kind],yaw=player.mesh.rotation.y,dist=kind==='siegeTower'||kind==='ramp'?8.5:6.5,x=player.mesh.position.x+Math.sin(yaw)*dist,z=player.mesh.position.z+Math.cos(yaw)*dist;return{x,z,rot:yaw+Math.PI,id:B.nextId,kind,foot:d.foot}}
function clearSpot(p){const C=window.WildernessCollision45;if(!C?.staticBlocked)return true;const r=p.foot*.52;for(const ox of[-r,0,r])for(const oz of[-r,0,r]){tmp56.set(p.x+ox,W.groundY(p.x+ox,p.z+oz),p.z+oz);if(C.staticBlocked(tmp56,.42))return false}return true}
const tmp56=new T.Vector3();
function place(kind){const d=defs[kind];if(!d)return false;if(d.tab==='siege'&&!activeSiege()){flash?.('Solo puedes construir máquinas de asedio durante un asedio activo cercano.',2600);return false}if(!canPay(d.cost)){flash?.(`Necesitas ${d.cost.shekels} séqueles y ${d.cost.food} comida.`,2200);return false}const p=placement(kind);if(!clearSpot(p)){flash?.('No hay espacio libre suficiente delante de ti.',2200);return false}const siege=d.tab==='siege'?activeSiege():null;const rec={id:B.nextId++,kind,x:p.x,z:p.z,rot:p.rot,siegeId:siege?.id||null,createdAt:Date.now()};pay(d.cost);B.placed.push(rec);model(kind,rec);save();window.WildernessCollision45?.rebuild?.();render();flash?.(`${d.label} construido.`,1900);return rec}
function settlementButtons(){if(!S8)return'';if(!S8.state?.founded)return'<button class="c56wide" data-found>FUNDAR ASENTAMIENTO<small>20₪ · 5 comida</small></button>';const ds={house:['CASA','10₪ · 2 comida'],corral:['CORRAL','12₪ · 1 comida'],store:['ALMACÉN','18₪ · 2 comida'],tower:['TORRE','24₪ · 3 comida'],wall:['EMPALIZADA','30₪ · 4 comida'],hall:['SALÓN DEL JEFE','45₪ · 7 comida']};return Object.entries(ds).map(([k,v])=>`<button data-old="${k}">${v[0]}<small>${v[1]}</small></button>`).join('')}
const modal=document.createElement('div');modal.id='construction56';modal.innerHTML='<div id="c56card"><div class="c56head"><small>WILDERNESS 5.6</small><h2>CONSTRUIR</h2></div><div id="c56tabs"><button data-tab="camp">CAMPAMENTO</button><button data-tab="siege">ASEDIO</button><button data-tab="ritual">RITUAL</button></div><div id="c56status"></div><div id="c56body"></div><button id="c56close">CERRAR</button></div>';document.body.appendChild(modal);
const css=document.createElement('style');css.textContent=`#build08{display:none!important}#construction56{display:none;position:fixed;z-index:150;inset:0;background:#090604dc;align-items:center;justify-content:center;padding:16px;pointer-events:auto;text-shadow:none}#construction56.open{display:flex}#c56card{width:min(94vw,570px);max-height:88dvh;overflow:auto;background:#24180f;color:#f4e6c4;border:2px solid #d5ad6b;border-radius:13px;padding:15px;font:10px/1.4 ui-monospace,monospace}#c56card h2{margin:2px 0 8px;color:#fff0bb;font-size:19px}#c56card .c56head{text-align:center}#c56card .c56head>small{color:#d4ae6c;font-weight:900;letter-spacing:.15em}#c56tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-bottom:8px}#c56tabs button,#c56body button,#c56close{border:1px solid #b9915d;border-radius:8px;background:#49301d;color:#fff0cf;padding:9px;font:900 9px ui-monospace,monospace;touch-action:manipulation}#c56tabs button.active{background:#7a532e;border-color:#ffe0a0}#c56status{min-height:32px;padding:5px 7px;margin-bottom:7px;background:#171008;border-left:3px solid #a47a48;font-size:8px}#c56body{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}#c56body button{min-height:62px;text-align:left}#c56body button small{display:block;margin-top:4px;opacity:.7;font-size:7px;font-weight:500}#c56body button[disabled]{opacity:.38}.c56wide{grid-column:1/-1}#c56close{display:block;width:100%;margin-top:10px;background:#2d2118}@media(pointer:coarse),(max-width:820px){#construction56{align-items:flex-start;padding-top:calc(48px + env(safe-area-inset-top,0px))}#c56card{max-height:calc(100dvh - 64px);font-size:9px;padding:11px}#c56body button{min-height:55px;padding:8px;font-size:8px}#c56tabs button{font-size:7px;padding:8px 4px}}`;document.head.appendChild(css);
const body=modal.querySelector('#c56body'),status=modal.querySelector('#c56status');
function cardButton(k){const d=defs[k],locked=d.tab==='siege'&&!activeSiege();return`<button data-kind="${k}" ${locked?'disabled':''}>${d.label}<small>${d.cost.shekels}₪ · ${d.cost.food} comida<br>${d.desc}</small></button>`}
function render(){modal.querySelectorAll('#c56tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===B.tab));const e=eco(),siege=activeSiege();status.innerHTML=`Recursos: <b>${e?.shekels??0}₪</b> · Comida: <b>${e?.food??0}</b>${B.tab==='siege'?`<br>${siege?`Asedio activo: <b>${siege.name}</b>`:'<b>No hay un asedio activo cercano.</b>'}`:''}`;if(B.tab==='camp'){body.innerHTML=cardButton('tent')+cardButton('fire')+settlementButtons()}else if(B.tab==='siege'){body.innerHTML=['ladder','ram','coveredRam','siegeTower','ramp'].map(cardButton).join('')}else body.innerHTML=cardButton('altar');body.querySelectorAll('[data-kind]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();place(b.dataset.kind)});body.querySelector('[data-found]')?.addEventListener('pointerdown',e=>{e.preventDefault();S8?.found?.();render()},{passive:false});body.querySelectorAll('[data-old]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();S8?.build?.(b.dataset.old);render()})}
function openMenu(){B.tab=B.tab||'camp';render();modal.classList.add('open');document.exitPointerLock?.()}
function closeMenu(){modal.classList.remove('open')}
modal.querySelectorAll('#c56tabs button').forEach(b=>b.onpointerdown=e=>{e.preventDefault();B.tab=b.dataset.tab;render()});modal.querySelector('#c56close').onpointerdown=e=>{e.preventDefault();closeMenu()};
addEventListener('keydown',e=>{if((e.code==='KeyB'||e.key==='b'||e.key==='B')&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();openMenu()}if(e.key==='Escape'&&modal.classList.contains('open')){e.preventDefault();closeMenu()}},true);
load();
window.WildernessConstruction56={state:B,defs,openMenu,closeMenu,place,activeSiege,save,render};
})();