// Wilderness 5.8 - FAVOR DE ELOHIM: rituals, Temple offerings and divine abilities
(()=>{
const T=window.THREE,W=window.WildernessWorld,N=window.WildernessNations50,J=window.WildernessJerusalem54,C56=window.WildernessConstruction56,S57=window.WildernessSiege57;
if(!T||!W||!N||typeof scene==='undefined'||typeof player==='undefined')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
const KEY=`wilderness58:${W.seedToken}`;
const R={unlocked:false,fortifyUntil:0,fearUntil:0,confuseUntil:0,lastHint:'',lastNearby:null};
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d)Object.assign(R,d)}catch(_){ }if(N.state.nation==='israel'||N.state.nation==='judah')R.unlocked=true}
function save(){try{localStorage.setItem(KEY,JSON.stringify({unlocked:R.unlocked}))}catch(_){ }}
load();addEventListener('pagehide',save);
function favor(){return Math.max(0,Math.min(100,Number(N.state.favor)||0))}
function gain(n){return N.gainFavor?.(n)??favor()}
function spend(n){return !!N.spendFavor?.(n)}
function flash58(t,m=2200){if(typeof flash==='function')flash(t,m)}
function eco(){return typeof L06!=='undefined'?L06.eco:null}
function distXZ(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function playerPos(){return player.mesh.position}
function templeNear(max=9){const a=J?.altar;if(!a)return false;return distXZ(playerPos(),a)<=max}
function altarRecords(){return (C56?.state?.placed||[]).filter(r=>r?.kind==='altar')}
function nearestPlayerAltar(max=9){let best=null,bd=max;for(const r of altarRecords()){const m=C56.state.meshes?.get?.(r.id),p=m?.position||r,d=distXZ(playerPos(),p);if(d<bd){bd=d;best={rec:r,mesh:m,pos:p,d}}}return best}
function nearestOwnedSheep(pos,max=28){if(typeof livestock==='undefined')return null;let best=null,bd=max;for(const a of livestock){if(!a?.alive||!a.owned||a.type!=='sheep'||!a.mesh)continue;const d=distXZ(a.mesh.position,pos);if(d<bd){bd=d;best=a}}return best}
function unlockByTemple(){if(R.unlocked)return true;R.unlocked=true;save();gain(20);flash58('Has consagrado tu camino a Yahvé. FAVOR DE ELOHIM desbloqueado · +20',4200);return true}
function templeOffering(cost,reward){const e=eco();if(!e||e.shekels<cost){flash58(`Necesitas ${cost} séqueles para esta ofrenda.`);return false}e.shekels-=cost;if(!R.unlocked)unlockByTemple();else{gain(reward);flash58(`Ofrenda presentada en el Templo · FAVOR DE ELOHIM +${reward}`,3200)}closeRitual();renderHud();return true}
function holocaust(){if(!R.unlocked){flash58('Primero debes consagrarte a Yahvé mediante una ofrenda en el Templo de Jerusalén.',3800);return false}const a=nearestPlayerAltar(10);if(!a){flash58('Debes estar junto a un altar de holocausto construido por ti.');return false}const sheep=nearestOwnedSheep(a.pos,28);if(!sheep){flash58('Acerca una oveja de tu rebaño al altar antes de ofrecer el holocausto.',3400);return false}sheep.alive=false;scene.remove(sheep.mesh);gain(22);altarFlame(a.pos);flash58('Holocausto presentado · una oveja de tu rebaño ha sido ofrecida · FAVOR DE ELOHIM +22',4200);closeRitual();renderHud();return true}
const flameMat=new T.MeshBasicMaterial({color:0xe4943d,transparent:true,opacity:.9});
function altarFlame(pos){const g=new T.Group();g.name='favor58-altar-flame';g.position.set(pos.x,W.groundY(pos.x,pos.z)+2.1,pos.z);for(let i=0;i<8;i++){const q=new T.Mesh(new T.BoxGeometry(.18+.1*(i%2),.45+.15*(i%3),.18+.1*((i+1)%2)),flameMat.clone());q.position.set((i%3-1)*.24,.15+(i%2)*.2,(Math.floor(i/3)-1)*.18);g.add(q)}scene.add(g);const start=performance.now();function anim(t){const u=(t-start)/2600;if(u>=1){scene.remove(g);return}g.rotation.y+=.06;g.scale.y=.8+Math.sin(t*.012)*.16;g.traverse(o=>{if(o.material?.opacity!=null)o.material.opacity=Math.max(0,.9-u)});requestAnimationFrame(anim)}requestAnimationFrame(anim)}
function activeSiege(){return S57?.state?.active||null}
function enemiesNear(max=45){if(typeof enemies==='undefined')return[];return enemies.filter(e=>e?.alive&&e.mesh&&distXZ(e.mesh.position,playerPos())<max)}
function followersAlive(){return typeof followers==='undefined'?[]:followers.filter(f=>f?.alive&&f.mesh)}
const abilities={
 fortitude:{label:'FORTALEZA',cost:25,desc:'Reduce el daño recibido por ti y tus hombres durante 30 s.',available:()=>true,use(){R.fortifyUntil=performance.now()+30000;flash58('FAVOR DE ELOHIM · FORTALEZA sobre tu compañía.',3000)}},
 fear:{label:'TEMOR',cost:40,desc:'Los enemigos cercanos retroceden durante varios segundos.',available:()=>enemiesNear(36).length>0,use(){const until=performance.now()+10000;R.fearUntil=until;for(const e of enemiesNear(36))e.__favor58FearUntil=until;flash58('FAVOR DE ELOHIM · TEMOR cae sobre tus enemigos.',3000)}},
 restore:{label:'RESTAURACIÓN',cost:60,desc:'Restaura tu vida y sana parcialmente a tus seguidores.',available:()=>player.hp<player.maxHp||followersAlive().some(f=>f.hp<f.maxHp),use(){player.hp=player.maxHp;for(const f of followersAlive())f.hp=Math.min(f.maxHp||5,(f.hp||0)+4);flash58('FAVOR DE ELOHIM · RESTAURACIÓN.',2800)}},
 confusion:{label:'CONFUSIÓN',cost:75,desc:'Desorganiza durante 14 s a los enemigos que te rodean.',available:()=>enemiesNear(48).length>0,use(){const until=performance.now()+14000;R.confuseUntil=until;for(const e of enemiesNear(48)){e.__favor58ConfusedUntil=until;e.cooldown=Math.max(e.cooldown||0,2.5)}flash58('FAVOR DE ELOHIM · CONFUSIÓN sobre el ejército enemigo.',3200)}},
 breach:{label:'DERRIBAR MURALLA',cost:100,desc:'Durante un asedio abre inmediatamente una gran brecha en la fortificación.',available:()=>{const st=activeSiege();return !!(st&&!st.breached&&!st.won)},use(){const st=activeSiege();if(st&&!st.breached)S57.breachGate?.(st,true);flash58('FAVOR DE ELOHIM · LA FORTIFICACIÓN CEDE.',3600)}}
};
function useAbility(id){const a=abilities[id];if(!a)return false;if(!R.unlocked){flash58('FAVOR DE ELOHIM aún no está desbloqueado.');return false}if(!a.available()){flash58('Esta intervención no está disponible en la situación actual.');return false}if(favor()<a.cost){flash58(`Necesitas ${a.cost} de FAVOR DE ELOHIM.`);return false}if(!spend(a.cost))return false;a.use();closeAbilities();renderHud();return true}
// Incoming damage protection while Fortaleza is active. Loaded after siege57 so it wraps the final combat chain.
const oldDamage58=typeof damage==='function'?damage:null;if(oldDamage58){damage=function(e,amount){if(performance.now()<R.fortifyUntil&&(e===player||followersAlive().includes(e)))amount*=.55;return oldDamage58(e,amount)}}
function updateAffected(dt,now){if(typeof enemies==='undefined')return;for(const e of enemies){if(!e?.alive||!e.mesh)continue;if((e.__favor58FearUntil||0)>now){const dx=e.mesh.position.x-player.mesh.position.x,dz=e.mesh.position.z-player.mesh.position.z,d=Math.hypot(dx,dz)||1;e.mesh.position.x+=dx/d*4.6*dt;e.mesh.position.z+=dz/d*4.6*dt;e.mesh.position.y=W.groundY(e.mesh.position.x,e.mesh.position.z);e.mesh.rotation.y=Math.atan2(dx,dz);continue}if((e.__favor58ConfusedUntil||0)>now){e.cooldown=Math.max(e.cooldown||0,.5);if(Math.random()<dt*2.2){const a=Math.random()*Math.PI*2;e.mesh.position.x+=Math.sin(a)*.55;e.mesh.position.z+=Math.cos(a)*.55;e.mesh.position.y=W.groundY(e.mesh.position.x,e.mesh.position.z);e.mesh.rotation.y=a}}}}
const hud=document.createElement('button');hud.id='favor58hud';hud.setAttribute('aria-label','FAVOR DE ELOHIM');hud.innerHTML='<span>FAVOR DE ELOHIM</span><i><b></b></i><em></em>';document.body.appendChild(hud);
const style=document.createElement('style');style.textContent=`#favor58hud{position:fixed;z-index:84;left:calc(12px + env(safe-area-inset-left,0px));top:calc(142px + env(safe-area-inset-top,0px));width:190px;padding:7px 8px;border:1px solid #dfc27caa;border-radius:8px;background:#171108db;color:#fff0c4;text-align:left;pointer-events:auto;touch-action:manipulation;font:900 8px ui-monospace,monospace;text-shadow:0 1px 2px #000}#favor58hud>span{display:block;letter-spacing:.08em;margin-bottom:4px}#favor58hud i{display:block;height:7px;border:1px solid #9f834e;background:#0d0a07;overflow:hidden}#favor58hud i b{display:block;width:0;height:100%;background:linear-gradient(90deg,#8d7130,#f0dc83);transition:width .25s}#favor58hud em{display:block;font-style:normal;font-size:7px;opacity:.8;margin-top:3px}#favor58modal,#favor58ritual{display:none;position:fixed;z-index:170;inset:0;background:#080604dd;align-items:center;justify-content:center;padding:16px;pointer-events:auto;text-shadow:none}#favor58modal.open,#favor58ritual.open{display:flex}.f58card{width:min(94vw,520px);max-height:88dvh;overflow:auto;border:2px solid #d9bd79;border-radius:12px;background:#24180f;color:#f5e5c2;padding:15px;font:10px/1.4 ui-monospace,monospace}.f58card h2{margin:0 0 7px;color:#fff1bd}.f58grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.f58card button{border:1px solid #b9975e;border-radius:8px;background:#51341f;color:#fff0cf;padding:9px;font:900 8px ui-monospace,monospace;touch-action:manipulation}.f58card button small{display:block;font-size:7px;opacity:.72;margin-top:4px;font-weight:500}.f58card button[disabled]{opacity:.34}.f58close{width:100%;margin-top:9px;background:#30231a!important}#favor58hint{display:none;position:fixed;z-index:97;left:50%;bottom:112px;transform:translateX(-50%);padding:6px 9px;border:1px solid #d7b97888;border-radius:8px;background:#171108df;color:#ffe9b5;font:800 7px ui-monospace,monospace;pointer-events:none}@media(pointer:coarse),(max-width:820px){#favor58hud{top:calc(116px + env(safe-area-inset-top,0px));left:calc(8px + env(safe-area-inset-left,0px));width:150px;font-size:6.5px;padding:5px 6px}#favor58hud em{font-size:6px}.f58card{font-size:9px;padding:11px}.f58grid{grid-template-columns:1fr}#favor58hint{bottom:calc(200px + env(safe-area-inset-bottom,0px));font-size:6px}}`;document.head.appendChild(style);
const abilityModal=document.createElement('div');abilityModal.id='favor58modal';abilityModal.innerHTML='<div class="f58card"><h2>FAVOR DE ELOHIM</h2><p id="f58abilitystatus"></p><div id="f58abilities" class="f58grid"></div><button class="f58close">CERRAR</button></div>';document.body.appendChild(abilityModal);
const ritualModal=document.createElement('div');ritualModal.id='favor58ritual';ritualModal.innerHTML='<div class="f58card"><h2 id="f58ritualtitle">RITUAL</h2><div id="f58ritualbody"></div><button class="f58close">CERRAR</button></div>';document.body.appendChild(ritualModal);
const hint=document.createElement('div');hint.id='favor58hint';document.body.appendChild(hint);
function renderHud(){const v=favor();hud.querySelector('i b').style.width=`${v}%`;hud.querySelector('em').textContent=R.unlocked?`${Math.round(v)}/100 · TOCA PARA INVOCAR`:'NO DESBLOQUEADO · VE AL TEMPLO'}
function openAbilities(){const box=abilityModal.querySelector('#f58abilities'),status=abilityModal.querySelector('#f58abilitystatus');status.innerHTML=R.unlocked?`Favor disponible: <b>${Math.round(favor())}/100</b>`:'Debes presentar primero una ofrenda en el Templo de Jerusalén para consagrar tu camino a Yahvé.';box.innerHTML=Object.entries(abilities).map(([id,a])=>`<button data-a="${id}" ${(!R.unlocked||favor()<a.cost||!a.available())?'disabled':''}>${a.label} · ${a.cost}<small>${a.desc}</small></button>`).join('');box.querySelectorAll('[data-a]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();useAbility(b.dataset.a)});abilityModal.classList.add('open')}
function closeAbilities(){abilityModal.classList.remove('open')}
function openTemple(){const body=ritualModal.querySelector('#f58ritualbody');ritualModal.querySelector('#f58ritualtitle').textContent='TEMPLO DE JERUSALÉN';if(!R.unlocked)body.innerHTML='<p>Presenta una ofrenda y consagra tu camino a Yahvé. Esto desbloqueará FAVOR DE ELOHIM.</p><button data-offer="10,20">PRESENTAR OFRENDA · 10₪<small>Desbloquea FAVOR DE ELOHIM y concede +20.</small></button>';else body.innerHTML='<p>Presenta una ofrenda en el Templo.</p><div class="f58grid"><button data-offer="8,15">OFRENDA · 8₪<small>+15 FAVOR</small></button><button data-offer="20,30">OFRENDA MAYOR · 20₪<small>+30 FAVOR</small></button></div>';body.querySelectorAll('[data-offer]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();const[c,r]=b.dataset.offer.split(',').map(Number);templeOffering(c,r)});ritualModal.classList.add('open')}
function openHolocaust(){const a=nearestPlayerAltar(10),sheep=a&&nearestOwnedSheep(a.pos,28),body=ritualModal.querySelector('#f58ritualbody');ritualModal.querySelector('#f58ritualtitle').textContent='ALTAR DE HOLOCAUSTO';body.innerHTML=`<p>${R.unlocked?'Ofrece una oveja de tu propio rebaño.':'Debes consagrarte primero en el Templo de Jerusalén.'}</p><p>Oveja propia cercana: <b>${sheep?'SÍ':'NO'}</b></p><button id="f58burn" ${(!R.unlocked||!sheep)?'disabled':''}>OFRECER HOLOCAUSTO<small>Consume 1 oveja · +22 FAVOR</small></button>`;body.querySelector('#f58burn')?.addEventListener('pointerdown',e=>{e.preventDefault();holocaust()});ritualModal.classList.add('open')}
function closeRitual(){ritualModal.classList.remove('open')}
hud.onpointerdown=e=>{e.preventDefault();openAbilities()};abilityModal.querySelector('.f58close').onpointerdown=e=>{e.preventDefault();closeAbilities()};ritualModal.querySelector('.f58close').onpointerdown=e=>{e.preventDefault();closeRitual()};
const oldInteract58=typeof interact==='function'?interact:null;if(oldInteract58){interact=function(){if(templeNear(9)){openTemple();return}if(nearestPlayerAltar(9)){openHolocaust();return}return oldInteract58()}}
function updateHint(){if(templeNear(10)){R.lastNearby='temple';hint.textContent='ACCIÓN / △ · OFRENDA EN EL TEMPLO';hint.style.display='block';return}if(nearestPlayerAltar(10)){R.lastNearby='altar';hint.textContent='ACCIÓN / △ · ALTAR DE HOLOCAUSTO';hint.style.display='block';return}R.lastNearby=null;hint.style.display='none'}
let last=performance.now(),ui=0;function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;updateAffected(dt,now);ui+=dt;if(ui>.18){ui=0;renderHud();updateHint()}requestAnimationFrame(loop)}renderHud();requestAnimationFrame(loop);
window.WildernessFavor58={state:R,abilities,useAbility,holocaust,templeOffering,openAbilities,openTemple,openHolocaust,favor,unlock:unlockByTemple};
})();