(() => {
  const W=window.WildernessWorld;
  if(!W||typeof player==='undefined')return;
  const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
  const key=`wilderness10:${W.seedToken}`;
  const R={savedAt:0,conquered:[],diplomacy:{},autosaveClock:0,ready:false};
  let modal,card,btn;
  function safe(v,d){return Number.isFinite(v)?v:d}
  function collect(){
    const conquered=[];
    if(typeof cities!=='undefined')for(const c of cities)if(c?.captured)conquered.push(c.id||c.name||`${c.x},${c.z}`);
    const diplomacy={};
    const K=window.WildernessKingdoms;
    if(K?.realms)for(const [id,r] of K.realms)if(id!=='player-settlement')diplomacy[id]={owner:r.owner,strength:r.strength,wealth:r.wealth,cities:r.cities};
    return {version:'1.0',seed:W.seedToken,savedAt:Date.now(),player:{x:player.mesh.position.x,z:player.mesh.position.z,hp:player.hp},economy:typeof L06!=='undefined'?{...L06.eco}:null,conquered,diplomacy};
  }
  function save(manual=false){try{const d=collect();localStorage.setItem(key,JSON.stringify(d));R.savedAt=d.savedAt;R.conquered=d.conquered;R.diplomacy=d.diplomacy;if(manual&&typeof flash==='function')flash('Partida guardada.',1800);render()}catch(e){console.warn('save10',e);if(manual&&typeof flash==='function')flash('No se pudo guardar la partida.',2200)}}
  function loadRaw(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(_){return null}}
  function apply(){const d=loadRaw();if(!d)return false;try{if(d.player){player.mesh.position.x=safe(d.player.x,player.mesh.position.x);player.mesh.position.z=safe(d.player.z,player.mesh.position.z);player.mesh.position.y=W.groundY(player.mesh.position.x,player.mesh.position.z);player.hp=Math.max(1,Math.min(player.maxHp||100,safe(d.player.hp,player.hp)))}if(d.economy&&typeof L06!=='undefined')Object.assign(L06.eco,d.economy);R.savedAt=d.savedAt||0;R.conquered=d.conquered||[];R.diplomacy=d.diplomacy||{};restoreConquests();restoreDiplomacy();return true}catch(e){console.warn('load10',e);return false}}
  function cityKey(c){return c?.id||c?.name||`${c?.x},${c?.z}`}
  function restoreConquests(){if(typeof cities==='undefined'||!R.conquered.length)return;for(const c of cities){if(R.conquered.includes(cityKey(c))){c.captured=true;if(c.defendersRuntime)for(const e of c.defendersRuntime){if(e.alive){e.alive=false;scene.remove(e.mesh)}}if(c.kingRuntime?.alive){c.kingRuntime.alive=false;scene.remove(c.kingRuntime.mesh)}}}}
  function restoreDiplomacy(){const K=window.WildernessKingdoms;if(!K?.realms)return;for(const[id,d]of Object.entries(R.diplomacy)){const r=K.realms.get(id);if(r)Object.assign(r,d)}}
  function nearestRealm(){const K=window.WildernessKingdoms;if(!K?.realms)return null;let best=null,bd=Infinity;for(const r of K.realms.values()){if(r.owner==='player')continue;const d=Math.hypot(r.x-player.mesh.position.x,r.z-player.mesh.position.z);if(d<bd){best=r;bd=d}}return best?{r:best,d:bd}:null}
  function relationLabel(r){const d=R.diplomacy[r.id];if(d?.relation==='ally')return 'ALIADO';if(d?.relation==='enemy')return 'ENEMIGO';return 'NEUTRAL'}
  function diplomacy(action){const n=nearestRealm();if(!n||n.d>125){flash('Acércate a una ciudad para negociar.',2200);return}const r=n.r;R.diplomacy[r.id]=R.diplomacy[r.id]||{};const d=R.diplomacy[r.id];if(action==='gift'){if(typeof L06==='undefined'||L06.eco.shekels<12){flash('Necesitas 12 séqueles para enviar un presente.',2200);return}L06.eco.shekels-=12;d.relation='ally';r.aggression=Math.max(.08,(r.aggression||.4)-.18);flash(`${r.name} acepta tu presente. Relación: aliada.`,2800)}else if(action==='threat'){d.relation='enemy';r.aggression=Math.min(.95,(r.aggression||.4)+.25);flash(`${r.name} considera tu amenaza un acto hostil.`,2800)}save();render()}
  function render(){if(!card)return;const d=loadRaw(),n=nearestRealm();const when=d?.savedAt?new Date(d.savedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Nunca';const city=n&&n.d<150?`<p>Ciudad cercana: <b>${n.r.name}</b> · ${Math.round(n.d)}m · ${relationLabel(n.r)}</p><div class="a10"><button data-gift>PRESENTE 12₪</button><button data-threat>AMENAZAR</button></div>`:'<p>Acércate a una ciudad para usar diplomacia.</p>';card.innerHTML=`<h2>WILDERNESS 1.0</h2><p>Semilla <b>${W.seedToken}</b> · Último guardado: <b>${when}</b></p><p>Ciudades conquistadas registradas: <b>${R.conquered.length}</b></p>${city}<div class="a10"><button data-save>GUARDAR AHORA</button><button data-close>CERRAR</button></div>`;card.querySelector('[data-save]').onclick=()=>save(true);card.querySelector('[data-close]').onclick=close;card.querySelector('[data-gift]')?.addEventListener('click',()=>diplomacy('gift'));card.querySelector('[data-threat]')?.addEventListener('click',()=>diplomacy('threat'))}
  function open(){render();modal.style.display='flex'}function close(){modal.style.display='none'}
  function ui(){btn=document.createElement('button');btn.textContent='REINO';btn.style.cssText='position:fixed;z-index:38;right:12px;top:188px;border:1px solid #d8b97aaa;border-radius:7px;padding:7px 9px;background:#392617df;color:#fff0cf;font:9px ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:900';btn.onclick=open;document.body.appendChild(btn);modal=document.createElement('div');modal.style.cssText='display:none;position:fixed;z-index:99;inset:0;background:#090604e8;align-items:center;justify-content:center;padding:16px;pointer-events:auto';modal.innerHTML='<div id="rel10card" style="width:min(94vw,540px);max-height:88vh;overflow:auto;background:#25190f;color:#f4e6c4;border:2px solid #d5ad6b;border-radius:12px;padding:16px;text-shadow:none;font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace"></div>';document.body.appendChild(modal);card=modal.firstChild;const st=document.createElement('style');st.textContent='#rel10card h2{color:#fff0b8}#rel10card .a10{display:flex;gap:7px;flex-wrap:wrap}#rel10card button{flex:1;border:1px solid #d1a96b;border-radius:7px;background:#53371f;color:#fff0cf;padding:10px;font-weight:800}';document.head.appendChild(st);if(mobile){btn.style.right='8px';btn.style.top='144px';btn.style.fontSize='7px';btn.style.padding='5px 6px'}}
  addEventListener('keydown',e=>{if((e.key==='m'||e.key==='M')&&!e.repeat)open();if(e.key==='Escape'&&modal?.style.display==='flex')close()});
  function tick(dt){R.autosaveClock+=dt;if(R.autosaveClock>45){R.autosaveClock=0;save(false)}restoreConquests();restoreDiplomacy()}
  ui();setTimeout(()=>{const had=apply();R.ready=true;if(had)flash('Partida 1.0 restaurada.',2200);else save(false)},900);let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;try{tick(dt)}catch(e){console.warn('Wilderness 1.0:',e)}requestAnimationFrame(loop)}requestAnimationFrame(loop);addEventListener('pagehide',()=>save(false));addEventListener('visibilitychange',()=>{if(document.hidden)save(false)});window.WildernessRelease={state:R,save,open};
})();