// Wilderness 4.8 - river water ribbons, green banks, road bridges and river-settlement details
(()=>{
const T=window.THREE,W=window.WildernessWorld;if(!T||!W||typeof scene==='undefined'||typeof chunks==='undefined'||typeof player==='undefined'||typeof W.riverSegmentsNearBounds!=='function')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
const R={groups:new Map(),settlements:new Set(),bridges:[]};
const water=new T.MeshLambertMaterial({color:0x4a8792,transparent:true,opacity:.78,side:T.DoubleSide,depthWrite:false}),wood=new T.MeshLambertMaterial({color:0x5b3a25,flatShading:true}),stone=new T.MeshLambertMaterial({color:0x817365,flatShading:true}),green=new T.MeshLambertMaterial({color:0x5f7e43,flatShading:true}),green2=new T.MeshLambertMaterial({color:0x78934f,flatShading:true}),reed=new T.MeshLambertMaterial({color:0x86985b,flatShading:true});
function box(g,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=!mobile;q.receiveShadow=true;g.add(q);return q}
function tree(g,x,z,s=1,dry=false){const y=W.groundY(x,z);box(g,.36*s,3.7*s,.36*s,wood,x,y+1.85*s,z);box(g,2.5*s,.82*s,2.25*s,dry?green:green2,x,y+3.85*s,z);box(g,1.8*s,.65*s,1.7*s,green,x+.22*s,y+4.35*s,z-.1*s)}
function reeds(g,x,z,rot=0,s=1){const y=W.groundY(x,z);for(let i=-2;i<=2;i++){const q=box(g,.08,.8*s,.08,i%2?reed:green2,x+Math.cos(rot)*i*.18*s,y+.4*s,z+Math.sin(rot)*i*.18*s);q.rotation.z=(i-1)*.05}}
function riverMesh(g,s){const dx=s.bx-s.ax,dz=s.bz-s.az,len=Math.hypot(dx,dz),ang=Math.atan2(dx,dz),midX=(s.ax+s.bx)/2,midZ=(s.az+s.bz)/2,midY=(s.ay+s.by)/2+.035,q=box(g,s.width*2,.065,len+1.2,water,midX,midY,midZ);q.rotation.y=ang;q.renderOrder=4;q.receiveShadow=false;return q}
function bridge(g,s,t){const x=s.ax+(s.bx-s.ax)*t,z=s.az+(s.bz-s.az)*t,y=Math.max(W.groundY(x,z),s.ay+(s.by-s.ay)*t+.58),riverAng=Math.atan2(s.bx-s.ax,s.bz-s.az),span=s.width*2+4.8,r=new T.Group();r.position.set(x,y,z);r.rotation.y=riverAng+Math.PI/2;g.add(r);box(r,4.4,.28,span,wood,0,0,0);for(const side of[-1,1]){box(r,.16,.95,span,wood,side*2.02,.48,0);for(let zz=-span/2;zz<=span/2;zz+=2.1)box(r,.16,1.05,.16,wood,side*2.02,.45,zz)}for(const zz of[-span/2,span/2])box(r,4.8,.55,.8,stone,0,-.12,zz);R.bridges.push({x,z});return r}
function nearBridge(x,z,d=17){return R.bridges.some(b=>(b.x-x)**2+(b.z-z)**2<d*d)}
function buildChunk(cx,cz){const key=`${cx},${cz}`;if(R.groups.has(key))return;const g=new T.Group();g.name='rivers48-'+key;scene.add(g);R.groups.set(key,g);const minX=cx*W.CHUNK_SIZE,maxX=minX+W.CHUNK_SIZE,minZ=cz*W.CHUNK_SIZE,maxZ=minZ+W.CHUNK_SIZE,segs=W.riverSegmentsNearBounds(minX,maxX,minZ,maxZ,12);for(const s of segs){const mx=(s.ax+s.bx)/2,mz=(s.az+s.bz)/2;if(mx<minX||mx>=maxX||mz<minZ||mz>=maxZ)continue;riverMesh(g,s);const ang=Math.atan2(s.bx-s.ax,s.bz-s.az);if((s.i+(s.id%3))%3===0){for(const side of[-1,1]){const off=s.width*2.15+1.5,x=mx+Math.cos(ang)*off*side,z=mz-Math.sin(ang)*off*side;if(W.waterAt?.(x,z)||W.roadAt?.(x,z))continue;const dry=(W.climateAt?.(x,z)?.moisture??.5)<.43;if((s.id+side+7)%3===0)tree(g,x,z,.72+(s.id%4)*.08,dry);else reeds(g,x,z,ang,.8)}}for(const t of[.25,.5,.75]){const x=s.ax+(s.bx-s.ax)*t,z=s.az+(s.bz-s.az)*t;if(W.roadAt?.(x,z)&&!nearBridge(x,z)){bridge(g,s,t);break}}}}
function settlementDetails(){if(typeof generatedSettlements==='undefined')return;for(const s of generatedSettlements.values()){const d=s?.def||s?.definition||s?.source||s;if(!d?.id||R.settlements.has(d.id))continue;const q=W.riverInfoAt?.(d.x,d.z,48);if(!q||q.d>Math.min(46,q.bank+25)){R.settlements.add(d.id);continue}R.settlements.add(d.id);s.river48=true;const g=new T.Group();g.name='river-settlement48-'+d.id;scene.add(g);const dx=q.x-d.x,dz=q.z-d.z,L=Math.hypot(dx,dz)||1,nx=dx/L,nz=dz/L,px=-nz,pz=nx,baseX=d.x+nx*Math.min(22,Math.max(13,q.d*.55)),baseZ=d.z+nz*Math.min(22,Math.max(13,q.d*.55));for(let row=-2;row<=2;row++){const x=baseX+px*row*2.0,z=baseZ+pz*row*2.0,y=W.groundY(x,z),qf=box(g,1.15,.10,8.5,row%2?green:green2,x,y+.05,z);qf.rotation.y=Math.atan2(nx,nz)}for(let i=-2;i<=2;i++){const x=baseX+px*i*3.2-nx*5,z=baseZ+pz*i*3.2-nz*5;if(!W.riverAt?.(x,z))tree(g,x,z,.68+(i%2)*.08,false)}}}
function sync(){for(const key of chunks.keys()){const[cx,cz]=key.split(',').map(Number);buildChunk(cx,cz)}for(const[key,g]of[...R.groups])if(!chunks.has(key)){scene.remove(g);g.traverse(o=>o.geometry?.dispose?.());R.groups.delete(key)}settlementDetails()}
let last=0;function loop(t){if(t-last>450){last=t;sync()}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessRiversVisual48=R;
})();