(() => {
  const THREE=window.THREE, W=window.WildernessWorld;
  if(!THREE||!W||typeof scene==='undefined'||typeof player==='undefined')return;
  const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
  const key=`wilderness08:${W.seedToken}`;
  const S={founded:false,name:'Mi Asentamiento',x:0,z:0,level:0,population:0,capacity:6,defense:0,foodRate:0,storage:0,buildings:[],mesh:null,realm:null};
  const defs={
    house:{label:'CASA',cost:{shekels:10,food:2},pop:3,capacity:5,defense:0},
    corral:{label:'CORRAL',cost:{shekels:12,food:1},pop:1,capacity:0,defense:1},
    store:{label:'ALMACÉN',cost:{shekels:18,food:2},pop:1,capacity:2,defense:0},
    tower:{label:'TORRE',cost:{shekels:24,food:3},pop:1,capacity:1,defense:5},
    wall:{label:'EMPALIZADA',cost:{shekels:30,food:4},pop:0,capacity:0,defense:10},
    hall:{label:'SALÓN DEL JEFE',cost:{shekels:45,food:7},pop:4,capacity:8,defense:4}
  };
  function save(){try{localStorage.setItem(key,JSON.stringify({founded:S.founded,name:S.name,x:S.x,z:S.z,level:S.level,population:S.population,capacity:S.capacity,defense:S.defense,foodRate:S.foodRate,storage:S.storage,buildings:S.buildings}))}catch(_){}}
  function load(){try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d&&d.founded)Object.assign(S,d)}catch(_){}}
  function mat(c){return new THREE.MeshLambertMaterial({color:c,flatShading:true})}
  const adobe=mat(0xb77d4d),adobe2=mat(0x8c5d3d),wood=mat(0x5b3823),roof=mat(0x705039),stone=mat(0x756553),cloth=mat(0x9e6842),gold=mat(0xb58b35);
  function box(p,w,h,d,m,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=!mobile;o.receiveShadow=true;p.add(o);return o}
  function localY(x,z){return W.groundY(S.x+x,S.z+z)-W.groundY(S.x,S.z)}
  function houseMesh(p,x,z,i=0){const y=localY(x,z);box(p,5.4,3.1,4.5,i%2?adobe2:adobe,x,y+1.55,z);box(p,5.8,.45,4.9,roof,x,y+3.25,z);box(p,1.1,2.05,.25,wood,x,y+1.05,z+2.3);}
  function corralMesh(p,x,z){const y=localY(x,z),s=6;for(const dx of[-s,s])for(let q=-s;q<=s;q+=2)box(p,.16,1.25,.16,wood,x+dx,y+.62,z+q);for(const dz of[-s,s])for(let q=-s;q<=s;q+=2)box(p,.16,1.25,.16,wood,x+q,y+.62,z+dz);}
  function storeMesh(p,x,z){const y=localY(x,z);box(p,6.5,3.6,5.4,adobe2,x,y+1.8,z);box(p,7,.5,5.9,roof,x,y+3.8,z);for(let i=-1;i<=1;i++)box(p,1.2,1.2,1.2,wood,x+i*1.6,y+.6,z+3.2);}
  function towerMesh(p,x,z){const y=localY(x,z);box(p,3.4,6.5,3.4,stone,x,y+3.25,z);box(p,4,.4,4,wood,x,y+6.7,z);for(const dx of[-1.6,1.6])for(const dz of[-1.6,1.6])box(p,.35,1,.35,wood,x+dx,y+7.2,z+dz);}
  function wallMesh(p){const r=22,y0=0;for(let a=0;a<Math.PI*2;a+=Math.PI/12){const x=Math.cos(a)*r,z=Math.sin(a)*r,y=localY(x,z);const post=box(p,.55,3.4,.55,wood,x,y+1.7,z);post.rotation.y=-a;}for(let a=0;a<Math.PI*2;a+=Math.PI/6){if(Math.abs(Math.sin(a))<.15&&Math.cos(a)>0)continue;const a2=a+Math.PI/6,x=(Math.cos(a)+Math.cos(a2))*r/2,z=(Math.sin(a)+Math.sin(a2))*r/2,y=localY(x,z),len=2*r*Math.sin(Math.PI/12);const rail=box(p,len,.4,.35,wood,x,y+1.5,z);rail.rotation.y=-a-Math.PI/12;}}
  function hallMesh(p,x,z){const y=localY(x,z);box(p,9,4.4,7,adobe,x,y+2.2,z);box(p,9.6,.6,7.6,roof,x,y+4.65,z);for(const dx of[-3,-1.5,1.5,3])box(p,.45,3.1,.45,stone,x+dx,y+1.55,z+3.8);const flag=box(p,2.1,.8,.12,gold,x+1,y+8,z);box(p,.14,7,.14,wood,x,y+5,z);flag.position.z=z;}
  function banner(p){box(p,.14,6,.14,wood,0,3,0);const f=box(p,2.4,1.1,.12,gold,1.2,5.1,0);f.rotation.y=.05;}
  function rebuild(){if(S.mesh)scene.remove(S.mesh);if(!S.founded)return;const g=new THREE.Group();g.position.set(S.x,W.groundY(S.x,S.z),S.z);banner(g);let hi=0,ci=0,si=0,ti=0,hai=0;for(const b of S.buildings){if(b==='house'){const slots=[[-9,-8],[8,-9],[-11,6],[10,7],[-3,13],[4,-14]];const q=slots[hi++%slots.length];houseMesh(g,q[0],q[1],hi)}else if(b==='corral'){const slots=[[14,-1],[-15,-2]];const q=slots[ci++%2];corralMesh(g,q[0],q[1])}else if(b==='store'){const slots=[[-5,-12],[6,12]];const q=slots[si++%2];storeMesh(g,q[0],q[1])}else if(b==='tower'){const slots=[[-18,-18],[18,-18],[-18,18],[18,18]];const q=slots[ti++%4];towerMesh(g,q[0],q[1])}else if(b==='wall')wallMesh(g);else if(b==='hall'){hallMesh(g,0,6+hai*10);hai++;}}
    scene.add(g);S.mesh=g;syncRealm();
  }
  function nearbySettlement(){if(typeof generatedSettlements==='undefined')return false;for(const s of generatedSettlements.values()){const d=s?.def||s?.definition||s;if(d&&Math.hypot(d.x-player.mesh.position.x,d.z-player.mesh.position.z)<55)return true}return false}
  function found(){if(S.founded){openMenu();return}if(typeof L06==='undefined'){flash('Aún no está disponible la economía.',2200);return}if(nearbySettlement()){flash('Estás demasiado cerca de otro asentamiento.',2500);return}if(L06.eco.shekels<20||L06.eco.food<5){flash('Fundar requiere 20 séqueles y 5 de comida.',2600);return}L06.eco.shekels-=20;L06.eco.food-=5;S.founded=true;S.x=Math.round(player.mesh.position.x/2)*2;S.z=Math.round(player.mesh.position.z/2)*2;S.level=1;S.population=6;S.capacity=8;S.defense=2;S.buildings=[];save();rebuild();flash('Has fundado un asentamiento. Ahora puedes construir.',4000);openMenu()}
  function canPay(c){return L06&&L06.eco.shekels>=c.shekels&&L06.eco.food>=c.food}
  function build(kind){const d=defs[kind];if(!d||!S.founded)return;if(kind==='wall'&&S.buildings.includes('wall')){flash('Ya tienes una empalizada.',1800);return}if(kind==='hall'&&S.buildings.includes('hall')){flash('Ya tienes un salón del jefe.',1800);return}if(!canPay(d.cost)){flash(`Necesitas ${d.cost.shekels} séqueles y ${d.cost.food} comida.`,2200);return}L06.eco.shekels-=d.cost.shekels;L06.eco.food-=d.cost.food;S.buildings.push(kind);S.population=Math.min(S.capacity+d.capacity,S.population+d.pop);S.capacity+=d.capacity;S.defense+=d.defense;if(kind==='store')S.storage+=20;if(kind==='corral')S.foodRate+=.04;if(kind==='hall')S.level=Math.max(S.level,2);if(kind==='wall')S.level=Math.max(S.level,2);save();rebuild();renderMenu();flash(`${d.label} construido.`,1800)}
  function syncRealm(){if(!S.founded||!window.WildernessKingdoms)return;const K=window.WildernessKingdoms;if(!S.realm){S.realm={id:'player-settlement',name:S.name,king:'Tú',x:S.x,z:S.z,color:0xb58b35,strength:Math.max(5,S.defense),wealth:L06?.eco?.shekels||0,aggression:.2,owner:'player',cities:1,lastCampaign:0,source:{id:'player-settlement',type:'city',x:S.x,z:S.z,name:S.name,king:'Tú'}};K.realms.set(S.realm.id,S.realm)}S.realm.x=S.x;S.realm.z=S.z;S.realm.strength=Math.max(5,S.defense+Math.floor(S.population*.4));S.realm.wealth=L06?.eco?.shekels||0;}
  const modal=document.createElement('div');modal.id='build08';modal.style.cssText='display:none;position:fixed;z-index:90;inset:0;background:#090604d9;align-items:center;justify-content:center;padding:18px;pointer-events:auto';modal.innerHTML='<div id="build08card" style="width:min(94vw,520px);max-height:86vh;overflow:auto;background:#25190f;color:#f4e6c4;border:2px solid #d5ad6b;border-radius:12px;padding:17px;text-shadow:none;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace"></div>';document.body.appendChild(modal);const card=modal.firstChild;
  function renderMenu(){if(!S.founded){card.innerHTML='<h2>FUNDAR ASENTAMIENTO</h2><p>Establece aquí una aldea permanente. Costo: <b>20 séqueles + 5 comida</b>.</p><button data-found>FUNDAR AQUÍ</button><button data-close>CERRAR</button>'}else{let buttons='';for(const[k,d]of Object.entries(defs))buttons+=`<button data-build="${k}">${d.label}<small>${d.cost.shekels}₪ · ${d.cost.food} comida</small></button>`;card.innerHTML=`<h2>${S.name} · NIVEL ${S.level}</h2><p>Población <b>${S.population}/${S.capacity}</b> · Defensa <b>${S.defense}</b> · Edificios <b>${S.buildings.length}</b></p><div class="grid08">${buttons}</div><button data-close>CERRAR</button>`}card.querySelector('[data-close]').onclick=closeMenu;const f=card.querySelector('[data-found]');if(f)f.onclick=found;card.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>build(b.dataset.build))}
  const style=document.createElement('style');style.textContent='#build08card h2{color:#fff0b8;margin-top:0}#build08card button{border:1px solid #d1a96b;border-radius:7px;background:#53371f;color:#fff0cf;padding:10px;margin:4px;font-weight:800}#build08card .grid08{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}#build08card .grid08 button{min-height:58px}#build08card small{display:block;opacity:.7;font-size:9px;margin-top:3px}@media(max-width:550px){#build08card{font-size:10px!important}#build08card .grid08{grid-template-columns:1fr 1fr}#build08card button{padding:8px;font-size:9px}}';document.head.appendChild(style);
  function openMenu(){renderMenu();modal.style.display='flex'}function closeMenu(){modal.style.display='none'}
  const btn=document.createElement('button');btn.id='build08btn';btn.textContent='CONSTRUIR';btn.style.cssText='position:fixed;z-index:35;right:12px;top:118px;border:1px solid #d8b97aaa;border-radius:7px;padding:7px 9px;background:#392617df;color:#fff0cf;font:9px ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:900';btn.onclick=()=>S.founded?openMenu():found;document.body.appendChild(btn);if(mobile){btn.style.top='92px';btn.style.right='8px';btn.style.fontSize='7px';btn.style.padding='5px 6px'}
  addEventListener('keydown',e=>{if((e.key==='b'||e.key==='B')&&!e.repeat){e.preventDefault();S.founded?openMenu():found()}if(e.key==='Escape'&&modal.style.display==='flex')closeMenu()});
  let foodClock=0;function tick(dt){if(!S.founded)return;foodClock+=dt;if(foodClock>25){foodClock=0;if(S.foodRate>0&&L06){L06.eco.food=Math.min(99,L06.eco.food+Math.max(1,Math.floor(S.foodRate*25)));}syncRealm();save()}if(S.mesh&&Math.hypot(player.mesh.position.x-S.x,player.mesh.position.z-S.z)<32&&S.population<S.capacity&&L06?.eco?.food>2&&Math.random()<dt*.004){S.population++;L06.eco.food--;save();syncRealm();flash(`Un nuevo habitante se unió a ${S.name}.`,1800)}}
  let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;try{tick(dt)}catch(e){console.warn('Wilderness 0.8 settlement:',e)}requestAnimationFrame(loop)}
  load();if(S.founded)rebuild();requestAnimationFrame(loop);window.WildernessSettlement={state:S,found,build,openMenu};
})();