// Wilderness 5.7 - functional siege warfare: operators, rams, ladders, towers, wall assault and capture
(()=>{
const T=window.THREE,W=window.WildernessWorld,N=window.WildernessNations50,D55=window.WildernessDiplomacy55,C56=window.WildernessConstruction56;
if(!T||!W||!N||!D55||!C56||typeof scene==='undefined'||typeof player==='undefined'||typeof followers==='undefined')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820,KEY=`wilderness57:${W.seedToken}`;
const S={states:new Map(),active:null,playerClimb:null,lastSave:0};
const saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(_){return{}}})();
const rubbleMat=new T.MeshLambertMaterial({color:0x746657,flatShading:true});
function flash57(t,m=1900){if(typeof flash==='function')flash(t,m)}
function runtime(id){return typeof generatedSettlements!=='undefined'?generatedSettlements.get(id):null}
function defOf(rt){return rt?.def||rt?.definition||rt?.source||rt}
function aliveFollowers(){return followers.filter(f=>f?.alive!==false&&f.mesh)}
function aliveDefenders(rt){return (rt?.defendersRuntime||[]).filter(e=>e?.alive!==false&&e.mesh)}
function kingAlive(rt){return !!(rt?.kingRuntime&&rt.kingRuntime.alive!==false)}
function gateList(id){return [...(D55.state?.gates?.values?.()||[])].filter(g=>g.settlementId===id)}
function nearestGate(s,from=player.mesh.position){const gs=gateList(s.id);let best=null,bd=Infinity;for(const g of gs){const d=Math.hypot(from.x-g.root.position.x,from.z-g.root.position.z);if(d<bd){bd=d;best=g}}return best}
function wallRadius(s,rt){const g=nearestGate(s,{x:s.x,z:s.z+9999});if(g)return Math.hypot(g.root.position.x-s.x,g.root.position.z-s.z);const k=rt?.settlementKind||s.settlementKind;if(s.special==='jerusalem'||s.id==='hist-jerusalem')return 106;if(k==='royal_capital')return 34;if(k==='fortified_village')return 24;if(k==='caravan_city'||k==='oasis_trade_city'||k==='inland_walled_city')return 31;return rt?.radius||s.radius||24}
function gateStrength(s){if(s.special==='jerusalem'||s.id==='hist-jerusalem')return 180;if(s.capital)return 150;if((s.tier||1)>=3)return 120;if((s.tier||1)>=2)return 95;return 72}
function oldSiegeNeutral(rt){const o=rt?.siege13;if(o){if(o.group)o.group.visible=false;o.breached=true;o.gateHp=0;o.innerOpen=true}const old23=window.WildernessSiege23?.cities;if(old23&&rt){for(const st of old23.values()){if(st.city===rt||st.city?.id===rt.id){st.outer=0;st.inner=0;st.palace=0;if(st.ram){scene.remove(st.ram);st.ram=null}}}}if(rt?.kingRuntime)rt.kingRuntime.__siege23Protected=false}
function stateFor(s){let st=S.states.get(s.id);if(st)return st;const rt=runtime(s.id),max=gateStrength(s),d=saved[s.id]||{};st={id:s.id,s,rt,gateMax:max,gateHp:Number.isFinite(d.gateHp)?d.gateHp:max,breached:!!d.breached,won:!!d.won,assault:false,machines:new Map(),accesses:[],rubble:null,stage:'approach',lastHit:0,lastDefPos:0};S.states.set(s.id,st);oldSiegeNeutral(rt);if(st.breached)breachGate(st,false);return st}
function save(){const out={};for(const [id,st] of S.states)out[id]={gateHp:st.gateHp,breached:st.breached,won:st.won};try{localStorage.setItem(KEY,JSON.stringify(out));S.lastSave=Date.now()}catch(_){}}
addEventListener('pagehide',save);
function activeSettlement(){const near=D55.state?.near;if(near?.s&&D55.state.sieges?.has?.(near.s.id)&&near.d<240)return near.s;const px=player.mesh.position.x,pz=player.mesh.position.z,defs=W.settlementsNearBounds?.(px-240,px+240,pz-240,pz+240,20)||[];let best=null,bd=240;for(const s of defs){if(!D55.state.sieges?.has?.(s.id))continue;const d=Math.hypot(px-s.x,pz-s.z);if(d<bd){bd=d;best=s}}return best}
function makeRubble(st,g){if(st.rubble||!g)return;const rg=new T.Group();rg.name=`siege57-rubble-${st.id}`;const p=g.root.position;rg.position.set(p.x,W.groundY(p.x,p.z),p.z);for(let i=0;i<(mobile?9:15);i++){const q=new T.Mesh(new T.BoxGeometry(.65+(i%3)*.25,.35+(i%2)*.24,.7+((i+1)%3)*.22),rubbleMat);q.position.set((i%5-2)*.72,.18+(i%2)*.15,(Math.floor(i/5)-1)*.78);q.rotation.set((i%2)*.22,(i*.71)%Math.PI,(i%3)*.15);q.castShadow=!mobile;rg.add(q)}scene.add(rg);st.rubble=rg}
function breachGate(st,announce=true){if(st.breached&&st._breachApplied)return;st.breached=true;st.gateHp=0;st._breachApplied=true;const gs=gateList(st.id);for(const g of gs){g.breached=true;g.state='breached';g.targetOpen=1;if(g.left)g.left.visible=false;if(g.right)g.right.visible=false;makeRubble(st,g)}oldSiegeNeutral(st.rt);window.WildernessCollision45?.rebuild?.();if(announce)flash57(`¡BRECHA ABIERTA EN ${String(st.s.name).toUpperCase()}! Tus tropas pueden entrar.`,3600);save()}
function damageGate(st,amount,source='ariete'){if(st.breached||st.won)return;st.gateHp=Math.max(0,st.gateHp-amount);st.lastHit=performance.now();if(window.WildernessPolish)window.WildernessPolish.shake=Math.min(.8,(window.WildernessPolish.shake||0)+.09);if(st.gateHp<=0)breachGate(st,true);else if(performance.now()-st._lastFlash>850){st._lastFlash=performance.now();flash57(`${source.toUpperCase()} · Puerta ${Math.ceil(st.gateHp)}/${st.gateMax}`,800)}}
function machineRecords(st){const arr=C56.state?.placed||[];return arr.filter(r=>r?.siegeId===st.id&&['ladder','ram','coveredRam','siegeTower','ramp'].includes(r.kind))}
function machineState(st,rec){let m=st.machines.get(rec.id);if(m)return m;const mesh=C56.state?.meshes?.get?.(rec.id);m={rec,mesh,kind:rec.kind,operators:[],deployed:false,progress:0,cooldown:0,access:null};st.machines.set(rec.id,m);return m}
const needs={ladder:2,ram:3,coveredRam:4,siegeTower:5,ramp:4};
function directionToCenter(st,pos){let dx=st.s.x-pos.x,dz=st.s.z-pos.z,d=Math.hypot(dx,dz)||1;return{x:dx/d,z:dz/d}}
function wallTarget(st,m){const r=wallRadius(st.s,st.rt),dir=directionToCenter(st,m.mesh.position);return{x:st.s.x-dir.x*(r+1.6),z:st.s.z-dir.z*(r+1.6),dir}}
function gateTarget(st,m){const g=nearestGate(st.s,m.mesh.position);if(!g)return wallTarget(st,m);const p=g.root.position,dir=directionToCenter(st,p);return{x:p.x-dir.x*2.1,z:p.z-dir.z*2.1,dir,gate:g}}
function moveObject(mesh,target,dt,speed,stop=1.3){const dx=target.x-mesh.position.x,dz=target.z-mesh.position.z,d=Math.hypot(dx,dz);if(d>stop){mesh.position.x+=dx/d*Math.min(d-stop,speed*dt);mesh.position.z+=dz/d*Math.min(d-stop,speed*dt);mesh.position.y=W.groundY(mesh.position.x,mesh.position.z)}mesh.rotation.y=Math.atan2(target.x-mesh.position.x,target.z-mesh.position.z)+Math.PI;return d}
function assignOperators(st,m,used){const want=needs[m.kind]||2,all=aliveFollowers().filter(f=>!used.has(f)&&!f.__siege57Climb);all.sort((a,b)=>a.mesh.position.distanceToSquared(m.mesh.position)-b.mesh.position.distanceToSquared(m.mesh.position));m.operators=all.slice(0,want);for(const f of m.operators){used.add(f);f.__siege57Controlled='operator';f.__siege57Machine=m.rec.id}}
function moveOperator(f,m,i,dt){const a=(i/(Math.max(1,m.operators.length)))*Math.PI*2,tx=m.mesh.position.x+Math.cos(a)*2.1,tz=m.mesh.position.z+Math.sin(a)*2.1,dx=tx-f.mesh.position.x,dz=tz-f.mesh.position.z,d=Math.hypot(dx,dz);if(d>.55){const sp=f.role==='cavalry'?7.2:5.3;f.mesh.position.x+=dx/d*Math.min(d-.55,sp*dt);f.mesh.position.z+=dz/d*Math.min(d-.55,sp*dt);f.mesh.rotation.y=Math.atan2(dx,dz);f.mesh.position.y=W.groundY(f.mesh.position.x,f.mesh.position.z)}return d}
function addAccess(st,m,type){if(m.access)return m.access;const t=wallTarget(st,m),r=wallRadius(st.s,st.rt),out={x:st.s.x-t.dir.x*(r+2.2),z:st.s.z-t.dir.z*(r+2.2)},inside={x:st.s.x-t.dir.x*(r-4.2),z:st.s.z-t.dir.z*(r-4.2)},top={x:st.s.x-t.dir.x*r,z:st.s.z-t.dir.z*r,y:W.groundY(t.x,t.z)+(type==='ladder'?8.0:7.5)};m.access={type,machineId:m.rec.id,outside:out,inside,top};st.accesses.push(m.access);return m.access}
function updateMachine(st,m,dt,used){if(!m.mesh)return;assignOperators(st,m,used);for(let i=0;i<m.operators.length;i++)moveOperator(m.operators[i],m,i,dt);const ready=m.operators.filter(f=>f.mesh.position.distanceTo(m.mesh.position)<3.8).length,need=needs[m.kind]||2;if(ready<Math.max(1,need-1))return;
 if(m.kind==='ram'||m.kind==='coveredRam'){
   const t=gateTarget(st,m),d=moveObject(m.mesh,t,dt,m.kind==='coveredRam'?1.0:1.25,2.4);if(d<=2.8&&!st.breached){m.cooldown-=dt;if(m.cooldown<=0){damageGate(st,(m.kind==='coveredRam'?6.2:5.1)+ready*.42,m.kind==='coveredRam'?'ariete cubierto':'ariete');m.cooldown=m.kind==='coveredRam'?1.05:.88;m.mesh.position.x-=t.dir.x*.38;m.mesh.position.z-=t.dir.z*.38;setTimeout(()=>{if(m.mesh){m.mesh.position.x+=t.dir.x*.38;m.mesh.position.z+=t.dir.z*.38}},110)}}return;
 }
 const t=wallTarget(st,m),speed=m.kind==='siegeTower'?.62:m.kind==='ramp'?.45:.9,d=moveObject(m.mesh,t,dt,speed,m.kind==='siegeTower'?2.7:1.6);if(d<3.1&&!m.deployed){m.deployed=true;if(m.kind==='ladder'){m.mesh.rotation.x=-.34;addAccess(st,m,'ladder');flash57('Escalera apoyada. Tus hombres pueden escalar la muralla.',2200)}else if(m.kind==='siegeTower'){addAccess(st,m,'tower');flash57('La torre de asedio alcanzó la muralla.',2200)}else if(m.kind==='ramp'){m.progress=.01;flash57('Comienza la construcción de la rampa contra la muralla.',2200)}}
 if(m.kind==='ramp'&&m.deployed&&m.progress<1){m.progress=Math.min(1,m.progress+dt*(.022+ready*.008));m.mesh.scale.y=.7+m.progress*.5;if(m.progress>=1){addAccess(st,m,'ramp');flash57('¡La rampa de asedio está terminada! El muro puede ser superado.',2700)}}
}
function releaseControls(st){for(const f of aliveFollowers())if(f.__siege57Controlled==='operator'){f.__siege57Controlled=null;f.__siege57Machine=null;if(f.order==='hold')f.order='follow'}for(const m of st.machines.values())m.operators=[]}
function startClimb(entity,access){if(entity===player){if(typeof mounted!=='undefined'&&mounted){flash57('Debes desmontar para escalar.',1600);return false}S.playerClimb={access,t:0,start:player.mesh.position.clone()};return true}entity.__siege57Controlled='climb';entity.__siege57Climb={access,t:0,start:entity.mesh.position.clone()};return true}
function climbPosition(c,t){const a=c.access,out=c.start,topOut=new T.Vector3(a.outside.x,a.top.y,a.outside.z),topIn=new T.Vector3(a.inside.x,a.top.y,a.inside.z),inside=new T.Vector3(a.inside.x,W.groundY(a.inside.x,a.inside.z),a.inside.z);if(t<.45)return out.clone().lerp(topOut,t/.45);if(t<.62)return topOut.clone().lerp(topIn,(t-.45)/.17);return topIn.clone().lerp(inside,(t-.62)/.38)}
function updateClimber(f,dt){const c=f.__siege57Climb;if(!c)return false;c.t=Math.min(1,c.t+dt/(c.access.type==='tower'?1.25:c.access.type==='ramp'?1.15:1.75));f.mesh.position.copy(climbPosition(c,c.t));if(c.t>=1){f.__siege57Climb=null;f.__siege57Controlled=null;f.order='attack';return false}return true}
function queueAssault(st,dt){if(!st.assault)return;const accesses=st.accesses.filter(a=>a&&((a.type!=='ramp')||true));if(!accesses.length&&!st.breached)return;for(const f of aliveFollowers()){if(f.__siege57Climb){updateClimber(f,dt);continue}if(f.__siege57Controlled)continue;if(f.order!=='attack')continue;if(st.breached){const g=nearestGate(st.s,f.mesh.position);if(g){const dir=directionToCenter(st,g.root.position),inside={x:g.root.position.x+dir.x*5,z:g.root.position.z+dir.z*5};const d=Math.hypot(f.mesh.position.x-inside.x,f.mesh.position.z-inside.z);if(d>2&&d<42){f.mesh.position.x+=(inside.x-f.mesh.position.x)/d*Math.min(d-1.2,5.5*dt);f.mesh.position.z+=(inside.z-f.mesh.position.z)/d*Math.min(d-1.2,5.5*dt);f.mesh.position.y=W.groundY(f.mesh.position.x,f.mesh.position.z)}continue}}
 let best=null,bd=22;for(const a of accesses){const d=Math.hypot(f.mesh.position.x-a.outside.x,f.mesh.position.z-a.outside.z);if(d<bd){bd=d;best=a}}if(best&&bd<3.4)startClimb(f,best);else if(best){f.__siege57Controlled='approach';const dx=best.outside.x-f.mesh.position.x,dz=best.outside.z-f.mesh.position.z,d=Math.hypot(dx,dz)||1;f.mesh.position.x+=dx/d*Math.min(d-1.5,5.1*dt);f.mesh.position.z+=dz/d*Math.min(d-1.5,5.1*dt);f.mesh.position.y=W.groundY(f.mesh.position.x,f.mesh.position.z);f.__siege57Controlled=null}}
}
function positionDefenders(st,now){if(now-st.lastDefPos<330)return;st.lastDefPos=now;const rt=st.rt;if(!rt||st.breached||st.accesses.length)return;const g=nearestGate(st.s);if(!g)return;const p=g.root.position,dir=directionToCenter(st,p),tx=-dir.z,tz=dir.x,defs=aliveDefenders(rt),arch=defs.filter(e=>e.role==='archer'),inf=defs.filter(e=>e.role!=='archer');for(let i=0;i<arch.length;i++){const off=(i-(arch.length-1)/2)*2.4,x=p.x-dir.x*1.9+tx*off,z=p.z-dir.z*1.9+tz*off,y=W.groundY(x,z)+8.0;arch[i].mesh.position.set(x,y,z);arch[i].mesh.rotation.y=Math.atan2(-dir.x,-dir.z);arch[i].__siege57Wall=true}for(let i=0;i<Math.min(inf.length,8);i++){const off=(i-3.5)*1.5,x=p.x+dir.x*6+tx*off,z=p.z+dir.z*6+tz*off;inf[i].mesh.position.set(x,W.groundY(x,z),z);inf[i].__siege57Gate=true}}
function defenderFire(st,dt){if(st.breached||st.accesses.length)return;const rt=st.rt,arch=aliveDefenders(rt).filter(e=>e.role==='archer'),targets=aliveFollowers().filter(f=>Math.hypot(f.mesh.position.x-st.s.x,f.mesh.position.z-st.s.z)<wallRadius(st.s,rt)+45);if(!targets.length||typeof fireArrow!=='function')return;for(const a of arch){if(Math.random()>dt*.22)continue;const t=targets[Math.floor(Math.random()*targets.length)];if(t&&a.mesh.position.distanceTo(t.mesh.position)<34)fireArrow(a,t,false)}}
function syncOldProtection(st){oldSiegeNeutral(st.rt);if(st.rt?.kingRuntime){const threshold=Math.max(2,Math.floor((st.s.defenders||st.rt.defenders||8)*.28));st.rt.kingRuntime.__siege57Protected=!(st.breached||st.accesses.length)||aliveDefenders(st.rt).length>threshold;st.rt.kingRuntime.__siege23Protected=false}}
function victoryCheck(st){if(st.won)return;const rt=st.rt;if(!rt)return;if(aliveDefenders(rt).length===0&&!kingAlive(rt)){st.won=true;rt.captured=true;st.s.captured=true;D55.cancelSiege?.(st.id);if(!N.state.capturedCities.includes(st.id))N.state.capturedCities.push(st.id);N.save?.();for(const g of gateList(st.id)){g.breached=true;if(g.left)g.left.visible=false;if(g.right)g.right.visible=false}releaseControls(st);flash57(`¡${String(st.s.name).toUpperCase()} HA SIDO TOMADA! El recinto está bajo tu control.`,4800);save()}}
function stage(st){if(st.won)return'RECINTO TOMADO';if(st.breached||st.accesses.length)return'ASALTO INTERIOR';const ms=[...st.machines.values()];if(!ms.length)return'PREPARAR MÁQUINAS';if(ms.some(m=>(m.kind==='ram'||m.kind==='coveredRam')))return'ROMPER LA PUERTA';return'ESCALAR LAS MURALLAS'}
const panel=document.createElement('div');panel.id='siege57';panel.innerHTML='<div id="s57info"></div><div id="s57actions"><button id="s57assault">ORDENAR ASALTO</button><button id="s57retreat">RETIRARSE</button></div><div id="s57hint"></div>';document.body.appendChild(panel);
const css=document.createElement('style');css.textContent=`#siege13{display:none!important}#siege57{display:none;position:fixed;z-index:96;left:50%;top:118px;transform:translateX(-50%);min-width:270px;max-width:min(88vw,430px);padding:8px 10px;border:1px solid #c9986d;border-radius:10px;background:#160e09e8;color:#f6e5c5;text-align:center;font:8px/1.38 ui-monospace,monospace;text-shadow:0 1px 2px #000;pointer-events:auto}#siege57 b{color:#fff0b6}#s57actions{display:flex;gap:5px;justify-content:center;margin-top:6px}#s57actions button{border:1px solid #bd8663;border-radius:7px;background:#613323;color:#ffe8cf;padding:6px 9px;font:900 7px ui-monospace,monospace;touch-action:manipulation}#s57retreat{background:#30231b!important}#s57hint{min-height:10px;margin-top:5px;color:#e8c78f}@media(pointer:coarse),(max-width:820px){#siege57{top:116px;min-width:205px;max-width:76vw;padding:6px 7px;font-size:6.5px}#s57actions button{font-size:6px;padding:6px}}`;document.head.appendChild(css);
const info=panel.querySelector('#s57info'),hint=panel.querySelector('#s57hint'),assaultBtn=panel.querySelector('#s57assault'),retreatBtn=panel.querySelector('#s57retreat');
function nearestAccess(st,max=5){let best=null,bd=max;for(const a of st.accesses){const d=Math.hypot(player.mesh.position.x-a.outside.x,player.mesh.position.z-a.outside.z);if(d<bd){bd=d;best=a}}return best}
function render(st){if(!st){panel.style.display='none';return}const defs=aliveDefenders(st.rt).length,king=kingAlive(st.rt)?1:0,ms=machineRecords(st),counts={};for(const r of ms)counts[r.kind]=(counts[r.kind]||0)+1;const machineText=Object.entries(counts).map(([k,v])=>`${({ladder:'Esc',ram:'Ariete',coveredRam:'Ariete cub.',siegeTower:'Torre',ramp:'Rampa'})[k]||k} ${v}`).join(' · ')||'ninguna';info.innerHTML=`<b>ASEDIO · ${String(st.s.name).toUpperCase()}</b><br>${stage(st)}<br>Puerta: <b>${st.breached?'BRECHA':`${Math.ceil(st.gateHp)}/${st.gateMax}`}</b> · Defensores: <b>${defs+king}</b><br>Máquinas: ${machineText}`;assaultBtn.textContent=st.assault?'ASALTO EN CURSO':'ORDENAR ASALTO';assaultBtn.disabled=st.won;const a=nearestAccess(st);hint.textContent=a?'ACCIÓN / E: ESCALAR LA MURALLA':'';panel.style.display='block'}
function orderAssault(st){st.assault=true;if(typeof setFollowMode==='function')setFollowMode('people');for(const f of aliveFollowers()){f.order='attack';f.holdPos=null}flash57(`¡ASALTO A ${String(st.s.name).toUpperCase()}!`,2200)}
assaultBtn.onpointerdown=e=>{e.preventDefault();if(S.active)orderAssault(S.active)};
retreatBtn.onpointerdown=e=>{e.preventDefault();const st=S.active;if(!st)return;for(const f of aliveFollowers()){f.__siege57Controlled=null;f.__siege57Climb=null;f.order='retreat';f.retreat=3.2}releaseControls(st);D55.cancelSiege?.(st.id);st.assault=false;flash57(`Te retiras del asedio de ${st.s.name}. La guerra con su nación continúa.`,2800)};
const oldInteract57=typeof interact==='function'?interact:null;if(oldInteract57){interact=function(){const st=S.active,a=st&&nearestAccess(st);if(a&&startClimb(player,a)){flash57(a.type==='ladder'?'Comienzas a subir la escalera.':'Cruzas la fortificación.',1400);return}return oldInteract57()}}
const oldDamage57=typeof damage==='function'?damage:null;if(oldDamage57){damage=function(e,amount){if(e?.king&&e.__siege57Protected){flash57('El rey sigue protegido por la guarnición. Abre paso y derrota a los defensores.',1500);return}if(e?.king)e.__siege23Protected=false;return oldDamage57(e,amount)}}
const oldAttack57=typeof playerAttack==='function'?playerAttack:null;if(oldAttack57){playerAttack=function(){const st=S.active;if(!st)return oldAttack57();const near=enemies?.filter?.(e=>e?.alive&&e.mesh).sort((a,b)=>a.mesh.position.distanceToSquared(player.mesh.position)-b.mesh.position.distanceToSquared(player.mesh.position))[0];if(near&&near.mesh.position.distanceTo(player.mesh.position)<3.8){if(typeof issueOrder==='function')issueOrder('attack');return damage(near,(typeof mounted!=='undefined'&&mounted)?3.2:2.6)}const g=nearestGate(st.s);if(g&&!st.breached&&player.mesh.position.distanceTo(g.root.position)<6){flash57('La puerta es demasiado sólida para la espada. Usa un ariete.',1300);return}return oldAttack57()}}
const oldUpdatePlayer57=typeof updatePlayer==='function'?updatePlayer:null;if(oldUpdatePlayer57){updatePlayer=function(dt){const c=S.playerClimb;if(!c)return oldUpdatePlayer57(dt);c.t=Math.min(1,c.t+dt/(c.access.type==='tower'?1.25:c.access.type==='ramp'?1.15:1.75));player.mesh.position.copy(climbPosition(c,c.t));player.mesh.rotation.y=Math.atan2(c.access.inside.x-c.access.outside.x,c.access.inside.z-c.access.outside.z);if(typeof updateChunks==='function')updateChunks();try{const target=player.mesh.position.clone().add(new T.Vector3(0,2.15,0)),distance=11,horizontal=Math.cos(camPitch)*distance,offset=new T.Vector3(Math.sin(camYaw)*horizontal,Math.sin(camPitch)*distance+1.8,Math.cos(camYaw)*horizontal),desired=target.clone().add(offset);camera.position.lerp(desired,1-Math.pow(.0001,dt));camera.lookAt(target)}catch(_){ }if(c.t>=1){S.playerClimb=null;flash57('Has superado la muralla.',1300)}}}
function tick(dt,now){const s=activeSettlement();if(!s){if(S.active){releaseControls(S.active);S.active=null}render(null);return}const st=stateFor(s);S.active=st;st.rt=runtime(st.id)||st.rt;oldSiegeNeutral(st.rt);if(aliveFollowers().some(f=>f.order==='attack'))st.assault=true;const used=new Set();for(const rec of machineRecords(st)){const m=machineState(st,rec);if(m.mesh)updateMachine(st,m,dt,used)}for(const f of aliveFollowers())if(f.__siege57Controlled==='operator'&&!used.has(f)){f.__siege57Controlled=null;f.__siege57Machine=null}positionDefenders(st,now);defenderFire(st,dt);queueAssault(st,dt);syncOldProtection(st);victoryCheck(st);render(st);if(Date.now()-S.lastSave>5000)save()}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;try{tick(dt,now)}catch(e){console.warn('Wilderness 5.7 siege',e)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.WildernessSiege57={state:S,stateFor,damageGate,breachGate,orderAssault,activeSettlement,startClimb};
})();