(() => {
  const W=window.WildernessWorld;
  if(!W||typeof player==='undefined')return;
  const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
  const key=`wilderness09:${W.seedToken}`;
  const firstNames=['Ammiel','Eliab','Nadab','Mattan','Reuel','Joram','Hiram','Neriah','Zaccur','Abner','Tirzah','Yael','Miriam','Adina','Keziah','Noa','Ruth','Tamar','Shira','Dinah'];
  const clans=['ben Zur','ben Ner','de Qedem','de Shalem','ben Ammón','de Beer','ben Hador','de Ramah'];
  const traits=['Leal','Valiente','Prudente','Ambicioso','Generoso','Reservado','Hábil','Devoto','Impulsivo','Paciente'];
  const jobs=['Agricultor','Pastor','Artesano','Guardia','Mercader','Constructor'];
  const Q={people:[],families:[],reputation:50,prosperity:20,security:20,stories:[],day:1,lastPopulation:0,eventClock:0,economyClock:0,dayClock:0};
  let panel=null,modal=null,card=null,btn=null;

  function rnd(salt=0){return W.hash2i((Q.people.length+1)*17+Q.day,(Q.stories.length+3)*23,salt)}
  function save(){try{localStorage.setItem(key,JSON.stringify({people:Q.people,families:Q.families,reputation:Q.reputation,prosperity:Q.prosperity,security:Q.security,stories:Q.stories,day:Q.day,lastPopulation:Q.lastPopulation}))}catch(_){}}
  function load(){try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d)Object.assign(Q,d)}catch(_){}}
  function settlement(){return window.WildernessSettlement?.state||null}
  function nameFor(i){const a=firstNames[Math.floor(W.hash2i(i,11,9101)*firstNames.length)%firstNames.length];const b=clans[Math.floor(W.hash2i(i,19,9102)*clans.length)%clans.length];return `${a} ${b}`}
  function pickJob(i){const S=settlement();const b=S?.buildings||[];const weighted=['Agricultor','Pastor','Artesano','Guardia'];if(b.includes('corral'))weighted.push('Pastor','Pastor');if(b.includes('store'))weighted.push('Mercader','Artesano');if(b.includes('tower')||b.includes('wall'))weighted.push('Guardia','Guardia');if(b.includes('hall'))weighted.push('Constructor','Mercader');return weighted[Math.floor(W.hash2i(i,31,9103)*weighted.length)%weighted.length]}
  function makePerson(i){const adult=W.hash2i(i,41,9104)>.18;return{id:`p${Date.now().toString(36)}${i}`,name:nameFor(i+Q.people.length*3),age:adult?18+Math.floor(W.hash2i(i,43,9105)*39):5+Math.floor(W.hash2i(i,47,9106)*12),trait:traits[Math.floor(W.hash2i(i,53,9107)*traits.length)%traits.length],job:adult?pickJob(i):'Niño',loyalty:45+Math.floor(W.hash2i(i,59,9108)*46),health:70+Math.floor(W.hash2i(i,61,9109)*31),family:null}}
  function syncPopulation(){const S=settlement();if(!S?.founded)return;const target=Math.max(0,S.population|0);while(Q.people.length<target){const p=makePerson(Q.people.length+Q.day);Q.people.push(p)}if(Q.people.length>target)Q.people.length=target;Q.lastPopulation=target;makeFamilies();save()}
  function makeFamilies(){Q.families=[];const adults=Q.people.filter(p=>p.age>=18),children=Q.people.filter(p=>p.age<18);for(let i=0;i<adults.length;i+=2){const members=[adults[i]?.id];if(adults[i+1])members.push(adults[i+1].id);const f={id:`f${i/2}`,name:clans[(i/2)%clans.length],members:members.filter(Boolean)};Q.families.push(f);for(const id of f.members){const p=Q.people.find(x=>x.id===id);if(p)p.family=f.id}}
    children.forEach((c,i)=>{if(!Q.families.length)return;const f=Q.families[i%Q.families.length];f.members.push(c.id);c.family=f.id});
  }
  function story(text,impact=0){Q.stories.unshift(`Día ${Q.day}: ${text}`);if(Q.stories.length>18)Q.stories.length=18;Q.reputation=Math.max(0,Math.min(100,Q.reputation+impact));if(typeof flash==='function')flash(text,2800);save();renderPanel()}
  function economyTick(){const S=settlement();if(!S?.founded||typeof L06==='undefined')return;const adults=Q.people.filter(p=>p.age>=18);const count=j=>adults.filter(p=>p.job===j).length;const farms=count('Agricultor'),pastors=count('Pastor'),craft=count('Artesano'),guards=count('Guardia'),merchants=count('Mercader'),builders=count('Constructor');
    let foodGain=Math.floor((farms*.35+pastors*.28)+(S.buildings.filter(b=>b==='corral').length*.45));let moneyGain=Math.floor(craft*.22+merchants*.4+builders*.08);if(foodGain>0)L06.eco.food=Math.min(99,L06.eco.food+foodGain);if(moneyGain>0)L06.eco.shekels+=moneyGain;
    Q.prosperity=Math.max(0,Math.min(100,20+S.buildings.length*4+merchants*3+craft*2+Math.floor((L06.eco.shekels||0)/12)));
    Q.security=Math.max(0,Math.min(100,S.defense*3+guards*4));
    const consumption=Math.max(1,Math.floor(Q.people.length/8));L06.eco.food=Math.max(0,L06.eco.food-consumption);
    if(L06.eco.food===0){Q.reputation=Math.max(0,Q.reputation-2);for(const p of Q.people)p.loyalty=Math.max(5,p.loyalty-2)}else if(Q.prosperity>55){Q.reputation=Math.min(100,Q.reputation+1)}
    if(S.realm){S.realm.wealth=L06.eco.shekels;S.realm.strength=Math.max(S.realm.strength||0,Math.floor(Q.security/3))}save();renderPanel();
  }
  function randomEvent(){const S=settlement();if(!S?.founded||Q.people.length<2)return;const roll=Math.random();if(roll<.18&&typeof L06!=='undefined'&&L06.eco.food>4){L06.eco.food-=2;Q.prosperity+=2;story('Una familia celebró un banquete y fortaleció los lazos de la aldea.',2)}else if(roll<.34){const p=Q.people[Math.floor(Math.random()*Q.people.length)];p.loyalty=Math.min(100,p.loyalty+8);story(`${p.name} se distinguió ayudando a sus vecinos.`,2)}else if(roll<.49&&Q.security<45){const loss=Math.min(6,typeof L06!=='undefined'?L06.eco.shekels:0);if(typeof L06!=='undefined')L06.eco.shekels-=loss;story(`Ladrones aprovecharon la poca vigilancia y robaron ${loss} séqueles.`,-4)}else if(roll<.64&&Q.prosperity>40){if(typeof L06!=='undefined')L06.eco.shekels+=6;story('Un mercader visitante dejó nuevas ganancias en el asentamiento.',3)}else if(roll<.79){const p=Q.people[Math.floor(Math.random()*Q.people.length)];p.health=Math.max(25,p.health-12);story(`${p.name} enfermó y necesita tiempo para recuperarse.`,-1)}else{const p=Q.people[Math.floor(Math.random()*Q.people.length)];p.loyalty=Math.min(100,p.loyalty+5);story(`${p.name} contó una historia de tus victorias alrededor del fuego.`,2)}}
  function dayTick(){Q.day++;for(const p of Q.people){if(Q.day%12===0)p.age++;if(p.health<100)p.health=Math.min(100,p.health+2);if(Q.reputation>65)p.loyalty=Math.min(100,p.loyalty+1);if(Q.reputation<30)p.loyalty=Math.max(0,p.loyalty-1)}save();renderPanel()}

  function setupUI(){panel=document.createElement('div');panel.style.cssText='position:fixed;left:12px;top:118px;z-index:24;padding:7px 9px;border:1px solid #d8b97a88;border-radius:7px;background:#1c130bc7;color:#f6e7c8;font:9px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-shadow:0 1px 2px #000;pointer-events:none;max-width:240px';document.body.appendChild(panel);
    btn=document.createElement('button');btn.textContent='SOCIEDAD';btn.style.cssText='position:fixed;z-index:36;right:12px;top:153px;border:1px solid #d8b97aaa;border-radius:7px;padding:7px 9px;background:#392617df;color:#fff0cf;font:9px ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:900';document.body.appendChild(btn);
    modal=document.createElement('div');modal.style.cssText='display:none;position:fixed;z-index:95;inset:0;background:#090604e8;align-items:center;justify-content:center;padding:16px;pointer-events:auto';modal.innerHTML='<div id="soc09card" style="width:min(94vw,620px);max-height:88vh;overflow:auto;background:#25190f;color:#f4e6c4;border:2px solid #d5ad6b;border-radius:12px;padding:16px;text-shadow:none;font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace"></div>';document.body.appendChild(modal);card=modal.firstChild;btn.onclick=open;
    if(mobile){panel.style.left='8px';panel.style.top='91px';panel.style.fontSize='7px';panel.style.maxWidth='45vw';btn.style.right='8px';btn.style.top='118px';btn.style.fontSize='7px';btn.style.padding='5px 6px'}
  }
  function renderPanel(){if(!panel)return;const S=settlement();if(!S?.founded){panel.innerHTML='<b>SOCIEDAD · 0.9</b><br>Funda una aldea para crear una comunidad.';return}panel.innerHTML=`<b>SOCIEDAD · 0.9</b><br>Día ${Q.day} · Rep. ${Math.round(Q.reputation)}/100<br>Prosperidad ${Math.round(Q.prosperity)} · Seguridad ${Math.round(Q.security)}<br>${Q.families.length} familias · ${Q.people.length} habitantes`;}
  function open(){syncPopulation();const people=Q.people.slice(0,16).map(p=>`<div class="p09"><b>${p.name}</b><span>${p.age} años · ${p.job} · ${p.trait}</span><small>Lealtad ${Math.round(p.loyalty)} · Salud ${Math.round(p.health)}</small></div>`).join('');const stories=Q.stories.slice(0,7).map(s=>`<li>${s}</li>`).join('')||'<li>Aún no hay crónicas.</li>';card.innerHTML=`<h2>SOCIEDAD DE ${settlement()?.name||'TU ALDEA'}</h2><p>Reputación <b>${Math.round(Q.reputation)}/100</b> · Prosperidad <b>${Math.round(Q.prosperity)}</b> · Seguridad <b>${Math.round(Q.security)}</b></p><h3>HABITANTES</h3><div class="people09">${people||'No hay habitantes.'}</div><h3>CRÓNICA</h3><ul>${stories}</ul><button data-close>CERRAR</button>`;card.querySelector('[data-close]').onclick=close;modal.style.display='flex'}
  function close(){modal.style.display='none'}
  const style=document.createElement('style');style.textContent='#soc09card h2,#soc09card h3{color:#fff0b8}#soc09card button{border:1px solid #d1a96b;border-radius:7px;background:#53371f;color:#fff0cf;padding:9px 12px;font-weight:800}.people09{display:grid;grid-template-columns:1fr 1fr;gap:5px}.p09{border:1px solid #8c6848;background:#171008;padding:7px;border-radius:6px}.p09 span,.p09 small{display:block;opacity:.8;margin-top:2px}@media(max-width:550px){.people09{grid-template-columns:1fr}#soc09card{font-size:9px!important}}';document.head.appendChild(style);
  addEventListener('keydown',e=>{if((e.key==='n'||e.key==='N')&&!e.repeat)open();if(e.key==='Escape'&&modal?.style.display==='flex')close()});
  function tick(dt){const S=settlement();if(!S?.founded){renderPanel();return}if(Q.lastPopulation!==S.population)syncPopulation();Q.economyClock+=dt;Q.eventClock+=dt;Q.dayClock+=dt;if(Q.economyClock>35){Q.economyClock=0;economyTick()}if(Q.eventClock>55){Q.eventClock=0;randomEvent()}if(Q.dayClock>90){Q.dayClock=0;dayTick()}}
  load();setupUI();syncPopulation();renderPanel();let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;try{tick(dt)}catch(e){console.warn('Wilderness 0.9 society:',e)}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessSociety={state:Q,open,syncPopulation};
})();