(()=>{const W=window.WildernessWorld;if(!W||typeof player==='undefined')return;const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;const S={version:'2.0',restored:false,lastSave:0,errors:0};const key=`wilderness20:${W.seedToken}`;
function bindCampUI(){const duplicate=document.getElementById('camp-controls');if(duplicate)duplicate.remove();const camp=document.getElementById('btn-camp'),shep=document.getElementById('btn-shepherds');if(camp&&!camp.__w20){camp.__w20=true;camp.addEventListener('pointerdown',e=>{e.preventDefault();if(typeof establishCamp==='function')establishCamp()})}if(shep&&!shep.__w20){shep.__w20=true;shep.addEventListener('pointerdown',e=>{e.preventDefault();if(typeof cycleShepherds==='function')cycleShepherds()})}}
function safeEntity(e){return{x:e.mesh.position.x,z:e.mesh.position.z,hp:e.hp,role:e.role||null,duty:e.duty||null}}
function collect(){const data={version:'2.0',seed:W.seedToken,time:Date.now(),player:{x:player.mesh.position.x,z:player.mesh.position.z,hp:player.hp},followers:[],livestock:[],camp:null,mounted:false,mountType:null,economy:typeof L06!=='undefined'?{...L06.eco}:null};if(typeof followers!=='undefined')data.followers=followers.filter(e=>e.alive).map(safeEntity);if(typeof livestock!=='undefined')data.livestock=livestock.filter(a=>a.alive&&a.owned).map(a=>({type:a.type,x:a.mesh.position.x,z:a.mesh.position.z,hp:a.hp,age:a.age,sex:a.sex}));if(typeof campState!=='undefined'&&campState.active)data.camp={active:true,x:campState.x,z:campState.z,condition:campState.herdCondition,shepherds:typeof livingShepherds==='function'?livingShepherds().length:0};if(typeof mounted!=='undefined'&&mounted&&typeof mount!=='undefined'&&mount){data.mounted=true;data.mountType=mount.type}return data}
function save(){try{localStorage.setItem(key,JSON.stringify(collect()));S.lastSave=Date.now()}catch(e){S.errors++;console.warn('save20',e)}}
function raw(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(_){return null}}
function restoreFollowers(list){if(!Array.isArray(list)||typeof followers==='undefined'||typeof makeHumanoid!=='function')return;const current=followers.filter(f=>f.alive);if(current.length)return;for(const d of list.slice(0,60)){const f=makeHumanoid({x:d.x,z:d.z,role:d.role||'infantry'});const ci=typeof civilians!=='undefined'?civilians.indexOf(f):-1;if(ci>=0)civilians.splice(ci,1);f.recruited=true;f.civilian=false;f.hp=Math.max(.5,Math.min(f.maxHp||5,d.hp||5));f.order='follow';f.duty=null;followers.push(f)}}
function restoreLivestock(list){if(!Array.isArray(list)||typeof livestock==='undefined'||typeof makeAnimal!=='function')return;const pools={};for(const a of livestock.filter(a=>a.alive&&a.owned))(pools[a.type]??=[]).push(a);for(const d of list){let a=(pools[d.type]||[]).shift();if(!a)a=makeAnimal(d.type,d.x,d.z,true);a.owned=true;a.mesh.position.set(d.x,W.groundY(d.x,d.z),d.z);if(Number.isFinite(d.hp))a.hp=Math.max(.5,Math.min(a.maxHp||5,d.hp));if(d.age!=null)a.age=d.age;if(d.sex)a.sex=d.sex}}
function restoreCamp(d){if(!d?.active||typeof campState==='undefined'||campState.active)return;if(typeof createCampVisual!=='function')return;campState.active=true;campState.x=d.x;campState.z=d.z;campState.herdCondition=Number.isFinite(d.condition)?d.condition:72;campState.group=createCampVisual(d.x,d.z);campState.birthProgress=0;if(typeof setShepherdCount==='function')setTimeout(()=>setShepherdCount(Math.max(0,Math.min(3,d.shepherds||0))),250)}
function restoreMount(d){if(!d?.mounted||!d.mountType||typeof livestock==='undefined')return;const a=livestock.find(x=>x.alive&&x.owned&&x.type===d.mountType);if(a){try{mounted=true;mount=a}catch(_){}}}
function restore(){const d=raw();if(!d||d.seed!==W.seedToken)return false;try{if(d.player){player.mesh.position.x=d.player.x;player.mesh.position.z=d.player.z;player.mesh.position.y=W.groundY(d.player.x,d.player.z);if(Number.isFinite(d.player.hp))player.hp=Math.max(1,Math.min(player.maxHp,d.player.hp))}if(d.economy&&typeof L06!=='undefined')Object.assign(L06.eco,d.economy);restoreFollowers(d.followers);restoreLivestock(d.livestock);restoreCamp(d.camp);restoreMount(d);S.restored=true;if(typeof flash==='function')flash('Wilderness 2.0 · Partida completa restaurada.',2200);return true}catch(e){S.errors++;console.warn('restore20',e);return false}}
function stabilizeBattle(dt){const F=window.WildernessFieldBattle;if(F){if(!F.battle){F.__peace=(F.__peace||0)+dt;if(F.__peace>7){F.enemyMorale=100;F.morale=Math.min(100,F.morale+dt*5)}}else F.__peace=0}if(typeof enemies!=='undefined'&&typeof moveAway==='function')for(const e of enemies){if(!e?.alive||!e.__fieldRout||!(e.retreat>0))continue;e.retreat=Math.max(0,e.retreat-dt);e.cooldown=Math.max(e.cooldown||0,.6);moveAway(e,player.mesh.position,dt,e.role==='cavalry'?7.2:5.3);if(e.retreat<=0)e.__fieldRout=false}}
function mobileGuard(){if(!mobile)return;const P=window.WildernessPolish;if(P?.fps&&P.fps<25&&typeof renderer!=='undefined')renderer.setPixelRatio(Math.min(devicePixelRatio,.68))}
let last=performance.now(),acc=0;function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;acc+=dt;try{bindCampUI();stabilizeBattle(dt);if(acc>5){acc=0;mobileGuard()}}catch(e){S.errors++;console.warn('stability20',e)}requestAnimationFrame(loop)}requestAnimationFrame(loop);setTimeout(()=>{if(!restore())save()},1300);setInterval(save,30000);addEventListener('pagehide',save);addEventListener('visibilitychange',()=>{if(document.hidden)save()});window.Wilderness20={state:S,save,restore};})();