// Wilderness 5.12.16 — gate-aware urban navigation for armies and hostile AI
(()=>{
const T=window.THREE,W=window.WildernessWorld;if(!T||!W||typeof scene==='undefined')return;
const S={routes:0,detours:0,lanes:new WeakMap(),laneSeq:0};
const tmp=new T.Vector3();
function radiusOf(e){if(e?.role==='cavalry')return .72;switch(e?.type){case'horse':return 1.05;case'camel':return 1.12;case'cow':return .82;case'donkey':return .78;case'lion':return .76;case'sheep':case'goat':return .56;default:return .48}}
function blocked(e,x,z,r=radiusOf(e)){const C=window.WildernessCollision45;if(!C)return false;tmp.set(x,W.groundY(x,z),z);try{return C.entityStaticBlocked?C.entityStaticBlocked(e,tmp,r):C.staticBlocked?.(tmp,r)||false}catch(_){return false}}
function support(e){const p=e?.mesh?.position,C=window.WildernessCollision45;if(!p||!C?.supportTop){if(p)p.y=W.groundY(p.x,p.z);return}try{p.y=C.supportTop(p,radiusOf(e),C.stepHeightFor?.(e)??1.08)}catch(_){p.y=W.groundY(p.x,p.z)}}
function laneFor(e){if(!e||typeof e!=='object')return 0;if(S.lanes.has(e))return S.lanes.get(e);const n=S.laneSeq++%3,l=n===0?0:n===1?-1:1;S.lanes.set(e,l);return l}
function cityCandidate(a,b){const U=window.Wilderness6UrbanAccess5131;if(!U?.nearbyCapital)return null;return U.nearbyCapital(a)||U.nearbyCapital(b)||null}
function chooseGate(cap,a,b){const U=window.Wilderness6UrbanAccess5131,gs=U?.gatePoints?.(cap.c)||[];if(!gs.length)return null;let best=null,score=Infinity;for(const g of gs){const s=Math.hypot(a.x-g.x,a.z-g.z)+Math.hypot(b.x-g.x,b.z-g.z);if(s<score){score=s;best=g}}return best}
function routeTarget(e,target){const p=e?.mesh?.position;if(!p||!target)return target;const cap=cityCandidate(p,target);if(!cap)return target;const r=cap.c.r,dc=Math.hypot(p.x-cap.p.x,p.z-cap.p.z),dt=Math.hypot(target.x-cap.p.x,target.z-cap.p.z);const pInside=dc<r-14,tInside=dt<r-14,pOutside=dc>r+7,tOutside=dt>r+7;let crossing=(pInside&&tOutside)||(pOutside&&tInside);if(!crossing){const nearWall=dc>r-25&&dc<r+25;if(!nearWall)return target;const dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d<5)return target;for(let s=3;s<Math.min(d,24);s+=3){const x=p.x+dx/d*s,z=p.z+dz/d*s;if(blocked(e,x,z)){crossing=true;break}}if(!crossing)return target}
const g=chooseGate(cap,p,target);if(!g)return target;const ox0=g.x-cap.p.x,oz0=g.z-cap.p.z,ol=Math.hypot(ox0,oz0)||1,ox=ox0/ol,oz=oz0/ol,tx=-oz,tz=ox,lane=laneFor(e)*(e?.role==='cavalry'?1.55:1.05);const gd=Math.hypot(p.x-g.x,p.z-g.z);let side;if(pOutside)side=1;else if(pInside)side=-1;else side=dt>r?1:-1;const approach={x:g.x+ox*side*8+tx*lane,z:g.z+oz*side*8+tz*lane};const through={x:g.x-ox*side*9+tx*lane,z:g.z-oz*side*9+tz*lane};S.routes++;return gd>10?approach:through}
function tryMove(e,target,dt,speed,stop=2){const p=e?.mesh?.position;if(!p||!target)return Infinity;const rt=routeTarget(e,target)||target,dx=rt.x-p.x,dz=rt.z-p.z,d=Math.hypot(dx,dz);if(d<=stop){support(e);return d}const nx=dx/d,nz=dz/d,step=Math.min(Math.max(0,d-stop),Math.max(0,speed*dt)),tries=[[nx,nz],[nx*.78-nz*.62,nz*.78+nx*.62],[nx*.78+nz*.62,nz*.78-nx*.62],[-nz,nx],[nz,-nx]];let moved=false;for(const [ax,az] of tries){const l=Math.hypot(ax,az)||1,x=p.x+ax/l*step,z=p.z+az/l*step;if(blocked(e,x,z))continue;p.x=x;p.z=z;e.mesh.rotation.y=Math.atan2(ax,az);moved=true;break}if(!moved)S.detours++;support(e);return d}
function tryAway(e,target,dt,speed){const p=e?.mesh?.position;if(!p||!target)return;let dx=p.x-target.x,dz=p.z-target.z,d=Math.hypot(dx,dz);if(d<.01){dx=1;dz=0;d=1}const nx=dx/d,nz=dz/d,step=Math.max(0,speed*dt),tries=[[nx,nz],[nx*.72-nz*.70,nz*.72+nx*.70],[nx*.72+nz*.70,nz*.72-nx*.70],[-nz,nx],[nz,-nx]];for(const [ax,az] of tries){const l=Math.hypot(ax,az)||1,x=p.x+ax/l*step,z=p.z+az/l*step;if(blocked(e,x,z))continue;p.x=x;p.z=z;e.mesh.rotation.y=Math.atan2(ax,az);break}support(e)}
const baseToward=typeof moveToward==='function'?moveToward:null,baseAway=typeof moveAway==='function'?moveAway:null;
if(baseToward)moveToward=function(e,target,dt,speed,stop=2){try{return tryMove(e,target,dt,speed,stop)}catch(err){return baseToward(e,target,dt,speed,stop)}};
if(baseAway)moveAway=function(e,target,dt,speed){try{return tryAway(e,target,dt,speed)}catch(err){return baseAway(e,target,dt,speed)}};
window.WildernessUrbanNavigation51216={version:'5.12.16',state:S,routeTarget,blocked,support,move:tryMove,away:tryAway,radiusOf};
})();