// Wilderness 4.2 - detailed facades, roof terraces, stairs and alleys
(()=>{
  const T=window.THREE,W=window.WildernessWorld;if(!T||!W||typeof scene==='undefined'||typeof generatedSettlements==='undefined')return;
  const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820,done=new Set(),groups=new Map();
  const M={stone:new T.MeshLambertMaterial({color:0x8e7c63,flatShading:true}),stone2:new T.MeshLambertMaterial({color:0x65594c,flatShading:true}),adobe:new T.MeshLambertMaterial({color:0xa8734b,flatShading:true}),adobe2:new T.MeshLambertMaterial({color:0x8e5d3e,flatShading:true}),wood:new T.MeshLambertMaterial({color:0x593721,flatShading:true}),dark:new T.MeshLambertMaterial({color:0x261a12,flatShading:true}),cloth:new T.MeshLambertMaterial({color:0x8c4d40,flatShading:true}),cloth2:new T.MeshLambertMaterial({color:0xc4a36f,flatShading:true}),road:new T.MeshLambertMaterial({color:0x9d7b59,flatShading:true})};
  function box(g,w,h,d,m,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=!mobile;q.receiveShadow=true;g.add(q);return q}
  function facade(g,x,z,w,h,rot=0,stone=false){const y=W.groundY(x,z),r=new T.Group();r.position.set(x,y,z);r.rotation.y=rot;g.add(r);const mat=stone?M.stone:M.adobe;box(r,w,h,1.15,mat,0,h/2,0);box(r,w+.25,.24,1.35,stone?M.stone2:M.wood,0,h+.12,0);box(r,1.35,2.35,.24,M.dark,0,1.18,.69);for(const sx of[-.27,.27])box(r,.72,.82,.22,M.dark,sx*w,2.55,.69);box(r,w*.72,.16,1.55,M.wood,0,3.55,.98);for(const sx of[-.30,.30])box(r,.12,1.55,.12,M.wood,sx*w,2.80,.98);if((Math.floor(x+z)&1)===0)box(r,w*.66,.13,1.42,(Math.floor(x)&1)?M.cloth:M.cloth2,0,4.0,1.0)}
  function stairs(g,x,z,rot=0){const y=W.groundY(x,z),r=new T.Group();r.position.set(x,y,z);r.rotation.y=rot;g.add(r);for(let i=0;i<6;i++)box(r,2.0,.34,.75,M.stone2,0,.17+i*.34,i*.62)}
  function terrace(g,x,z,w,d,h){const y=W.groundY(x,z);box(g,w,.25,d,M.stone,x,y+h,z);for(const sx of[-1,1])for(const sz of[-1,1])box(g,.22,1.05,.22,M.stone2,x+sx*(w*.45),y+h+.52,z+sz*(d*.43));box(g,w*.82,.12,d*.16,M.wood,x,y+h+.86,z-d*.33)}
  function alley(g,x1,z1,x2,z2){const dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz),n=Math.max(2,Math.ceil(len/3));for(let i=0;i<=n;i++){const t=i/n,x=x1+dx*t,z=z1+dz*t,y=W.groundY(x,z),q=box(g,2.1,.07,3.1,M.road,x,y+.035,z);q.rotation.y=Math.atan2(dx,dz)}}
  function build(s){if(!s?.id||done.has(s.id)||s.type!=='city')return;done.add(s.id);const g=new T.Group();g.name='urban42-'+s.id;scene.add(g);groups.set(s.id,g);const count=mobile?8:16;for(let i=0;i<count;i++){const a=i/count*Math.PI*2+.16,rr=11+(i%3)*5.5,x=s.x+Math.cos(a)*rr,z=s.z+Math.sin(a)*rr;if(Math.abs(x-s.x)<4||Math.abs(z-s.z)<4)continue;facade(g,x,z,5.0+(i%3)*.8,5.0+(i%4===0?3.4:0),a+Math.PI/2,i%3===0);if(i%4===0){stairs(g,x+Math.cos(a+1.57)*3.4,z+Math.sin(a+1.57)*3.4,a);terrace(g,x,z,5.4,4.4,5.2)}}for(let i=0;i<5;i++){const x=s.x-15+i*7.5;alley(g,x,s.z-13,x+4,s.z+13)}for(let i=0;i<3;i++){const x=s.x-7+i*7,z=s.z+8,y=W.groundY(x,z);box(g,3.4,.12,2.5,i%2?M.cloth:M.cloth2,x,y+3.0,z);for(const dx of[-1.35,1.35])for(const dz of[-.9,.9])box(g,.1,2.9,.1,M.wood,x+dx,y+1.45,z+dz)}}
  function tick(){for(const s of generatedSettlements.values())build(s)}let last=0;function loop(t){if(t-last>700){last=t;tick()}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessUrban42={groups};
})();