(()=>{
const T=window.THREE,W=window.WildernessWorld;if(!T||!W||typeof scene==='undefined'||typeof player==='undefined')return;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
const V={decorated:new Set(),groups:new Map(),settlements:new Set(),settlementGroups:new Map(),lastChunk:'',lastSettleScan:0};
const m={sand:new T.MeshLambertMaterial({color:0xc9a66d,flatShading:true}),sand2:new T.MeshLambertMaterial({color:0xb98d58,flatShading:true}),stone:new T.MeshLambertMaterial({color:0x8a795f,flatShading:true}),stone2:new T.MeshLambertMaterial({color:0x6f6557,flatShading:true}),adobe:new T.MeshLambertMaterial({color:0xb67c50,flatShading:true}),adobe2:new T.MeshLambertMaterial({color:0x946140,flatShading:true}),wood:new T.MeshLambertMaterial({color:0x5b3925,flatShading:true}),cloth:new T.MeshLambertMaterial({color:0x8d4f43,flatShading:true}),cloth2:new T.MeshLambertMaterial({color:0xd0b07b,flatShading:true}),leaf:new T.MeshLambertMaterial({color:0x506b36,flatShading:true}),leaf2:new T.MeshLambertMaterial({color:0x6f8145,flatShading:true}),dark:new T.MeshLambertMaterial({color:0x24180f,flatShading:true})};
function box(g,w,h,d,mat,x,y,z){const q=new T.Mesh(new T.BoxGeometry(w,h,d),mat);q.position.set(x,y,z);q.castShadow=!mobile;q.receiveShadow=true;g.add(q);return q}
function palm(g,x,z,s=1){const y=W.groundY(x,z);box(g,.58*s,6.8*s,.58*s,m.wood,x,y+3.4*s,z);for(let i=0;i<7;i++){const a=i*Math.PI*2/7,q=box(g,.34*s,.16*s,3.3*s,i%2?m.leaf:m.leaf2,x,y+7.1*s,z);q.rotation.y=a;q.rotation.x=(i%2?-.13:.08)}}
function acacia(g,x,z,s=1){const y=W.groundY(x,z);box(g,.52*s,5.4*s,.52*s,m.wood,x,y+2.7*s,z);box(g,4.4*s,.72*s,3.8*s,m.leaf,x,y+5.7*s,z);box(g,3.0*s,.62*s,2.7*s,m.leaf2,x+.4*s,y+6.3*s,z-.2*s)}
function awning(g,x,y,z,w,d,mat){const q=box(g,w,.12,d,mat,x,y,z);q.rotation.x=.06;for(const dx of[-w*.43,w*.43])for(const dz of[-d*.42,d*.42])box(g,.11,2.2,.11,m.wood,x+dx,y-1.1,z+dz)}
function house(g,x,z,w,d,h,mat,rot=0,floors=1){const y=W.groundY(x,z),root=new T.Group();root.position.set(x,y,z);root.rotation.y=rot;g.add(root);for(let f=0;f<floors;f++){const fy=f*h;box(root,w,h,d,mat,0,fy+h/2,0);box(root,w+.3,.22,d+.3,m.wood,0,fy+h+.11,0);box(root,1.05,1.7,.18,m.dark,0,fy+.85,d/2+.10);for(const sx of[-1,1])box(root,.58,.68,.18,m.dark,sx*w*.24,fy+h*.62,d/2+.10)}if(floors>1){const bw=w*.72;box(root,bw,.16,1.35,m.wood,0,h*1.22,d/2+.65);box(root,.11,1.3,.11,m.wood,-bw*.43,h*.58,d/2+.65);box(root,.11,1.3,.11,m.wood,bw*.43,h*.58,d/2+.65)}return root}
function tent(g,x,z,s=1,rot=0){const y=W.groundY(x,z),r=new T.Group();r.position.set(x,y,z);r.rotation.y=rot;g.add(r);const roof=box(r,6.4*s,.24,4.5*s,m.cloth,0,2.7*s,0);roof.rotation.z=.10;box(r,6.1*s,.15,4.2*s,m.cloth2,0,2.18*s,0);for(const dx of[-2.7,2.7])for(const dz of[-1.7,1.7])box(r,.12,2.6*s,.12,m.wood,dx*s,1.3*s,dz*s);box(r,2.5*s,.12,1.2*s,m.dark,0,.10*s,0)}
function cityDetails(s){if(!s?.id||V.settlements.has(s.id))return;V.settlements.add(s.id);const g=new T.Group();g.name='v40-'+s.id;const city=s.type==='city';const radius=city?23:14;
if(city){const count=mobile?8:14;for(let i=0;i<count;i++){const a=i/count*Math.PI*2+(W.randAt(s.x,s.z,40100+i)-.5)*.38,rr=7+W.randAt(s.x,s.z,40200+i)*(radius-8),x=s.x+Math.cos(a)*rr,z=s.z+Math.sin(a)*rr;const floors=1+Math.floor(W.randAt(x,z,40300)*3),h=3.7+W.randAt(x,z,40400)*.8,w=5.8+W.randAt(x,z,40500)*2.7,d=4.8+W.randAt(x,z,40600)*2.1;house(g,x,z,w,d,h,i%3?m.adobe:m.stone,(a+Math.PI*.5),floors)}for(let i=0;i<5;i++){const a=i*.9+.2,x=s.x-9+i*4.4,z=s.z+4+Math.sin(a)*2;awning(g,x,W.groundY(x,z)+3.1,z,4.0,2.8,i%2?m.cloth:m.cloth2)}const cy=W.groundY(s.x,s.z);box(g,8.5,7.8,7.0,m.stone,s.x,cy+3.9,s.z-3);box(g,7.7,.28,6.4,m.wood,s.x,cy+7.94,s.z-3)}else{const count=mobile?7:11;for(let i=0;i<count;i++){const a=i/count*Math.PI*2,rr=5+W.randAt(s.x,s.z,40700+i)*10,x=s.x+Math.cos(a)*rr,z=s.z+Math.sin(a)*rr;if(i%3!==0)tent(g,x,z,.82+W.randAt(x,z,40800)*.32,a);else house(g,x,z,6.6,5.2,3.7,m.adobe,a,1)}for(let i=0;i<3;i++){const x=s.x-5+i*5,z=s.z+2;awning(g,x,W.groundY(x,z)+2.8,z,4.2,2.8,i%2?m.cloth:m.cloth2)}}scene.add(g);V.settlementGroups.set(s.id,{g,s})}
function scanSettlements(){if(typeof generatedSettlements==='undefined')return;for(const s of generatedSettlements.values())cityDetails(s)}
function decorateChunk(cx,cz){const key=`${cx},${cz}`;if(V.decorated.has(key))return;V.decorated.add(key);const g=new T.Group();g.name='v40chunk-'+key;const minX=cx*W.CHUNK_SIZE,minZ=cz*W.CHUNK_SIZE,count=mobile?4:7;for(let i=0;i<count;i++){const x=minX+6+W.hash2i(cx,cz,41000+i*4)*(W.CHUNK_SIZE-12),z=minZ+6+W.hash2i(cx,cz,41001+i*4)*(W.CHUNK_SIZE-12),b=W.biomeAt(x,z),r=W.hash2i(cx,cz,41002+i*4),s=.85+W.hash2i(cx,cz,41003+i*4)*.65;if(W.roadAt(x,z))continue;if((b==='fertile'||b==='oasis')&&r>.25)palm(g,x,z,s);else if(b==='steppe'&&r>.45)acacia(g,x,z,s);else if(b==='rocky'&&r>.82){const y=W.groundY(x,z);box(g,3.5*s,2.7*s,3.0*s,m.stone2,x,y+1.35*s,z)}}scene.add(g);V.groups.set(key,g)}
function cleanup(cx,cz){const keep=(mobile?2:3)+1;for(const[k,g]of [...V.groups]){const[a,b]=k.split(',').map(Number);if(Math.abs(a-cx)>keep||Math.abs(b-cz)>keep){scene.remove(g);V.groups.delete(k);V.decorated.delete(k)}}}
function lighting(){scene.background.setHex(0xc8d6d4);scene.fog.color.setHex(0xc9b98e);scene.fog.density=mobile?.0048:.0036;scene.traverse(o=>{if(o.isHemisphereLight){o.intensity=1.35;o.color.setHex(0xffe7be);o.groundColor.setHex(0x66523e)}if(o.isDirectionalLight){o.intensity=2.55;o.color.setHex(0xffdca1);o.position.set(-85,120,55)}});renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.outputColorSpace=T.SRGBColorSpace}
function installHUD(){document.title='Wilderness — 4.0';const st=document.querySelector('#startup strong');if(st)st.textContent='WILDERNESS 4.0';const style=document.createElement('style');style.textContent=`#stats.panel{background:linear-gradient(180deg,#17110bd9,#20160dd0);border:1px solid #d6b77a99;border-radius:9px;box-shadow:0 10px 30px #0006;font-size:10px;line-height:1.45}#message.panel{border-radius:8px;background:#1a120bd9;border:1px solid #e2c58d88}#weapon-toggle15{background:#21170fdd!important;border:1px solid #d8bb80aa!important;box-shadow:0 5px 15px #0007}#world-button{background:#21170fdd!important}body:before{content:'';position:fixed;z-index:2;inset:0;pointer-events:none;box-shadow:inset 0 0 120px #2a170c22}@media(pointer:coarse),(max-width:820px){#weapon-toggle15{top:auto!important;right:90px!important;bottom:130px!important;border-radius:50%!important;width:58px;height:58px;padding:5px!important;font-size:7px!important}}`;document.head.appendChild(style)}
lighting();installHUD();
let last='';function tick(t){const cx=Math.floor(player.mesh.position.x/W.CHUNK_SIZE),cz=Math.floor(player.mesh.position.z/W.CHUNK_SIZE),k=`${cx},${cz}`;if(k!==last){last=k;const r=mobile?2:3;for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++)decorateChunk(cx+x,cz+z);cleanup(cx,cz);scanSettlements()}if(t-V.lastSettleScan>1800){V.lastSettleScan=t;scanSettlements()}requestAnimationFrame(tick)}requestAnimationFrame(tick);window.WildernessVisual40=V;
})();