// Wilderness 5.10.7 — georeferenced interactive world map
(()=>{
  if(window.WildernessWorldMap5107)return;
  const G=window.WildernessGeo5107;if(!G){console.warn('WildernessGeo5107 missing');return;}
  window.WildernessWorldMap5107={version:'5.10.7'};
  const BLOCK_NAMES={'1':'Judá · Samaria central','2':'Filistea · Sefelá','3':'Jezreel · Galilea','4':'Galaad · Amón · Moab','5':'Edom · Arabá · Aqaba','6':'Fenicia · Aram','7':'Norte neo-hitita · Éufrates','8':'Egipto · Sinaí · Nilo'};
  const BLOCK_COLORS={'1':'#e9cf8f','2':'#cf9f70','3':'#b6c782','4':'#c7a56a','5':'#b97b55','6':'#8fb6a1','7':'#9d9a7b','8':'#d7bd78'};
  const TYPE_NAMES={city:'Ciudad',settlement:'Asentamiento',mining_district:'Distrito minero',port:'Puerto',oasis_settlement:'Oasis',fortress:'Fortaleza',ruins:'Ruinas',monument:'Monumento',ruins_mining:'Ruinas/minas',landmark:'Hito'};
  const PRECISION={high:'ubicación conocida',medium:'ubicación aproximada',low:'identificación debatida',traditional:'ubicación tradicional'};
  let cities=[],cityById=new Map(),routes=[],landTopo=null,riversGeo=null,lakesGeo=null;
  let canvas,ctx,modal,info,status,btn,zoom=1,panX=0,panY=0,drag=false,moved=false,lastX=0,lastY=0,selected=null,showRoutes=true,showLabels=true;

  function csvRows(text){const ls=String(text||'').trim().split(/\r?\n/);if(ls.length<2)return[];const h=ls.shift().split(',');return ls.filter(Boolean).map(line=>{const p=line.split(','),o={};h.forEach((k,i)=>o[k]=p[i]??'');return o;});}
  function blockKey(v){return String(v||'').split('-')[0];}
  function routePoint(id){return cityById.get(id)||G.waypoints[id]||null;}
  function buildUI(){
    const s=document.createElement('style');s.textContent=`
      #wm5107btn{position:fixed;z-index:31;top:calc(12px + env(safe-area-inset-top,0px));right:calc(72px + env(safe-area-inset-right,0px));border:1px solid #d8b97a88;border-radius:8px;padding:7px 9px;color:#f7e4bb;background:#1c130bcc;font:700 9px ui-monospace,SFMono-Regular,Menlo,monospace;pointer-events:auto;text-shadow:0 1px 2px #000}
      #wm5107{display:none;position:fixed;z-index:180;inset:0;background:#0d1820;color:#f4e6c4;pointer-events:auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;touch-action:none}#wm5107.open{display:block}
      #wm5107top{position:absolute;z-index:4;left:0;right:0;top:0;min-height:54px;display:flex;align-items:center;gap:7px;padding:calc(8px + env(safe-area-inset-top,0px)) calc(10px + env(safe-area-inset-right,0px)) 8px calc(10px + env(safe-area-inset-left,0px));background:#21170fed;border-bottom:1px solid #cfae7166}
      #wm5107top strong{font-size:12px;color:#fff0b8;margin-right:auto;white-space:nowrap}.wm5107ctl{border:1px solid #d6b87a99;background:#352517;color:#f7e4bb;border-radius:7px;padding:7px 9px;font:700 9px inherit}.wm5107ctl.on{background:#72512c}
      #wm5107canvas{position:absolute;inset:0;width:100%;height:100%;display:block;image-rendering:auto;touch-action:none}
      #wm5107info{position:absolute;z-index:4;left:calc(10px + env(safe-area-inset-left,0px));bottom:calc(10px + env(safe-area-inset-bottom,0px));max-width:min(420px,72vw);background:#20160ee8;border:1px solid #d6b87a88;border-radius:9px;padding:9px 11px;font-size:10px;line-height:1.45;box-shadow:0 5px 20px #0008}#wm5107info b{color:#fff0b8}
      #wm5107status{position:absolute;z-index:4;right:calc(10px + env(safe-area-inset-right,0px));bottom:calc(10px + env(safe-area-inset-bottom,0px));background:#20160ede;border:1px solid #d6b87a66;border-radius:8px;padding:7px 9px;font-size:8px;max-width:44vw;text-align:right}
      #wm5107legend{position:absolute;z-index:3;right:calc(10px + env(safe-area-inset-right,0px));top:calc(64px + env(safe-area-inset-top,0px));background:#20160ed4;border:1px solid #d6b87a55;border-radius:8px;padding:7px 8px;font-size:7px;line-height:1.55;pointer-events:none}#wm5107legend span{display:block;white-space:nowrap}#wm5107legend i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px}
      @media(pointer:coarse),(max-width:820px){#wm5107btn{right:calc(65px + env(safe-area-inset-right,0px));font-size:7px;padding:7px}#wm5107top{gap:4px;min-height:48px}#wm5107top strong{font-size:8px;max-width:34vw;overflow:hidden;text-overflow:ellipsis}.wm5107ctl{padding:6px 7px;font-size:8px}#wm5107legend{display:none}#wm5107info{font-size:8px;max-width:70vw}#wm5107status{font-size:7px}}
    `;document.head.appendChild(s);
    btn=document.createElement('button');btn.id='wm5107btn';btn.textContent='MAPA';btn.title='Mapa geográfico del mundo (M)';document.body.appendChild(btn);
    modal=document.createElement('div');modal.id='wm5107';modal.innerHTML=`<div id="wm5107top"><strong>MAPA REAL · WILDERNESS 6</strong><button class="wm5107ctl" data-a="minus">−</button><button class="wm5107ctl" data-a="plus">+</button><button class="wm5107ctl" data-a="reset">TODO</button><button class="wm5107ctl on" data-a="routes">RUTAS</button><button class="wm5107ctl on" data-a="labels">NOMBRES</button><button class="wm5107ctl" data-a="close">CERRAR</button></div><canvas id="wm5107canvas"></canvas><div id="wm5107legend">${Object.entries(BLOCK_NAMES).map(([k,n])=>`<span><i style="background:${BLOCK_COLORS[k]}"></i>${k}. ${n}</span>`).join('')}</div><div id="wm5107info"><b>Geografía real</b><br>Las posiciones se derivan de latitud/longitud. Arrastra, haz zoom y toca una ciudad.</div><div id="wm5107status">Cargando geografía…</div>`;document.body.appendChild(modal);
    canvas=modal.querySelector('#wm5107canvas');ctx=canvas.getContext('2d');info=modal.querySelector('#wm5107info');status=modal.querySelector('#wm5107status');btn.onclick=open;
    modal.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='close')return close();if(a==='plus'){zoom=Math.min(18,zoom*1.35);draw();}if(a==='minus'){zoom=Math.max(.55,zoom/1.35);draw();}if(a==='reset'){zoom=1;panX=panY=0;selected=null;defaultInfo();draw();}if(a==='routes'){showRoutes=!showRoutes;b.classList.toggle('on',showRoutes);draw();}if(a==='labels'){showLabels=!showLabels;b.classList.toggle('on',showLabels);draw();}});
    canvas.addEventListener('pointerdown',e=>{drag=true;moved=false;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;panX+=dx;panY+=dy;lastX=e.clientX;lastY=e.clientY;draw();});canvas.addEventListener('pointerup',e=>{drag=false;if(!moved)pick(e.clientX,e.clientY)});canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.55,Math.min(18,zoom*(e.deltaY<0?1.18:1/1.18)));draw()},{passive:false});
    addEventListener('resize',resize);document.addEventListener('keydown',keys,true);
  }
  function keys(e){if((e.key==='m'||e.key==='M')&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();modal?.classList.contains('open')?close():open();return;}if(!modal?.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();return;}if(['w','a','s','d','W','A','S','D',' ','e','E','f','F','c','C','k','K'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();}}
  function open(){modal.classList.add('open');resize();draw();}function close(){modal.classList.remove('open');}
  function resize(){if(!canvas)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw();}
  function size(){const r=canvas.getBoundingClientRect();return{w:r.width,h:r.height};}
  const C=Math.cos(((G.BOUNDS.minLat+G.BOUNDS.maxLat)/2)*Math.PI/180);
  function baseScale(){const {w,h}=size(),gw=(G.BOUNDS.maxLon-G.BOUNDS.minLon)*C,gh=G.BOUNDS.maxLat-G.BOUNDS.minLat;return Math.min((w-32)/gw,(h-82)/gh);}
  function toScreen(lon,lat){const {w,h}=size(),clon=(G.BOUNDS.minLon+G.BOUNDS.maxLon)/2,clat=(G.BOUNDS.minLat+G.BOUNDS.maxLat)/2,s=baseScale()*zoom;return{x:w/2+(lon-clon)*C*s+panX,y:h/2-(lat-clat)*s+panY};}
  function visibleBBox(coords){let minLon=999,maxLon=-999,minLat=999,maxLat=-999;for(const p of coords){if(!p||p.length<2)continue;minLon=Math.min(minLon,p[0]);maxLon=Math.max(maxLon,p[0]);minLat=Math.min(minLat,p[1]);maxLat=Math.max(maxLat,p[1]);}return !(maxLon<G.BOUNDS.minLon-2||minLon>G.BOUNDS.maxLon+2||maxLat<G.BOUNDS.minLat-2||minLat>G.BOUNDS.maxLat+2);}
  function pathLL(coords,closePath=false){if(!coords?.length)return;ctx.beginPath();coords.forEach((p,i)=>{const q=toScreen(p[0],p[1]);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});if(closePath)ctx.closePath();}

  function decodeArc(top,i){const rev=i<0,idx=rev?~i:i,a=top.arcs[idx];if(!a)return[];let x=0,y=0;const sc=top.transform?.scale||[1,1],tr=top.transform?.translate||[0,0],pts=a.map(d=>{x+=d[0];y+=d[1];return[x*sc[0]+tr[0],y*sc[1]+tr[1]]});return rev?pts.reverse():pts;}
  function ringFromArcs(top,ids){let out=[];ids.forEach((id,n)=>{let a=decodeArc(top,id);if(n&&a.length)a=a.slice(1);out=out.concat(a)});return out;}
  function drawTopoGeometry(top,g){if(!g)return;if(g.type==='GeometryCollection'){g.geometries.forEach(x=>drawTopoGeometry(top,x));return;}const polys=g.type==='Polygon'?[g.arcs]:g.type==='MultiPolygon'?g.arcs:[];for(const poly of polys){if(!poly?.length)continue;const outer=ringFromArcs(top,poly[0]);if(!visibleBBox(outer))continue;pathLL(outer,true);for(let i=1;i<poly.length;i++){const hole=ringFromArcs(top,poly[i]);if(hole.length){const q=toScreen(hole[0][0],hole[0][1]);ctx.moveTo(q.x,q.y);for(let j=1;j<hole.length;j++){const t=toScreen(hole[j][0],hole[j][1]);ctx.lineTo(t.x,t.y)}ctx.closePath();}}ctx.fillStyle='#493f2c';ctx.fill('evenodd');ctx.strokeStyle='#8f805f';ctx.lineWidth=.55;ctx.stroke();}}
  function drawLand(){ctx.fillStyle='#173b4b';const {w,h}=size();ctx.fillRect(0,0,w,h);if(landTopo?.objects?.land){drawTopoGeometry(landTopo,landTopo.objects.land);return;}ctx.fillStyle='#493f2c';ctx.fillRect(w*.38,55,w*.62,h-55);}
  function eachGeom(g,fn){if(!g)return;if(g.type==='FeatureCollection')return g.features.forEach(f=>eachGeom(f,fn));if(g.type==='Feature')return eachGeom(g.geometry,fn);if(g.type==='LineString')fn(g.coordinates,false);else if(g.type==='MultiLineString')g.coordinates.forEach(c=>fn(c,false));else if(g.type==='Polygon')g.coordinates.forEach((c,i)=>fn(c,i===0));else if(g.type==='MultiPolygon')g.coordinates.forEach(p=>p.forEach((c,i)=>fn(c,i===0)));}
  function drawLakes(){if(lakesGeo){eachGeom(lakesGeo,(c,outer)=>{if(!outer||!visibleBBox(c))return;pathLL(c,true);ctx.fillStyle='#245769';ctx.fill();ctx.strokeStyle='#78a8b6';ctx.lineWidth=.55;ctx.stroke();});}else drawLocalLakes();}
  function drawRivers(){if(riversGeo){eachGeom(riversGeo,c=>{if(!visibleBBox(c))return;pathLL(c);ctx.strokeStyle='#4f94a9';ctx.lineWidth=Math.max(.55,1.05*zoom);ctx.globalAlpha=.72;ctx.stroke();ctx.globalAlpha=1;});}drawMandatoryHydrology();}
  function drawLocalLakes(){const dead=[[35.47,31.79],[35.54,31.65],[35.56,31.45],[35.50,31.20],[35.43,31.05],[35.40,31.25],[35.42,31.55]],gal=[[35.53,32.89],[35.63,32.86],[35.64,32.76],[35.58,32.69],[35.52,32.75]];for(const p of [dead,gal]){pathLL(p,true);ctx.fillStyle='#245769';ctx.fill();ctx.strokeStyle='#78a8b6';ctx.stroke();}}
  function line(points,w=1.1,color='#56a1b6',dash=[]){pathLL(points);ctx.strokeStyle=color;ctx.lineWidth=Math.max(.65,w*zoom);ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
  function drawMandatoryHydrology(){
    line([[35.65,33.25],[35.62,33.10],[35.59,32.89],[35.59,32.70],[35.55,32.50],[35.56,32.20],[35.54,31.87],[35.48,31.55]],1.35);
    line([[32.66,25.72],[31.92,26.18],[30.80,27.78],[31.25,29.85],[31.31,30.13],[31.45,30.55],[31.88,30.98]],1.65);
    line([[31.45,30.55],[30.77,30.97]],.9);line([[31.45,30.55],[31.88,30.98]],.9);line([[31.45,30.55],[32.30,31.10]],.9);
    line([[36.05,34.10],[36.20,34.45],[36.50,34.85],[36.75,35.13],[36.63,35.55],[36.38,36.05]],1.05);
    line([[35.70,33.92],[35.55,33.60],[35.35,33.33]],.9);
    line([[36.28,33.52],[36.05,33.48],[35.90,33.45]],.85);
    line([[35.95,32.12],[35.78,32.08],[35.58,32.12]],.85);
    line([[35.78,31.50],[35.70,31.42],[35.47,31.40]],.85);
    line([[35.20,32.80],[35.08,32.78],[34.95,32.82]],.8);
    line([[38.36,38.38],[38.20,38.00],[37.95,37.55],[38.01,36.83],[38.35,36.45]],1.7);
  }
  function drawRoutes(){if(!showRoutes)return;const styles={road:['#d3a85c',1.15,[]],trail:['#b69572',1,[4,4]],ferry:['#8bb5c1',1,[5,4]],sea:['#70aab8',1,[6,5]],mixed:['#b6a969',1.1,[2,3]]};for(const r of routes){const pts=r.nodes.map(routePoint).filter(Boolean);if(pts.length<2)continue;const st=styles[r.mode]||styles.road;ctx.beginPath();pts.forEach((p,i)=>{const q=toScreen(+p.lon,+p.lat);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.strokeStyle=st[0];ctx.lineWidth=Math.max(.65,st[1]*zoom);ctx.globalAlpha=.68;ctx.setLineDash(st[2]);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;}}
  function markerRadius(c){const base=c.type==='city'?2.15:c.type==='monument'||c.type==='landmark'?2.35:1.8;return Math.max(1.6,Math.min(5.4,base*Math.sqrt(zoom)));}
  function drawCities(){const placed=[];for(const c of cities){const q=toScreen(+c.lon,+c.lat),r=markerRadius(c),k=blockKey(c.block);ctx.beginPath();ctx.arc(q.x,q.y,r,0,Math.PI*2);ctx.fillStyle=BLOCK_COLORS[k]||'#eee';ctx.fill();ctx.strokeStyle=c.precision==='low'?'#d7a0a0':'#20160e';ctx.lineWidth=selected===c?2.2:1;ctx.stroke();if(selected===c){ctx.beginPath();ctx.arc(q.x,q.y,r+4,0,Math.PI*2);ctx.strokeStyle='#fff0b8';ctx.lineWidth=1.2;ctx.stroke();}if(showLabels&&zoom>.72){const fs=Math.max(6,Math.min(11,6.2*zoom));ctx.font=`${c.radius>=200?'700':'500'} ${fs}px ui-monospace,monospace`;ctx.textBaseline='middle';let tx=q.x+r+3,ty=q.y;const tw=ctx.measureText(c.name).width;for(const p of placed){if(Math.abs(p.y-ty)<fs+2&&tx<p.x+p.w+3&&tx+tw>p.x-3)ty+=fs+3;}ctx.fillStyle='#f3e3bc';ctx.shadowColor='#000';ctx.shadowBlur=2;ctx.fillText(c.name,tx,ty);ctx.shadowBlur=0;placed.push({x:tx,y:ty,w:tw});}}}
  function drawGraticule(){ctx.globalAlpha=.16;ctx.strokeStyle='#d9c99d';ctx.lineWidth=.5;for(let lat=26;lat<=38;lat+=2){const a=toScreen(G.BOUNDS.minLon,lat),b=toScreen(G.BOUNDS.maxLon,lat);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}for(let lon=31;lon<=39;lon+=2){const a=toScreen(lon,G.BOUNDS.minLat),b=toScreen(lon,G.BOUNDS.maxLat);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.globalAlpha=1;}
  function draw(){if(!ctx)return;drawLand();drawLakes();drawRivers();drawGraticule();drawRoutes();drawCities();}
  function defaultInfo(){info.innerHTML='<b>Geografía real</b><br>Ciudades y landmarks están proyectados desde latitud/longitud. Las rutas enlazan los mismos nodos del mundo 3D.';}
  function pick(clientX,clientY){const r=canvas.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top;let best=null,bd=18;for(const c of cities){const q=toScreen(+c.lon,+c.lat),d=Math.hypot(q.x-x,q.y-y);if(d<bd){best=c;bd=d;}}selected=best;if(best){const p=PRECISION[best.precision]||best.precision;info.innerHTML=`<b>${best.name}</b><br>${TYPE_NAMES[best.type]||best.type} · Bloque ${best.block}<br>Lat ${(+best.lat).toFixed(4)}° · Lon ${(+best.lon).toFixed(4)}°<br>Juego: X ${Math.round(+best.x)} · Z ${Math.round(+best.z)}<br><span style="opacity:.78">${p}</span>`;}else defaultInfo();draw();}
  function groupRoutes(rows){const m=new Map();for(const o of rows){if(!m.has(o.route_id))m.set(o.route_id,{id:o.route_id,name:o.route_name,mode:o.mode,nodes:[]});m.get(o.route_id).nodes.push({seq:+o.sequence,id:o.node});}return[...m.values()].map(r=>{r.nodes.sort((a,b)=>a.seq-b.seq);r.nodes=r.nodes.map(n=>n.id);return r;});}
  async function load(){try{const [ct,rt,physical]=await Promise.all([fetch(G.coordsUrl).then(r=>{if(!r.ok)throw Error('coordenadas');return r.text()}),fetch(G.roadsUrl).then(r=>{if(!r.ok)throw Error('rutas');return r.text()}),Promise.allSettled([fetch(G.physical.land).then(r=>r.json()),fetch(G.physical.rivers).then(r=>r.json()),fetch(G.physical.lakes).then(r=>r.json())])]);cities=csvRows(ct).map(o=>({...o,lat:+o.lat,lon:+o.lon,x:+o.x,z:+o.z,radius:+o.radius}));cityById=new Map(cities.map(c=>[c.id,c]));routes=groupRoutes(csvRows(rt));if(physical[0].status==='fulfilled')landTopo=physical[0].value;if(physical[1].status==='fulfilled')riversGeo=physical[1].value;if(physical[2].status==='fulfilled')lakesGeo=physical[2].value;const real=!!landTopo;status.textContent=`${cities.length} sitios · ${routes.length} rutas · ${real?'base física real':'base física simplificada'}`;draw();}catch(e){console.warn('World map 5.10.7',e);status.textContent='No se pudo cargar el mapa georreferenciado';}}
  buildUI();load();
})();
