(() => {
  const THREE=window.THREE,W=window.WildernessWorld;
  if(!THREE||!W||typeof scene==='undefined'||typeof player==='undefined')return;
  const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<=820;
  const V={decorated:new Set(),groups:new Map(),settlements:new Set(),settlementGroups:new Map(),lastChunk:'',atmo:''};
  const mats={water:new THREE.MeshLambertMaterial({color:0x4f8994,transparent:true,opacity:.72,flatShading:true}),grass:new THREE.MeshLambertMaterial({color:0x657946,flatShading:true}),dry:new THREE.MeshLambertMaterial({color:0x9a8656,flatShading:true}),darkLeaf:new THREE.MeshLambertMaterial({color:0x4e6539,flatShading:true}),stone:new THREE.MeshLambertMaterial({color:0x786856,flatShading:true}),stone2:new THREE.MeshLambertMaterial({color:0x665749,flatShading:true}),adobe:new THREE.MeshLambertMaterial({color:0xa66f48,flatShading:true}),cloth:new THREE.MeshLambertMaterial({color:0xa45f43,flatShading:true}),wood:new THREE.MeshLambertMaterial({color:0x5c3926,flatShading:true})};
  function box(g,w,h,d,m,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=!mobile;o.receiveShadow=true;g.add(o);return o}
  function tree(g,x,z,s=1){const y=W.groundY(x,z);box(g,.45,3.8*s,.45,mats.wood,x,y+1.9*s,z);box(g,2.4*s,1.1*s,2.1*s,mats.darkLeaf,x,y+4.1*s,z);box(g,1.8*s,.9*s,1.8*s,mats.grass,x+.4*s,y+4.75*s,z-.2*s)}
  function grassPatch(g,x,z,s=1){const y=W.groundY(x,z);for(let i=0;i<3;i++){const a=(i-1)*.45*s;const q=box(g,.12,.8*s,.12,i===1?mats.grass:mats.dry,x+a,y+.4*s,z+(i%2)*.2);q.rotation.z=(i-1)*.18}}
  function waterPatch(g,x,z,r=5){const y=W.groundY(x,z)+.06;const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.08,18),mats.water);m.position.set(x,y,z);m.receiveShadow=false;g.add(m)}
  function ruin(g,x,z,s=1){const y=W.groundY(x,z);box(g,4.2*s,.7*s,4.2*s,mats.stone,x,y+.35*s,z);box(g,.7*s,3.5*s,.7*s,mats.stone2,x-1.45*s,y+1.75*s,z-1.2*s);box(g,.7*s,2.4*s,.7*s,mats.stone2,x+1.3*s,y+1.2*s,z+1.15*s);const lint=box(g,3.2*s,.5*s,.7*s,mats.stone,x,y+3.2*s,z-1.2*s);lint.rotation.z=.08}
  function roadMarker(g,x,z){const y=W.groundY(x,z);box(g,.5,.28,.5,mats.stone,x,y+.14,z);box(g,.18,1.35,.18,mats.wood,x,y+.8,z)}
  function disposeGroup(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose?.()});scene.remove(g)}
  function decorateChunk(cx,cz){const key=`${cx},${cz}`;if(V.decorated.has(key))return;V.decorated.add(key);const g=new THREE.Group();g.name=`visual12-${key}`;const minX=cx*W.CHUNK_SIZE,minZ=cz*W.CHUNK_SIZE;const count=mobile?4:8;for(let i=0;i<count;i++){const x=minX+5+W.hash2i(cx,cz,12000+i*5)*(W.CHUNK_SIZE-10);const z=minZ+5+W.hash2i(cx,cz,12001+i*5)*(W.CHUNK_SIZE-10);const b=W.biomeAt(x,z),r=W.hash2i(cx,cz,12002+i*5);if(W.roadAt(x,z)&&r>.62){roadMarker(g,x,z);continue}if(b==='fertile'){if(r>.45)tree(g,x,z,.7+W.hash2i(cx,cz,12003+i)*.55);else grassPatch(g,x,z,1.2)}else if(b==='steppe'){grassPatch(g,x,z,.9+W.hash2i(cx,cz,12004+i)*.6)}else if(b==='oasis'){if(r>.35)tree(g,x,z,.75);if(i===0)waterPatch(g,x,z,3.5+W.hash2i(cx,cz,12005)*2.5)}else if(b==='rocky'&&r>.76)ruin(g,x,z,.65+W.hash2i(cx,cz,12006+i)*.4);else if(b==='desert'&&r>.88)ruin(g,x,z,.5)}scene.add(g);V.groups.set(key,g)}
  function cleanupChunks(cx,cz){const keep=(mobile?2:3)+1;for(const[key,g]of [...V.groups]){const[gX,gZ]=key.split(',').map(Number);if(Math.abs(gX-cx)>keep||Math.abs(gZ-cz)>keep){disposeGroup(g);V.groups.delete(key);V.decorated.delete(key)}}}
  function settlementDefOf(s){return s?.def||s?.definition||s?.source||s}
  function beautifySettlement(s){const d=settlementDefOf(s);if(!d?.id||V.settlements.has(d.id))return;V.settlements.add(d.id);const g=new THREE.Group();g.name=`city12-${d.id}`;const city=d.type==='city';const radius=city?18:10;const count=city?(mobile?5:9):(mobile?3:5);for(let i=0;i<count;i++){const a=i/count*Math.PI*2+(W.randAt(d.x,d.z,13000+i)-.5)*.35;const rr=radius*(.38+.48*W.randAt(d.x,d.z,13100+i));const x=d.x+Math.cos(a)*rr,z=d.z+Math.sin(a)*rr,y=W.groundY(x,z);const w=city?3.8+W.randAt(x,z,13200)*2.5:3.2+W.randAt(x,z,13201)*1.6;const h=city?2.8+W.randAt(x,z,13202)*2.5:2.3+W.randAt(x,z,13203)*1.4;box(g,w,h,w*.78,i%2?mats.adobe:mats.stone,x,y+h/2,z);box(g,w+.35,.32,w*.78+.35,mats.wood,x,y+h+.16,z)}if(city){const gateY=W.groundY(d.x,d.z+radius);box(g,6,6,2.2,mats.stone2,d.x,gateY+3,d.z+radius);box(g,2.4,4.2,2.4,mats.adobe,d.x,gateY+2.1,d.z+radius+.2);box(g,2.2,.9,.12,mats.cloth,d.x+1.1,gateY+7.4,d.z+radius);box(g,.14,6,.14,mats.wood,d.x,gateY+5,d.z+radius)}else{const wellY=W.groundY(d.x,d.z);const well=new THREE.Mesh(new THREE.CylinderGeometry(1.5,1.7,1,12),mats.stone);well.position.set(d.x,wellY+.5,d.z);g.add(well)}scene.add(g);V.settlementGroups.set(d.id,{g,d})}
  function updateSettlements(){if(typeof generatedSettlements==='undefined')return;for(const s of generatedSettlements.values())beautifySettlement(s)}
  function cleanupSettlements(){for(const[id,o]of [...V.settlementGroups]){if(Math.hypot(player.mesh.position.x-o.d.x,player.mesh.position.z-o.d.z)>220){disposeGroup(o.g);V.settlementGroups.delete(id);V.settlements.delete(id)}}}
  function atmosphere(){if(typeof L06!=='undefined'&&L06.caveMode)return;const b=W.biomeAt(player.mesh.position.x,player.mesh.position.z);if(b===V.atmo)return;V.atmo=b;const bg={desert:0xc9b27f,rocky:0xb7aaa0,steppe:0xb6c39b,fertile:0x9fbf9a,oasis:0x8fbab5}[b]||0xb8d0d1;scene.background.setHex(bg);scene.fog.color.setHex(bg);scene.fog.density=mobile?(b==='rocky'?.0068:.0059):(b==='rocky'?.0052:.0044)}
  function tick(){const cx=Math.floor(player.mesh.position.x/W.CHUNK_SIZE),cz=Math.floor(player.mesh.position.z/W.CHUNK_SIZE),k=`${cx},${cz}`;if(k!==V.lastChunk){V.lastChunk=k;const r=mobile?2:3;for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++)decorateChunk(cx+x,cz+z);cleanupChunks(cx,cz);updateSettlements();cleanupSettlements()}atmosphere()}
  let last=0;function loop(t){if(t-last>350){last=t;try{tick()}catch(e){console.warn('Wilderness visuals:',e)}}requestAnimationFrame(loop)}requestAnimationFrame(loop);window.WildernessVisual12=V;
})();